### ISSUE TITLE
Fail to install via helm on Kubeadm due to no matches for kind "FederatedTypeConfig" in version "core.kubefed.k8s.io/v1beta1"

### ISSUE THREAD

**Issue by bingohuang** [kubernetes-sigs/kubefed#1021]
**What happened**:
I refer to helm chart installation guide to install  a KubeFed control plane, but get this error:
```
$ helm install kubefed --name kubefed  --namespace kube-federation-system
Error: validation failed: [unable to recognize "": no matches for kind "FederatedTypeConfig" in version "core.kubefed.k8s.io/v1beta1", unable to recognize "": no matches for kind "KubeFedConfig" in version "core.kubefed.k8s.io/v1beta1"]
```

**What you expected to happen**:
Successful installation

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a local cluster with version 1.14.1 by kubeadm
2. Follow the helm instruction guide
`helm install kubefed --name kubefed  --namespace kube-federation-system`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`)
k8s:
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```
helm:
```
Client: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
```
- KubeFed version
```
kubefedctl version: version.Info{Version:"v0.1.0-rc3", GitCommit:"d188d227fe3f78f33d74d9a40b3cb701c471cc7e", GitTreeState:"clean", BuildDate:"2019-06-25T00:27:58Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Scope of installation (namespaced or cluster)
namespaced 

- Others

/kind bug

**Comment by marun** [comment]
Did you follow the [chart install instructions](https://github.com/kubernetes-sigs/kubefed/tree/master/charts/kubefed#installing-the-chart) to install a released chart? The helm command you are using specifies neither a chart repo nor the chart version.  As per the documentation, the following should work once the chart repo has been configured:

```bash
helm install kubefed-charts/kubefed --name kubefed --version=<x.x.x> --namespace kube-federation-system
```
