### ISSUE TITLE
cloudn`t join the federation v2 by the kubeadm

### ISSUE THREAD

**Issue by lidongdong536** [kubernetes-sigs/kubefed#1032]
when i use the kubeadm build two cluster and  helm install the kubefed v2, i think the operation was no trouble,then i use the right version kubefedctl to join my cluster to federation and get a wrong, i`m sure that i have config the context and i can access multi-cluster by remote kubectl,cloud the user guide add the step 4 build federation v2 by use the kubeadm? >.<

/triage support

**Comment by marun** [comment]
@lidongdong536 Can you please clarify the versions of the software involved in the problem you are experiencing?

 - helm
 - kubefed helm chart
 - kubefedctl
 - kubernetes (and the deployment platform i.e. kind/minikube/gke/etc)

It would also be helpful to see the error text reported by kubefedctl when you attempt to join a cluster.
