### ISSUE TITLE
Add `kube-federated-system` namespace to the `FederatedTypeConfig` in the Helm chart

### ISSUE THREAD

**Issue by ernoaapa** [kubernetes-sigs/kubefed#1035]
**What would you like to be added**:
At the moment, the `FederatedTypeConfig` resources in the chart don't have the namespace defined. At least if you just generate the manifests with helm, the resources lack namespace and when you create the resources with `kubectl`, the resources get created to whatever namespace you're at.
By having `namespace: {{ .Release.Namespace }}` in the [federatedtypeconfig.yaml](https://github.com/kubernetes-sigs/kubefed/blob/master/charts/kubefed/templates/federatedtypeconfig.yaml#L5) would always get created to the namespace what you pass as command line argument.

**Why is this needed**:
Ensure that the default `FederatedTypeConfigs` get created to the proper namespace so that the installation is smooth for new users.
I had problems installing the kubefed and the root cause was that the resources were in the wrong namespace.

I'm new to the Kubernetes federation so might be that i'm missing something important here.

/kind feature

**Comment by marun** [comment]
Why are you attempting to create the FTCs from the chart yaml with kubectl?  If you're wanting to enable federation for a type separately from the chart I encourage you to use `kubefedctl enable` instead.

Note that `kubectl apply -n <namespace>` ensures the creation in the specified namespace.
