### ISSUE TITLE
federation didn't propagate resource to the cluster

### ISSUE THREAD

**Issue by konghui** [kubernetes-sigs/kubefed#1036]
**What happened**:
I try to create a federation Namespace and federation deployment, it seems didn't propagate the namespace and deployment to the subcluster.

yamlfile:

```yaml
apiVersion: types.kubefed.k8s.io/v1beta1
kind: FederatedNamespace
metadata:
  name: pf-k8s-federation
spec:
  placement:
    clusters:
    - name: cluster1
    - name: cluster2

```

describe federationNamespace output:

```
➜  ~ kubectl describe federatednamespaces.types.kubefed.k8s.io
Name:         pf-k8s-federation
Namespace:    default
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"types.kubefed.k8s.io/v1beta1","kind":"FederatedNamespace","metadata":{"annotations":{},"name":"pf-k8s-federation","namespac...
API Version:  types.kubefed.k8s.io/v1beta1
Kind:         FederatedNamespace
Metadata:
  Creation Timestamp:  2019-07-10T03:10:05Z
  Generation:          1
  Resource Version:    20805433
  Self Link:           /apis/types.kubefed.k8s.io/v1beta1/namespaces/default/federatednamespaces/pf-k8s-federation
  UID:                 370ff223-a2c0-11e9-93f9-fa163e51daaa
Spec:
  Placement:
    Clusters:
      Name:  cluster1
      Name:  cluster2
Events:      <none>
```

**What you expected to happen**:
subresource, such as namespace, deployment should exists in the cluster1 and cluster2, but I can't find namespace pf-k8s-federation in both two clusters.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Both cluster1 and cluster2 was at ready status

It seems federation informer didn't running correct.
In the federation-controller I found logs like this:
```
W0709 14:00:22.975770       6 reflector.go:270] sigs.k8s.io/kubefed/pkg/controller/util/federated_informer.go:437: watch of <nil> ended with: too old resource version: 2361258762 (2361301119)
W0709 14:03:26.044368       6 reflector.go:270] sigs.k8s.io/kubefed/pkg/controller/util/federated_informer.go:437: watch of <nil> ended with: too old resource version: 2361337726 (2361340560)
W0709 14:10:00.602006       6 reflector.go:270] sigs.k8s.io/kubefed/pkg/controller/util/federated_informer.go:437: watch of <nil> ended with: too old resource version: 20518395 (20519929)
W0709 14:10:39.642585       6 reflector.go:270] sigs.k8s.io/kubefed/pkg/controller/util/federated_informer.go:437: watch of <nil> ended with: too old resource version: 20519349 (20521205)
```

**Environment**:
- Kubernetes version: v1.14.2
- KubeFed version: v0.1.0-rc3
- Scope of installation: kube-federation-system
- Others
   Install Method: Install federation via Helm

/kind bug

**Comment by marun** [comment]
Note that a federated namespace needs to have the same name as the containing namespace.  Putting a FederatedNamespace named 'pf-k8s-federation' in namspace 'default' will have no effect. This really should result in an error event logged to the resource, though.  I'll file an issue.

**Comment by konghui** [comment]
thanks, it works well now.
