### ISSUE TITLE
Informer logging lacks type detail

### ISSUE THREAD

**Issue by marun** [kubernetes-sigs/kubefed#1083]
KubeFed's sync controller uses informers to watch federated resources in the host cluster and target resources in member clusters. The sync controller is configured with type information via the API to support the federation of types (e.g. CRDs) for which golang structs may not be available at compilation time.  Accordingly, the sync controller configures its informers with an `ObjectType` (indicating the type of resource that will be watched) of `nil`. `ObjectType` is passed by an informer to an internal `Reflector` instance, where it is used to:

1 -  check that the type of an event's object is as expected (i.e. [1](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/cache/reflector.go#L345))
2 -  indicate the type of resource that a log pertains to (e.g. [1](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/cache/reflector.go#L122), [2](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/cache/reflector.go#L201))

Passing `nil` for `ObjectType` avoids the type check to support watching resources for which a golang struct is not available, but also results in most `Reflector` log messages displaying `<nil>` instead of a type name: 

```
0806 13:49:50.180103    3856 reflector.go:131] Starting reflector <nil> (0s) from sigs.k8s.io/kubefed/pkg/controller/sync/accessor.go:161
I0806 13:49:50.180207    3856 reflector.go:169] Listing and watching <nil> from sigs.k8s.io/kubefed/pkg/controller/sync/accessor.go:161
I0806 13:49:50.180106    3856 reflector.go:169] Listing and watching <nil> from sigs.k8s.io/kubefed/pkg/controller/sync/accessor.go:156
```

Ideally `Reflector` could be configured with a `typeName` to be used in log messages. If `typeName` were not provided, it would be continue to be computed as `expectedType.String()`. A new constructor for `Reflector` and `Informer` could be added to support provision of `typeName`.

Note that KubeFed would likely prefer to supply a `typeName` of `<cluster name>/<type name>` to ensure traceability of an informer not just to a sync controller but also to the cluster it is targeting.

**Comment by marun** [comment]
Fixing this is likely to require changes to client-go (i.e. kubernetes/kubernetes) since that's where the informer and reflector code is sourced from.

@sttts @deads2k Your feedback on the feasibility of resolving this issue would be much appreciated.

**Comment by pjferrell** [comment]
@marun With a small change to reflector.go logging, an Unstructured object can be used for the expected type and GroupVersionKind could be used for logging.  If this is acceptable, I can raise PRs.

kubefed:
https://github.com/snaproute-mino/kubefed/commit/45947e974b3b8915b471473ea92af12379ccc5a6

client-go:
https://github.com/snaproute-mino/kubernetes/commit/f5e9b912be613db010b91e8a83cb48c3a1ffb054

**Comment by marun** [comment]
@pjferrell I'm already working on this after discussing with @sttts earlier this week. He indicated that Unstructured support was desirable for the reflector but only to the degree that the kind be checked for and logged (vs gvk).

**Comment by pjferrell** [comment]
Ok, just thought I'd share the diffs since we had to address this internally.  IMO... as a general purpose change itd be more helpful to provide group and kind in log. 
We have some controllers handing config and state as separate kinds in same controller (would be nice for log to differentiate).  For kubefed, I could imagine multiple federatedtypes with same kind, but different groups.
