### ISSUE TITLE
Could we remove the OS check in fix-joined-kind-clusters.sh

### ISSUE THREAD

**Issue by skeeey** [kubernetes-sigs/kubefed#1110]
I used kind (`v0.4.0`) to create clusters in my ubuntu host, then I meet the same [problem](https://github.com/kubernetes-sigs/kubefed/blob/master/docs/cluster-registration.md#joining-kind-clusters-on-macos) as the MACOS

In my ubuntu host, the cluster API endpoint is `https://127.0.0.1:<random-port>` in its kubeconfig context. then I try to remove the [OS check](https://github.com/kubernetes-sigs/kubefed/blob/master/scripts/fix-joined-kind-clusters.sh#L33) in `fix-joined-kind-clusters.sh` and run the script, it works, so I think could we remove the OS check in `fix-joined-kind-clusters.sh`? and make this become a generic solution

**Comment by marun** [comment]
The only reason I can imagine the fixup script working on a linux host is if you are running docker in a VM.  If that is the case, I encourage you to deploy docker directly on the host, as the virtualization penalty is unnecessary on linux.
