### ISSUE TITLE
Failing to join a cluster

### ISSUE THREAD

**Issue by greatEncoder** [kubernetes-sigs/kubefed#1126]
**What happened**:
When trying to join a cluster kubefed throws the following error
`I0823 15:52:08.898964   83622 join.go:159] Args and flags: name cluster1, host: cluster1, host-system-namespace: kube-federation-system, kubeconfig: , cluster-context: cluster1, secret-name: , dry-run: false`
`F0823 15:52:08.953390   83622 join.go:126] Error: Error retrieving KubeFedConfig "kube-federation-system/kubefed": no matches for kind "KubeFedConfig" in version "core.kubefed.k8s.io/v1beta1"`

**What you expected to happen**:
Expected to successfully join the cluster 

**How to reproduce it (as minimally and precisely as possible)**:
install kubefed with helm chart 0.1.0-rc5 or 0.1.0-rc6
try to join a cluster with the following command: `kubefedctl join <cluster_name> --cluster-context <cluster_context> --host-cluster-context <host_cluster_context> --v=2`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`)
`Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-20T04:49:16Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"darwin/amd64"}`
`Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}`

- KubeFed version
helm chart version 0.1.0-rc5 or 0.1.0-rc5
- Scope of installation (namespaced or cluster)
both namespaced and cluster

- Others

/kind bug

**Comment by marun** [comment]
Updating to a version of `kubefedctl` >= `v0.1.0-rc5` should resolve the problem you are seeing. The groups used by kubefed api types was changed from `*.kubefed.k8s.io` to `*.kubefed.io` as of [v0.1.0-rc5](https://github.com/kubernetes-sigs/kubefed/releases/tag/v0.1.0-rc5).
