### ISSUE TITLE
DNS: feature parity with v1

### ISSUE THREAD

**Issue by pmorie** [kubernetes-sigs/kubefed#113]
This issue is to achieve feature parity for external/in-cluster DNS with v1. I believe in use-case form, this would be:

- As a user of federation, I can created a federated service and have external federated DNS both on a federation-wide and per-zone basis programmed for me, and have kubernetes cluster DNS programmed for me so that if I look up a federated service inside a cluster, I'll have it resolved to the DNS in another cluster if the service is down in my cluster

@shashidharatd's current PR (#59) gets us most of the way there - but we need some additional glue between FederatedService and MultiClusterDNSRecord to make this story complete.

**Comment by marun** [comment]
@shashidharatd What work items are required to satisfy this issue for v1beta1?

**Comment by irfanurrehman** [comment]
@pmorie I have taken the liberty to assign this to you together with @shashidharatd. Please feel free to unassign if this is not the right thing to do.
