### ISSUE TITLE
Error while adding multiple cluster to the federation pane

### ISSUE THREAD

**Issue by boopathykpm** [kubernetes-sigs/kubefed#1139]
**What happened**:
Error while adding the second cluster to the federation plane, Below is the error when trying to add the new cluster to the plane 

`Error: Error retrieving KubeFedConfig "kube-federation-system/kubefed": no matches for kind "KubeFedConfig" in version "core.kubefed.io/v1beta1"`

**What you expected to happen**:
The cluster should have got added to the federation plane 

**Environment**:
- Kubernetes version (use `kubectl version`) `v1.13.10`
- KubeFed version (`v2`)
- Scope of installation (namespaced or cluster)  `kops`

/kind bug 
/kind HelpNeeded

**Comment by marun** [comment]
I'm guessing the `kubefedctl join` invocation may be targeting the wrong host cluster, since a successful deployment ensures that the KubeFed api is available on the host cluster. What is the full command that was executed that resulted in the reported error message?

Also, what versions of kubefedctl (`kubefedctl version`) is used and what version of the chart was used to deploy the control plane?

**Comment by boopathykpm** [comment]
kubefedctl version (`v0.1.0-rc6`) 

Below is the command i used to join a cluster. 

`export KUBECONFIG="/home/federation_kubeconfig:/home/federation_one_kubeconfig"
  kubefedctl join federation --host-cluster-context federation --v=2 - **This got successful** 
  kubefedctl join federation_one --host-cluster-context federation_one --v=2 - **This is getting failed**`

**Comment by marun** [comment]
> `kubefedctl join federation --host-cluster-context federation --v=2` - **This got successful**

This command is attempting to join the cluster `federation` to a control plane in the cluster `federation`.

> `kubefedctl join federation_one --host-cluster-context federation_one --v=2` - **This is getting failed**

This command is attempting to join the cluster `federation_one` to a control plane in cluster `federation_one`. If your intention is to join the cluster to the control plane in cluster `federation`, use `--host-cluster-context federation`.

**Comment by boopathykpm** [comment]
Ah, my bad I was able to connect to the cluster now. @marun Thanks for helping me out.
