### ISSUE TITLE
CRD validation schema is not compatible with being published in OpenAPI schema

### ISSUE THREAD

**Issue by qiyongxiao** [kubernetes-sigs/kubefed#1141]
Dears Authors:
    I want to use 'kubectl explain ' to show FederatedSecret's substance. I don't know how to show it. While I do this command, and show below:
```
[root@master1 docs]# kubectl explain FederatedSecret
error: Couldn't find resource for "types.kubefed.io/v1beta1, Kind=FederatedSecret"
```
Could I use this kinds of command to show it's substances? Please tell me how to show it.
Thanks.

**Comment by marun** [comment]
`kubectl explain` support for CRDs requires the `CustomResourcePublishOpenAPI` feature flag to be set to `true`.  In Kube 1.14 this feature was alpha and disabled by default. In Kube 1.15 the feature was beta and enabled by default. If you are still on 1.14, you can enable the feature flag as per the documentation:

https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

On Kube 1.15, though, I'm getting an empty result for kubefed api types instead of an error.  It appears that our CRDS (both generated by KubeBuilder 1.x and created dynamically) do not have validation schema that is compatible with being published in the OpenAPI schema (which `kubectl explain` depends on), as per the following status condition:

```
  - lastTransitionTime: "2019-09-06T13:29:24Z"
    message: 'spec.validation.openAPIV3Schema.type: Required value: must not be empty
      at the root'
    reason: Violations
    status: "True"
    type: NonStructuralSchema
```

**Comment by marun** [comment]
#1142 ensures federated types will be included in OpenAPI schema.  Addressing core type inclusion likely requires updating the vendored version of kubebuilder to 2.x.

**Comment by marun** [comment]
Note that `kubectl explain` doesn't actually provide much information. Services and Spec are the most useful fields and even for core types very little detail is provided:

```
    Spec defines the behavior of a service.
     https://git.k8s.io/community/contributors/devel/api-conventions.md#spec-and-status

   status       <Object>
     Most recently observed status of the service. Populated by the system.
     Read-only. More info:
     https://git.k8s.io/community/contributors/devel/api-conventions.md#spec-and-status
```

The kubefed userguide is likely to be a more useful source of detail of federated types.

**Comment by qiyongxiao** [comment]
> #1142 ensures federated types will be included in OpenAPI schema. Addressing core type inclusion likely requires updating the vendored version of kubebuilder to 2.x.

I deploy it with version 2.0.0-alpha,this is the information
![image](https://user-images.githubusercontent.com/7349963/64437382-c8bff180-d0f8-11e9-91b8-c5c7f121383e.png)

**Comment by qiyongxiao** [comment]
> `kubectl explain` support for CRDs requires the `CustomResourcePublishOpenAPI` feature flag to be set to `true`. In Kube 1.14 this feature was alpha and disabled by default. In Kube 1.15 the feature was beta and enabled by default. If you are still on 1.14, you can enable the feature flag as per the documentation:
> 
> https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/
> 
> On Kube 1.15, though, I'm getting an empty result for kubefed api types instead of an error. It appears that our CRDS (both generated by KubeBuilder 1.x and created dynamically) do not have validation schema that is compatible with being published in the OpenAPI schema (which `kubectl explain` depends on), as per the following status condition:
> 
> ```
>   - lastTransitionTime: "2019-09-06T13:29:24Z"
>     message: 'spec.validation.openAPIV3Schema.type: Required value: must not be empty
>       at the root'
>     reason: Violations
>     status: "True"
>     type: NonStructuralSchema
> ```

My cluster version is v1.13.7, has not upgrade to v1.14.x even  higher

**Comment by qiyongxiao** [comment]
@marun Thanks you very much.

**Comment by qiyongxiao** [comment]
> Note that `kubectl explain` doesn't actually provide much information. Services and Spec are the most useful fields and even for core types very little detail is provided:
> 
> ```
>     Spec defines the behavior of a service.
>      https://git.k8s.io/community/contributors/devel/api-conventions.md#spec-and-status
> 
>    status       <Object>
>      Most recently observed status of the service. Populated by the system.
>      Read-only. More info:
>      https://git.k8s.io/community/contributors/devel/api-conventions.md#spec-and-status
> ```
> 
> The kubefed userguide is likely to be a more useful source of detail of federated types.

I known it for wanted to add more configurations to the deployment.
