### ISSUE TITLE
Editing a placement does not propagate deletion

### ISSUE THREAD

**Issue by asincu** [kubernetes-sigs/kubefed#1147]
**What happened**:
Removing the member cluster from the placement of a resource does not propagate on that cluster.

**What you expected to happen**:
By removing one of the clusters from the placement of a resource, I would expect that kubefed would ensure deletion.

**How to reproduce it (as minimally and precisely as possible)**:
I have two clusters joined: cluster a is the host cluster and cluster b is the member cluster. I have created a FederatedConfigMap and propagate it on both clusters. After ensuring that the ConfigMap was created on both clusters, I have edited the placement of the FederatedConfigMap and removed the member cluster. 

```➜  scripts git:(master) ✗ kubectl edit federatedconfigmaps myfedconfigmap -ntest-placement
federatedconfigmap.types.kubefed.io/myfedconfigmap edited
➜  scripts git:(master) ✗ kubectl describe federatedconfigmaps myfedconfigmap -ntest-placement
Name:         myfedconfigmap
Namespace:    test-placement
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"types.kubefed.io/v1beta1","kind":"FederatedConfigMap","metadata":{"annotations":{},"name":"myfedconfigmap","namespace":"tes...
API Version:  types.kubefed.io/v1beta1
Kind:         FederatedConfigMap
Metadata:
  Creation Timestamp:  2019-09-09T23:18:29Z
  Finalizers:
    kubefed.io/sync-controller
  Generation:        4
  Resource Version:  179597
  Self Link:         /apis/types.kubefed.io/v1beta1/namespaces/test-placement/federatedconfigmaps/myfedconfigmap
  UID:               00a3bd39-745d-4e75-a0d8-88a612188be5
Spec:
  Placement:
    Clusters:
      Name:  a
  Template:
    Data:
      A:  a and b
Status:
  Clusters:
    Name:  a
  Conditions:
    Last Transition Time:  2019-09-09T23:24:49Z
    Last Update Time:      2019-09-09T23:26:31Z
    Status:                True
    Type:                  Propagation
Events:
  Type     Reason                 Age                   From                           Message
  ----     ------                 ----                  ----                           -------
  Normal   CreateInCluster        11m                   federatedconfigmap-controller  Creating ConfigMap "test-placement/myfedconfigmap" in cluster "a"
  Normal   UpdateInCluster        10m (x7 over 11m)     federatedconfigmap-controller  Updating ConfigMap "test-placement/myfedconfigmap" in cluster "b"
  Warning  CreateInClusterFailed  9m53s (x8 over 11m)   federatedconfigmap-controller  Failed to create ConfigMap "test-placement/myfedconfigmap" in cluster "b": An update will be attempted instead of a creation due to an existing resource
  Normal   CreateInCluster        6m17s (x21 over 11m)  federatedconfigmap-controller  Creating ConfigMap "test-placement/myfedconfigmap" in cluster "b"
➜  scripts git:(master) ✗ kubectl describe configmaps -n test-placement --context a
Name:         myfedconfigmap
Namespace:    test-placement
Labels:       kubefed.io/managed=true
Annotations:  <none>


Data
====
A:
----
a and b
Events:  <none>
➜  scripts git:(master) ✗ kubectl describe configmaps -n test-placement --context b
Name:         myfedconfigmap
Namespace:    test-placement
Labels:       <none>
Annotations:  <none>


Data
====
A:
----
a and b
Events:  <none>
```

**Anything else we need to know?**:
I also tried removing the host cluster and the resource was successfully removed. Also, the member cluster seems to be missing label ` kubefed.io/managed=true`

**Environment**:
- Kubernetes version: `1.14.1`
- KubeFed version `0.1.0-rc6`
- Scope of installation `kube-federation-system`
- Others: Using kind to create clusters: `kind version v0.4.0`

/kind bug

**Comment by marun** [comment]
If you add the managed label to the configmap in cluster b, I would expect the resource to be deleted. 

Any idea how the managed label came to be removed from the configmap in cluster b? All resources created in member clusters by KubeFed controllers will include the managed label, and any existing resources for which placement exists will be adopted by KubeFed by the addition of the managed label. KubeFed only removes the managed label from a resource when an [orphaning deletion](https://github.com/kubernetes-sigs/kubefed/blob/master/docs/userguide.md#deletion-policy) of the managing federated resource is performed, in which case all managed resources in member clusters will have the managed label removed. By design, KubeFed will not delete a resource that does not have the managed label (as per #549).
