### ISSUE TITLE
Explore ways to facilitate deploying 'normal' k8s resources to federation

### ISSUE THREAD

**Issue by pmorie** [kubernetes-sigs/kubefed#115]
Created after discussion in Jun 13 2018 WG meeting. This issue is to explore ways to allow people to deploy workloads expressed in 'normal' k8s resources to federation with minimal or no modification. There's a very wide spectrum on things that we could do here, and there may be more than one thing that makes sense to do to provide different types of facilitation (ie, transforming YAML resources to having direct integration in tools like helm, to any number of other things).

**Comment by marun** [comment]
I think this is being partially resolved with the (ongoing) implementation of `kubefed federate`.   Helm integration would be the logical next step, and a separate issue should be filed for that at some point..
