### ISSUE TITLE
Artifacts created by join should not include the host cluster context name

### ISSUE THREAD

**Issue by marun** [kubernetes-sigs/kubefed#1155]
As per the following log provided by a user on slack, it is not possible to join a cluster when the name of the supplied host cluster context is not a valid DNS-1123 subdomain: 

```
ubuntu@ip-10-1-1-5:~$ kubefedctl join k8s-east --cluster-context kubernetes-admin@kubernetes --host-cluster-context kubernetes-admin@kubernetes --v=2
I0930 19:55:00.946400   10067 join.go:159] Args and flags: name k8s-east, host: kubernetes-admin@kubernetes, host-system-namespace: kube-federation-system, kubeconfig: , cluster-context: kubernetes-admin@kubernetes, secret-name: , dry-run: false
I0930 19:55:01.018174   10067 join.go:238] Performing preflight checks.
I0930 19:55:01.020196   10067 join.go:244] Creating kube-federation-system namespace in joining cluster
I0930 19:55:01.022317   10067 join.go:377] Already existing kube-federation-system namespace
I0930 19:55:01.022339   10067 join.go:252] Created kube-federation-system namespace in joining cluster
I0930 19:55:01.022353   10067 join.go:398] Creating service account in joining cluster: k8s-east
I0930 19:55:01.023829   10067 join.go:476] Could not create service account kube-federation-system/k8s-east-kubernetes-admin@kubernetes in target cluster k8s-east due to: ServiceAccount "k8s-east-kubernetes-admin@kubernetes" is invalid: metadata.name: Invalid value: "k8s-east-kubernetes-admin@kubernetes": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
I0930 19:55:01.023855   10067 join.go:403] Error creating service account:  in joining cluster: k8s-east due to: ServiceAccount "k8s-east-kubernetes-admin@kubernetes" is invalid: metadata.name: Invalid value: "k8s-east-kubernetes-admin@kubernetes": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
F0930 19:55:01.023873   10067 join.go:126] Error: ServiceAccount "k8s-east-kubernetes-admin@kubernetes" is invalid: metadata.name: Invalid value: "k8s-east-kubernetes-admin@kubernetes": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

The error occurred because join composed the name of the service account in the joining cluster with the key used to identify the host cluster context (`kubernetes-admin@kubernetes`), and though this key is a valid context name it contains a character (`@`) which is not considered valid for a resource name.

A context name can change over time and is only supplied on the command line (it is not stored by the KubeFed control plane) which makes it a poor candidate for inclusion in the name of artifacts in the joining cluster. If the context name were to change between `join` and `unjoin` of a cluster, `unjoin` would be unable to identify the service account, roles, and rolebindings that should be removed from the member cluster.

/kind bug

**Comment by marun** [comment]
cc: @xunpan

**Comment by marun** [comment]
Note that there are 2 possible workarounds pending a fix:

 - rename the host cluster context (e.g. `kubectl config rename-context <old name> <new name>`)
   - this works fine so long as the context remains stable between `join` and `unjoin`
 - supply `--host-cluster-name` to 'kubefedctl` `join` or `unjoin`
   - this requires that the user supply the same argument across `join` and `unjoin`

**Comment by irfanurrehman** [comment]
@marun I am not sure if this should be treated as a bug. 
In the abscence of an unique global identifier which a cluster can be identified with we have to depend on something provided by the user, for example the local kubneconfig cluster context name or the supplied `--host-cluster-name`.
I also think its reasonable enough to ask a user to provide the same name (either the kubeconfig cluster context or the user chosen cluster name) for join and unjoin. 

Probably adding more documentation around this might help the usage.

**Comment by marun** [comment]
@irfanurrehman I think it would be preferable for kubefed to generate a guid to use on deploy vs the current strategy of relying on the user to do exactly the right thing over a period of time (i.e. good is preferable to bad in the absence of perfect).

**Comment by xunpan** [comment]
@marun,
`--host-cluster-name` was introduced by (https://github.com/kubernetes-sigs/kubefed/issues/577) to address related issue. A message change or document change is easy for this as irfan metioned.

From your comments, did you mean that we generate an UUID and use it as part of generated resource name in member clusters, instead of specified name. The UUID is recorded in `KubefedCluster` for `unjoin`? If that's what we want, I think we can remove `--host-cluster-name` at the same time.

/assign

**Comment by marun** [comment]
@xunpan Correct, `--host-cluster-name` would not be necessary if the name of the host cluster (whether explicitly specified or the name of the host cluster context) were not embedded in the name of resources created in member clusters. And I don't think it has to be per-cluster - it's identifying the host cluster, not the member cluster (which already has a name unique to the control plane). Maybe it could be stored as a field in `KubeFedConfig`?
