### ISSUE TITLE
CRD validation for federated type primitives

### ISSUE THREAD

**Issue by font** [kubernetes-sigs/kubefed#116]
A goal in transitioning to CRDs (depends on #74) is to maintain the same quality of validation for the resources embedded in templates as is currently provided by first-class API types.  Potential strategies:

1. Validate via decoding of object from JSON
2. Validate via OpenAPI spec:
    - For a given template resource (e.g. `FederatedSecret`), find the `FederatedTypeConfig` that specifies the template type.
    - For the target type of the `FederatedTypeConfig`, retrieve the OpenAPI spec.
    - Validate the target resource embedded in the template with the OpenAPI spec.
    - Note that the OpenAPI spec generated may lack the ability to validate string values as part of an enumerated string type e.g. `imagePullPolicy` being either `Always`, `Never`, or `IfNotPresent`. This may require updating the OpenAPI generation utility.

**Comment by marun** [comment]
This shouldn't block release of v1alpha1.

**Comment by marun** [comment]
Looks like dry-run has been implemented server-side in kube 1.12, and that would seem to offer higher fidelity validation than could be achieved with openapi.  The only catch is that a generic webhook validating an arbitrary type would need to have permission/quota/etc to actually create the target resource.

**Comment by marun** [comment]
Each crd generated for a federated type with `kubefed2 enable` includes a validation schema (sourced from openapi or crd schema).  Dry-run validation is still suggested to provide more exact validation, and as mentioned perviously a generic webhook is probably the best way to accomplish this.

**Comment by font** [comment]
See https://github.com/kubernetes-sigs/kubefed/pull/1063#discussion_r308701486 for additional validations that would be useful.
