### ISSUE TITLE
Helm ERROR when installing kubefed-charts/kubefed

### ISSUE THREAD

**Issue by ijaveed** [kubernetes-sigs/kubefed#1161]
helm install kubefed-charts/kubefed --name kubefed --version=0.1.0-rc6 --namespace kube-federation-system 

**Error: CustomResourceDefinition.apiextensions.k8s.io "federatedclusterroles.types.kubefed.io" is invalid: spec.validation.openAPIV3Schema.properties[spec].properties[placement].properties[clusterSelector].properties[matchLabels].additionalProperties: Forbidden: additionalProperties cannot be set to false**

$ kubectl version
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6+coreos.0", 

**What happened**:
Received the aboive Error message when applying kubefed 0.1.0-6 Helm Chart

**What you expected to happen**:
Install Helm chart on Kubernetes Cluster

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
Development

- Kubernetes version (use `kubectl version`)
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-eks-fa4c70", GitCommit:"fa4c703fa1706fac99d00d7f1f2080e9d4cc7eed", GitTreeState:"clean", BuildDate:"2019-07-23T03:14:24Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6+coreos.0", GitCommit:"c2aac694c2c7373dfe3ad81f47fc3cbc70a5a8fa", GitTreeState:"clean", BuildDate:"2018-03-21T21:54:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

- KubeFed version
0.1.0-rc6 -

- Scope of installation (namespaced or cluster)

- Others

/kind bug

**Comment by marun** [comment]
KubeFed depends on having a minimum level of CRD support, and as per the [helm chart installation guide](https://github.com/kubernetes-sigs/kubefed/blob/master/charts/kubefed/README.md), that requires Kube >= `v1.13`.
