### ISSUE TITLE
Enabling federation of the API type StorageClass not working.

### ISSUE THREAD

**Issue by jacobjohnanda** [kubernetes-sigs/kubefed#1165]
DESCRIPTION:-
Enabling federation of the API type StorageClass not working.

STEPS:-
1. Enable federation for the API type StorageClass
ubuntu@ip-172-23-1-87:~/trident-installer$ kubefedctl enable storageclass
customresourcedefinition.apiextensions.k8s.io/federatedstorageclasses.types.kubefed.io created
federatedtypeconfig.core.kubefed.io/storageclasses.storage.k8s.io created in namespace kube-federation-system

2.  Verifying API type is installed on all member clusters
ubuntu@ip-172-23-1-87:~/trident-installer$ for c in ${CLUSTER_CONTEXTS}; do     echo ----- ${c} -----;   kubectl --context=${c} api-resources --api-group=types.kubefed.io; done
----- kubernetes-admin-s1 -----
NAME                              SHORTNAMES   APIGROUP           NAMESPACED   KIND
federatedclusterroles                          types.kubefed.io   false        FederatedClusterRole
federatedconfigmaps               fcm          types.kubefed.io   true         FederatedConfigMap
federateddeployments              fdeploy      types.kubefed.io   true         FederatedDeployment
federatedingresses                fing         types.kubefed.io   true         FederatedIngress
federatedjobs                                  types.kubefed.io   true         FederatedJob
federatednamespaces               fns          types.kubefed.io   true         FederatedNamespace
federatedpersistentvolumeclaims   fpvc         types.kubefed.io   true         FederatedPersistentVolum               eClaim
federatedpersistentvolumes        fpv          types.kubefed.io   false        FederatedPersistentVolum               e
federatedreplicasets              frs          types.kubefed.io   true         FederatedReplicaSet
federatedsecrets                               types.kubefed.io   true         FederatedSecret
federatedserviceaccounts          fsa          types.kubefed.io   true         FederatedServiceAccount
federatedservices                 fsvc         types.kubefed.io   true         FederatedService
federatedstorageclasses           fsc          types.kubefed.io   false        FederatedStorageClass
----- kubernetes-admin-s2 -----
NAME                              SHORTNAMES   APIGROUP           NAMESPACED   KIND
federatedclusterroles                          types.kubefed.io   false        FederatedClusterRole
federatedconfigmaps               fcm          types.kubefed.io   true         FederatedConfigMap
federateddeployments              fdeploy      types.kubefed.io   true         FederatedDeployment
federatedingresses                fing         types.kubefed.io   true         FederatedIngress
federatedjobs                                  types.kubefed.io   true         FederatedJob
federatednamespaces               fns          types.kubefed.io   true         FederatedNamespace
federatedpersistentvolumeclaims   fpvc         types.kubefed.io   true         FederatedPersistentVolum               eClaim
federatedpersistentvolumes        fpv          types.kubefed.io   false        FederatedPersistentVolum               e
federatedreplicasets              frs          types.kubefed.io   true         FederatedReplicaSet
federatedsecrets                               types.kubefed.io   true         FederatedSecret
federatedserviceaccounts          fsa          types.kubefed.io   true         FederatedServiceAccount
federatedservices                 fsvc         types.kubefed.io   true         FederatedService
federatedstorageclasses           fsc          types.kubefed.io   false        FederatedStorageClass

3. Create a StorageClass
apiVersion: types.kubefed.io/v1beta1
kind: FederatedStorageClass
metadata:
  name: local
spec:
  template:
    provisioner: csi.trident.netapp.io
    reclaimPolicy: Retain
    allowVolumeExpansion: true
    placement:
        clusters:
        - name: netlg0y6s7
        - name: netnbto2q2
 4. **But now local storage classes are not created**
ubuntu@ip-172-23-1-87:trident-installer$ kubectl --context kubernetes-admin-s1 get sc
NAME            PROVISIONER             AGE
default         kubernetes.io/aws-ebs   2d2h
gp2 (default)   kubernetes.io/aws-ebs   2d2h
ubuntu@ip-172-23-1-87:trident-installer$ kubectl --context kubernetes-admin-s2 get sc
NAME            PROVISIONER             AGE
default         kubernetes.io/aws-ebs   2d2h
gp2 (default)   kubernetes.io/aws-ebs   2d2h

5. We are able to list the fsc on the first cluster but not  the second

ubuntu@ip-172-23-1-87:trident-installer$ kubectl --context kubernetes-admin-s1 get fsc
NAME    AGE
local   41m
ubuntu@ip-172-23-1-87:trident-installer$ kubectl --context kubernetes-admin-s2 get fsc
No resources found.

**What happened**:
local storage class was not created
**What you expected to happen**:
local storage classes on both the federated clusters should be created.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

    Kubernetes version (use kubectl version)
    ubuntu@ip-172-23-1-146:~$ kubectl version
    Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
    Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

    KubeFed version
    v2 -version=0.1.0-rc6

    Scope of installation (namespaced or cluster)
    cluster

    Others

/kind bug

**Comment by marun** [comment]
- Federated resources are input for federated controllers, so for normal use of KubeFed they only need to exist on the host cluster rather than all clusters.
- I recommend [checking the propagation status](https://github.com/kubernetes-sigs/kubefed/blob/master/docs/userguide.md#propagation-status) of a federated CR if it is not propagating as expected.
- If propagation status is not conclusive, I recommend:
  - [Checking the status of member clusters](https://github.com/kubernetes-sigs/kubefed/blob/master/docs/cluster-registration.md#checking-status-of-joined-clusters)
     - If an error condition exists, more detail will appear in the [controller log](https://github.com/kubernetes-sigs/kubefed/blob/master/docs/userguide.md#troubleshooting)
   - [Check the status of the CRD](https://github.com/kubernetes-sigs/kubefed/blob/master/docs/userguide.md#troubleshooting)
 - If propagation status, cluster status and CRD status prove inconclusive, I recommend [checking the logs for the kubefed controller](https://github.com/kubernetes-sigs/kubefed/blob/master/docs/userguide.md#troubleshooting)

**Comment by jacobjohnanda** [comment]
Thank you for the response. When i do a describe on the FederatedStorageClass i get the following details. It looks like  propagation status is true. but i dont see local storage classes being created.

ubuntu@ip-172-23-1-87:~$ kubectl describe fsc local
Name:         local
Namespace:
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"types.kubefed.io/v1beta1","kind":"FederatedStorageClass","metadata":{"annotations":{},"name":"local"},"spec":{"template":{"...
API Version:  types.kubefed.io/v1beta1
Kind:         FederatedStorageClass
Metadata:
  Creation Timestamp:  2019-10-30T13:39:31Z
  Finalizers:
    kubefed.io/sync-controller
  Generation:        1
  Resource Version:  295414
  Self Link:         /apis/types.kubefed.io/v1beta1/federatedstorageclasses/local
  UID:               490430a0-ca8c-4901-acc3-faa5ec144fd2
Spec:
  Template:
    Allow Volume Expansion:  true
    Placement:
      Clusters:
        Name:        netlg0y6s7
        Name:        netnbto2q2
    Provisioner:     csi.trident.netapp.io
    Reclaim Policy:  Retain
Status:
  Conditions:
    Last Transition Time:  2019-10-30T13:39:31Z
    Last Update Time:      2019-10-30T13:39:31Z
    Status:                True
    Type:                  Propagation
Events:                    <none>

**Comment by marun** [comment]
@jacobjohnanda Propagation status is true, but the cluster names declared for placement do not appear in the propagation status which is an indication that the named clusters are not actually known to KubeFed. I think someone filed a bug on that issue but I can't seem to find it right now. I suggest:

 - checking the names of member clusters
   - `kubectl -n kube-federation-system get kubefedclusters`
 - consider using [selector-based placement](https://github.com/kubernetes-sigs/kubefed/blob/master/docs/userguide.md#using-cluster-selector) rather than hard-coding cluster names

**Comment by marun** [comment]
@jacobjohnanda As per my previous comment, have you checked the controller logs?

**Comment by damoresa** [comment]
Good afternoon,

This may not be the right place to ask, but I've been digging for information about the FederatedStorageClass type and I've been unable to find anything within this repository or even Googling about it.
I tried enabling the type on my federation and it worked, I've been able to deploy a wrongly formatted object which failed to be deployed, but the controller seems to work.

Would you be kind enough to point me to the FederatedStorageClass documentation or at least provide me it's proper schema?
Thank you for your time!

**Comment by hectorj2f** [comment]
I have recently tested the federation of a storageclass and it worked without any problem.

**Comment by rushins** [comment]
@hectorj2f : Could you please provide the details or how this worked. i am running into some issues with netapp trident

**Comment by rushins** [comment]
@hectorj2f : could you please share your federatedstorageclass.yaml and federatedstoragepvc.yaml along with the POD.yaml which was using federatedstroageclass , basically i want to compare my configuration as well along with trident driver.i can share my files if needed .

can you share.
