### ISSUE TITLE
docs about kubefed on kubernetes website is outdated

### ISSUE THREAD

**Issue by Colstuwjx** [kubernetes-sigs/kubefed#1173]
Hi team,

**What would you like to be added**:
I know it's not a good place to ask questions, but the [federation page](https://kubernetes.io/docs/tasks/federation/) from kubernetes website is outdated, see also [website no.17736](https://github.com/kubernetes/website/issues/17736), [website no.16776](https://github.com/kubernetes/website/issues/16776) issues.

maybe we should make the pages under [federation](https://kubernetes.io/docs/tasks/federation/) more clearly, and update the pages from federation v1 to v2 (with contents and links) if it's needed, or just keep someone for federation v1 and mark it as deprecated.

**Why is this needed**:
since I only find out the related [docs](https://github.com/kubernetes-sigs/kubefed/tree/master/docs) for kubefed at our repo, I submitted this issue and wishes to build a better user experience for those users who visit the kubernetes website, and want to have a panorama of kubernetes.

/kind feature

**Comment by Colstuwjx** [comment]
@xunpan Shall we take a look about this issue? The kubernetes website didn't maintain any docs about kubefed ( aka federation v2 ), what's the next plan about this part?

IMO, I think kill all related v1 docs and just link to our [kubefed repo docs](https://github.com/kubernetes-sigs/kubefed/tree/master/docs) should be current solution, see [PR 17949](https://github.com/kubernetes/website/pull/17949).

It will be appreciated if you could add some ideas with kubefed OWNERS sight.
Thanks.

**Comment by xunpan** [comment]
I agree with you that `kubefed` document should be used to replace obsolete federation v1 document. 

For the follow up, I guess @pmorie, @quinton-hoole may know when&how to make it work.

**Comment by kbhawkey** [comment]
@Colstuwjx , Is this issue ready to close?

**Comment by Colstuwjx** [comment]
Yes, but the kubefed document is still not maintained inside k/website repo. I'd like to close this issue, and for the new version documentation, I think it should be tracked by another issue.
