### ISSUE TITLE
Network failure between federated pods

### ISSUE THREAD

**Issue by Docteur-RS** [kubernetes-sigs/kubefed#1177]
**1) What happened**:  
Got connectivity issues in namespaces federated by kubefed.  
Everything works well for some time and then all communication using IP and DNS suddenly starts to **timeout**.  
Only happens on master cluster (even on fresh kubernetes and kubefed install).  
Services can still be accessed from outside the cluster. Its only the in-cluster communication that is being impacted (using services's and pod's ip).

**2) What you expected to happen**:  
Network should no be impacted by Kubefed

**3) How to reproduce it (as minimally and precisely as possible)**:  
Just federating a few simple deployments + ingresses and wait...  
`kubectl exec -it <SOME_FEDERATED_POD> bash -n ...`  
`curl <SERVICE_IN_SAME_NAMESPACE>`  
Ends in timeout...   

**4) Anything else we need to know?**:
Nope !

**5) Environment**:
- Kubernetes version (use `kubectl version`) => 1.14.3
- KubeFed version => RC6
- Scope of installation (namespaced or cluster) => cluster
- Others
=> Kubernetes on premise
=> Federating only 2 clusters
=> Using Gitops on master cluster

Any assistance on the matter would be greatly appreciated 🚀 

/kind bug

**Comment by hectorj2f** [comment]
@Docteur-RS 
Did you join the master cluster as part of the federated clusters ? 
Could you verify the created pod templates run on similar clusters ? Perhaps it has to do something with the properties of the federate pod.

**Comment by Docteur-RS** [comment]
Yep ! Got two clusters.  
`cluster 1` is the master and `cluster 2` is the slave.  
```shell
$ kubectl get kubefedclusters -n kube-federation-system
NAME      READY   AGE
cluster1    True    3d22h
cluster2    True    3d21h
```

I've compared 2 pods's templates on the two clusters : They are identical.

**Comment by hectorj2f** [comment]
Did you federate any other resources or just the pods ? If you only federated the pods, I don't see how kubefed could affect the networking stack of a cluster, especially if it works in cluster2 but not in cluster1 🤔 .

**Comment by Docteur-RS** [comment]
Got the following federated ressources : 
* 1 namespace
* 1 httpbin deployment with its service
* 1 custom demo_backend deployment with its service
* 1 custom demo_frontend deployment with its service
* 2 ingresses
* 1 prometheus 

Network is working in all namespaces except the kubefed one (on the master cluster). Though it does work for some time before getting stuck in timeout.

**Oh and I forgot !!**  
Deleting all the pods in the namespace restores the network for something like 20 minutes before it dies again...

**Comment by hectorj2f** [comment]
I suggest to check the networking stack in these clusters. Kubefed does not proxy these federated namespaces, it just populates resources across federated cluster and reconcile them. Check the list the federated resources to avoid having unexpected resources federated in the clusters.
I have a "similar setup" and I am not experiencing any issues.
