### ISSUE TITLE
Question:  is there a library to convert  k8s Object to FederatedObject

### ISSUE THREAD

**Issue by debianmaster** [kubernetes-sigs/kubefed#1178]
Is there a library/existing method to convert normal k8s object (Like Deployment) to FederatedObject . (Like FederatedDeployment) ?

cc  @ranbirkatal

**Comment by hectorj2f** [comment]
@debianmaster No, as far as I know. We use the unstructured objects cause anything prefixed by `Federated*` would be a federated object so there isn't a static structure. Anyway if you find some time to code a helper function that would be great. So far I have been using what you can find in the current code

**Comment by debianmaster** [comment]
thanks for the update @hectorj2f 
@ranbirkatal . can you see if we can make this a library function as discussed ^ ?

**Comment by ranbirkatal** [comment]
@debianmaster , can be worked on

**Comment by debianmaster** [comment]
@hectorj2f   i see following is working
```kubefedctl federate deployments.extensions  mycurrent-object  --dry-run -oyaml```
we will try to re-use functionality from kubefedctl and create a wrapper .

**Comment by debianmaster** [comment]
This also works
```kubefedctl federate -f test.yaml  --dry-run -oyaml```
