### ISSUE TITLE
kubefedctl join failing when joining eks clusters (endpoint validation) with Uppercase letters in FQDN Cluster API

### ISSUE THREAD

**Issue by aiziumov** [kubernetes-sigs/kubefed#1190]
**What happened**: Tried joining AWS EKS cluster to itself and failed with dns related endpoint validation error

**What you expected to happen**: successful joining to federated cluster 

**How to reproduce it (as minimally and precisely as possible)**:
in /kube/config for cluster awsfedcluster: 
`server:  "0FCAD7BC040802FA0.yl4.eu-west-2.eks.amazonaws.com" `

`
kubefedctl join awsfedcluster --cluster-context awsfedclusterctx --host-cluster-context awsfedclusterctx --v=2

I0223 21:08:33.707512   14482 join.go:159] Args and flags: name awsfedcluster, host: awsfedclusterctx, host-system-namespace: kube-federation-system, kubeconfig: , cluster-context: awsfedclusterctx, secret-name: , dry-run: false
I0223 21:08:36.123524   14482 join.go:238] Performing preflight checks.
I0223 21:08:36.141260   14482 join.go:244] Creating kube-federation-system namespace in joining cluster
I0223 21:08:36.162370   14482 join.go:377] Already existing kube-federation-system namespace
I0223 21:08:36.162399   14482 join.go:252] Created kube-federation-system namespace in joining cluster
I0223 21:08:36.162411   14482 join.go:398] Creating service account in joining cluster: awsfedcluster
I0223 21:08:36.185420   14482 join.go:408] Created service account: awsfedcluster-awsfedclusterctx in joining cluster: awsfedcluster
I0223 21:08:36.185443   14482 join.go:436] Creating cluster role and binding for service account: awsfedcluster-awsfedclusterctx in joining cluster: awsfedcluster
I0223 21:08:36.260024   14482 join.go:445] Created cluster role and binding for service account: awsfedcluster-awsfedclusterctx in joining cluster: awsfedcluster
I0223 21:08:36.260051   14482 join.go:804] Creating cluster credentials secret in host cluster
I0223 21:08:36.296132   14482 join.go:830] Using secret named: awsfedcluster-awsfedclusterctx-token-4mqrr
I0223 21:08:36.315466   14482 join.go:873] Created secret in host cluster named: awsfedcluster-9qgwf
I0223 21:08:36.361024   14482 join.go:349] Could not create federated cluster awsfedcluster due to admission webhook "kubefedclusters.core.kubefed.io" denied the request: spec.apiEndpoint: Invalid value: "0FCAD7BC040802FA0.yl4.eu-west-2.eks.amazonaws.com": must be a valid IP address, (e.g. 10.9.8.7); or a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
I0223 21:08:36.361079   14482 join.go:276] Failed to create federated cluster resource: admission webhook "kubefedclusters.core.kubefed.io" denied the request: spec.apiEndpoint: Invalid value: "0FCAD7BC040802FA0.yl4.eu-west-2.eks.amazonaws.com": must be a valid IP address, (e.g. 10.9.8.7); or a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
F0223 21:08:36.361096   14482 join.go:126] Error: admission webhook "kubefedclusters.core.kubefed.io" denied the request: spec.apiEndpoint: Invalid value: "0FCAD7BC040802FA0.yl4.eu-west-2.eks.amazonaws.com": must be a valid IP address, (e.g. 10.9.8.7); or a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
`

**Anything else we need to know?**:
Looks like exactly the same issue as #1148, but looks like the tests do not cover this situation (I did not find Uppercase FQDN examples in validation_test.go file). 

**Environment**:
- Kubernetes version (use `kubectl version`)
`Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-502bfb", GitCommit:"502bfb383169b124d87848f89e17a04b9fc1f6f0", GitTreeState:"clean", BuildDate:"2020-02-07T01:31:02Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}`
- KubeFed version
`kubefedctl version: version.Info{Version:"v0.1.0-rc6", GitCommit:"7586b42f4f477f1912caf28287fa2e0a7f68f407", GitTreeState:"clean", BuildDate:"2019-08-17T03:55:05Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}`
- Scope of installation (namespaced or cluster)
- Others

/kind bug

**Comment by jimmidyson** [comment]
This is fixed by 29c2c88608596e0f76f86c15e3a3adab8a5b6ca1 by removing host validation completely.

**Comment by aiziumov** [comment]
@jimmidyson I've checked that yesterday on the rc6 version - still got an error during cluster Join - as you can see in error log. Let me know if you need more details to review this one. I have this cluster in hands to test/check.

**Comment by jimmidyson** [comment]
29c2c88608596e0f76f86c15e3a3adab8a5b6ca1 is only in master - we're hoping to restart releases soon, but you should be able to test it out with `quay.io/kubernetes-multicluster / kubefed:canary` docker image instead of `v0.1.0-rc6`.

**Comment by aiziumov** [comment]
I made a workaround - lowercase'd FQDN of EKS endpoint in config - and it did work.

**Comment by hectorj2f** [comment]
@aiziumov can we close the issue then ?

**Comment by aiziumov** [comment]
Yes, considering the workaround and 0.20 release with Master's fixes - I think we're good to close.
