### ISSUE TITLE
Add custom kubefed metrics and expose them on a prometheus friendly format

### ISSUE THREAD

**Issue by hectorj2f** [kubernetes-sigs/kubefed#1194]
**What would you like to be added**:

I'd like to add custom metrics about kubefed that could be expose in a prometheus friendly basis analogously as other controller does in the Kubernetes ecosystem.

**Why is this needed**:

My intention would be to add custom metrics and a baseline that would enable to easily expose more metrics in the future.

/kind feature

**Comment by irajdeep** [comment]
@hectorj2f We recently started using kubefed. So as an exercise to get familiar with the codebase, I can work on this, if no one else is currently working on it.

**Comment by hectorj2f** [comment]
@irajdeep I already have a PR in the pipeline so I might create very soon. However I am willing to see if we can all benefit from your metrics as well.

**Comment by irajdeep** [comment]
@hectorj2f one of the metrics I had in mind related to how many objects kubefed failed to federate. If you haven't already implemented this metric, I can look into it.

**Comment by hectorj2f** [comment]
@irajdeep look at https://github.com/kubernetes-sigs/kubefed/pull/1196 :)

**Comment by irajdeep** [comment]
@hectorj2f nice. So I think I can wait for your PR to be merged to work on top of it to expose metrics related to objects which couldn't be federated

**Comment by hectorj2f** [comment]
I am closing the issue, we added some custom metrics now
