### ISSUE TITLE
Cannot `kubectl rollout restart` a federated deployment

### ISSUE THREAD

**Issue by abrenneke** [kubernetes-sigs/kubefed#1202]
**What happened**:

After running `kubectl rollout restart deployment X`, the restart begins, but then is overridden by the kubefed controller and basically cancelled (returned to previous ReplicaSet?) 

**What you expected to happen**:

The deployment on one cluster performs a rolling restart

**How to reproduce it (as minimally and precisely as possible)**:

Attempt to restart a deployment using `kubectl rollout restart deployment deployment-name`

**Anything else we need to know?**:

Additionally it would be nice if `kubectl rollout restart FederatedDeployment deployment-name` could somehow work too. Or `kubefedctl rollout restart` (or similar)

**Environment**:
- Kubernetes version (use `kubectl version`) v1.1.17.3
- KubeFed version 0.1.0-rc6
- Scope of installation (namespaced or cluster) two clusters?
- Others

/kind bug

**Comment by jimmidyson** [comment]
I'm going to reopen this PR because it is a definite bug.

/reopen
/remove-lifecycle rotten

**Comment by chris-ng-scmp** [comment]
I'm going to reopen this PR because it is a definite bug.

/reopen
/remove-lifecycle rotten

**Comment by chris-ng-scmp** [comment]
We need this

**Comment by andrew-demb** [comment]
Please reopen this.
