### ISSUE TITLE
Helm install documentation misses --devel flag

### ISSUE THREAD

**Issue by Addono** [kubernetes-sigs/kubefed#1203]
**What happened**:
When following the [guide](https://github.com/kubernetes-sigs/kubefed/blob/master/charts/kubefed/README.md) on installing the Helm chart, some commands do not work straight away, as the latest release of `kubefed` is a development release, and as such needs the `--devel` flag to be used.

**What you expected to happen**:
The given Helm commands work out of the box, specifically the `helm search` and `helm install`

**How to reproduce it (as minimally and precisely as possible)**:
```bash
❯  helm search kubefed
NAME                        	CHART VERSION	APP VERSION	DESCRIPTION
kubefed-charts/federation-v2	0.0.10       	           	Kubernetes Federation V2 helm chart
```

```bash
❯ helm install kubefed-charts/kubefed --name kubefed --namespace kube-federation-system
Error: failed to download "kubefed-charts/kubefed" (hint: running `helm repo update` may help)
```

**Anything else we need to know?**:
Adding the `--devel` made it work again.

```bash
❯ helm search kubefed --devel
NAME                        	CHART VERSION	APP VERSION	DESCRIPTION
kubefed-charts/kubefed      	0.2.0-alpha.1	           	KubeFed helm chart
kubefed-charts/federation-v2	0.0.10       	           	Kubernetes Federation V2 helm chart
```

```bash
❯ helm2 install kubefed-charts/kubefed --name kubefed --namespace kube-federation-system --devel
NAME:   kubefed
LAST DEPLOYED: Thu Mar 12 14:21:16 2020
NAMESPACE: kube-federation-system
STATUS: DEPLOYED

RESOURCES:
...
```

**Environment**:
- Kubernetes version (use `kubectl version`)
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-13T18:08:14Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```
- KubeFed version
```
0.2.0-alpha.1
```

/kind bug

**Comment by jimmidyson** [comment]
I think we should remove the federation-v2 chart from the repo index and potentially release without the alpha|beta|rc suffixes - it should be enough to mark the project as alpha without having to include that in the release version.

In the meantime, I agree we should get the docs updated as in your PR.
