### ISSUE TITLE
Delete select federated resources upon unjoin

### ISSUE THREAD

**Issue by makkes** [kubernetes-sigs/kubefed#1205]
**What would you like to be added**:

I'd like to be able to configure certain federated resources in such a way that kubefed deletes them from the managed cluster when the cluster is unjoined.

**Why is this needed**:

It might be desirable in certain circumstances to leave a clean cluster behind after it is unjoined from the management cluster, clearing it of all the resources created when it was joined to the management cluster.

/kind feature

**Comment by makkes** [comment]
This is basically a duplicate of #583 which was closed. However, in my opinion it makes sense, to re-assess and discuss this proposal again.

**Comment by hectorj2f** [comment]
Perhaps it could be possible by adding a specific annotation similar to `kubefed.io/orphan` to achieve this goal.
