### ISSUE TITLE
Add support for deploying kubefed with Helm3

### ISSUE THREAD

**Issue by KadenLNelson** [kubernetes-sigs/kubefed#1234]
**What would you like to be added**:
I would like to be able to install kubefed with Helm3. Currently you can install kubefed with Helm3 if you apply the CRDs manually, but that is not optimal and you run into warnings like;

```
manifest_sorter.go:179: info: skipping unknown hook: "crd-install"
```

**What needs to be done?**:
[Helm gives us two options to deploy our CRDs;](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/)

1. we can add the CRDs into the `crds` folder of the Helm chart
2. or we could create a Helm chart specifically for the CRDs

The pros/cons of each option is outlined in the link above. This issue is not necessarily prompting immediate action. I'm opening this issue so that we can start a discussion about which option we would like to chose.

/kind feature

**Comment by RainbowMango** [comment]
Yes, It's time to update to Helm3.  Thanks.

I'll take it.
/assign

But, @KadenLNelson If you want to help with this, please feel free to send a PR and let me know.

**Comment by sagikazarmark** [comment]
@RainbowMango we've forked the chart to add CRD support: banzaicloud/banzai-charts#1121

Not sure if it's everything you would need, it worked for us, but feel free to use it for a PR. Don't really have the time to contribute it back in a PR, but it would be nice to drop the fork and use the official chart.

**Comment by eumel8** [comment]
@sagikazarmark 10 min to late when I started to struggle about the HelmV3 issue and landed in this issue ;)
I managed the issue in the same way and can confirm your solution. Thanks for sharing!

**Comment by hectorj2f** [comment]
@eumel8 @sagikazarmark  yeah, we would need to have a helmv3 compatible chart. Feel free to open any PR.

**Comment by eumel8** [comment]
@hectorj2f will test first if it's really working

**Comment by RainbowMango** [comment]
Great job and thanks for picking this up! @sagikazarmark @eumel8
