### ISSUE TITLE
kubefed controller manager crashes because of leadership lost

### ISSUE THREAD

**Issue by zryfish** [kubernetes-sigs/kubefed#1235]
**What happened**:
After upgrade to v0.3.0, kubefed-controller-manager crashes a lot because of leadership lost, leaderelection config is set to default. Sometimes I have to restart deployment to make it running normal for a while.  Is something I've missed?

```
root@master1:~# kubectl -n kube-federation-system get po
NAME                                         READY   STATUS             RESTARTS   AGE
kubefed-admission-webhook-d845d9459-2465w    1/1     Running            0          28d
kubefed-controller-manager-b5cc77585-5h92k   0/1     CrashLoopBackOff   3          12m
kubefed-controller-manager-b5cc77585-gmzwr   1/1     Running            3          12m
```

Last lines of logs before restart by k8s.
```
I0612 03:51:32.466821       1 leaderelection.go:288] failed to renew lease kube-federation-system/kubefed-controller-manager: failed to tryAcquireOrRenew context deadline exceeded
I0612 03:51:32.466865       1 leaderelection.go:82] leader election lost
E0612 03:51:32.466883       1 controller-manager.go:175] lost lease
I0612 03:51:32.470682       1 manager.go:179] No update necessary for ClusterPropagatedVersion "clusterrolebinding-fed-ben-platform-admin"
lost lease
```

My kubefedconfig
```yaml
apiVersion: core.kubefed.io/v1beta1
kind: KubeFedConfig
metadata:
  creationTimestamp: "2020-04-16T01:28:21Z"
  generation: 5
  name: kubefed
  namespace: kube-federation-system
  resourceVersion: "112739695"
  selfLink: /apis/core.kubefed.io/v1beta1/namespaces/kube-federation-system/kubefedconfigs/kubefed
  uid: 5e09c8b7-3cd9-4bb6-9c65-b50ed91f852c
spec:
  clusterHealthCheck:
    failureThreshold: 3
    period: 10s
    successThreshold: 1
    timeout: 3s
  controllerDuration:
    availableDelay: 20s
    unavailableDelay: 60s
  featureGates:
  - configuration: Enabled
    name: PushReconciler
  - configuration: Enabled
    name: SchedulerPreferences
  - configuration: Enabled
    name: CrossClusterServiceDiscovery
  - configuration: Enabled
    name: FederatedIngress
  leaderElect:
    leaseDuration: 15s
    renewDeadline: 10s
    resourceLock: configmaps
    retryPeriod: 5s
  scope: Cluster
  syncController:
    adoptResources: Enabled
```

```
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    control-plane.alpha.kubernetes.io/leader: '{"holderIdentity":"kubefed-controller-manager-b5cc77585-5h92k_7b85e514-7a6d-46ec-b7ff-e0205f30449f","leaseDurationSeconds":15,"acquireTime":"2020-06-12T03:53:23Z","renewTime":"2020-06-12T03:54:19Z","leaderTransitions":275}'
  creationTimestamp: "2020-04-16T01:29:24Z"
  name: kubefed-controller-manager
  namespace: kube-federation-system
  resourceVersion: "113184280"
  selfLink: /api/v1/namespaces/kube-federation-system/configmaps/kubefed-controller-manager
  uid: 83e53af3-85e2-41cc-bc0a-e84e40a2c402
```

**What you expected to happen**:
Running normally

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version **v1.17.3**
- KubeFed version **v0.3.0**
- Scope of installation **Cluster**
- Others

/kind bug

**Comment by RainbowMango** [comment]
Hi @zryfish Thanks for reporting this.

Can you provide the steps about how to reproduce it?

I've noticed that you're saying crashes, a backtrace would be useful.

**Comment by zryfish** [comment]
@RainbowMango  Not actually a crash, it seems kubefed controller keeps losing its leadership. 
```
I0612 03:51:32.466821       1 leaderelection.go:288] failed to renew lease kube-federation-system/kubefed-controller-manager: failed to tryAcquireOrRenew context deadline exceeded
I0612 03:51:32.466865       1 leaderelection.go:82] leader election lost
E0612 03:51:32.466883       1 controller-manager.go:175] lost lease
I0612 03:51:32.470682       1 manager.go:179] No update necessary for ClusterPropagatedVersion "clusterrolebinding-fed-ben-platform-admin"
lost lease

```

**Comment by zryfish** [comment]
Just found why kubefed controller keeps losing leadership. The default memory limits https://github.com/kubernetes-sigs/kubefed/blob/master/charts/kubefed/values.yaml#L15 is 128Mi, which is too low for my case.  
```
root@master1:~# kubectl -n kube-federation-system top po
NAME                                          CPU(cores)   MEMORY(bytes)
kubefed-admission-webhook-d845d9459-2465w     4m           20Mi
kubefed-controller-manager-575868c865-4h84t   1m           8Mi
kubefed-controller-manager-575868c865-qcqr9   197m         138Mi
```

It's not easy to find the oom from logs. I think we could increase the resources limits in chart to avoid this.

**Comment by RainbowMango** [comment]
Yeah, that's a good finding.  How about enlarging the limit memory to 256Mi? Can you help verify if this works for you?

> But it's not easy to find the OOM cause from logs.

By the way, maybe you can get the logs from `dmesg`, e.g.
```
# dmesg
...
Memory cgroup out of memory ...
...
```

**Comment by zryfish** [comment]
After increase the limits, kubefed works just fine. I think 256Mi is ok for most cases, in my environment, I've enabled 20+ type of resources which consumed more memory than usual.  It's better to tell the users to increase the resource limit if they enable more and more resources. 

Below is the resource usage of kubefed controller in my cluster
![截屏2020-06-15 10 14 27](https://user-images.githubusercontent.com/3326354/84611814-79adb500-aef1-11ea-97c2-847b46ffc0f4.png)

**Comment by RainbowMango** [comment]
Thanks for your quick feedback. I'd prefer 512Mi which will cover more cases. How do you think?

**Comment by zryfish** [comment]
Agree, I suggest we also increase cpu limits to 400m for better performance since 100m is too low. I'd like to create a PR to address above issues, Is that ok?

**Comment by RainbowMango** [comment]
Yeah, go for it!

I agree to enlarge CPU to 400m and memory to 512Mi.
