### ISSUE TITLE
Add FederatedChart feature.

### ISSUE THREAD

**Issue by lmxia** [kubernetes-sigs/kubefed#1242]
**What would you like to be added**:
FederatedChart
**Why is this needed**:
Then we can federate helm chart resource to member clusters implements the Helm v3 Controller based on Helm v3 Proposal.

/kind feature

**Comment by dgorst** [comment]
https://github.com/fluxcd/helm-operator pairs pretty nicely with kubefed - we've had some joy federating the HelmRelease CRD and using those to distribute out helm packages to clusters. Worth taking a look to see if that meets your use cases!

**Comment by lmxia** [comment]
pretty cool, i will take a look and see, thanks.

**Comment by hectorj2f** [comment]
Yeah, it sounds like a good approach too. I like the idea too.
