### ISSUE TITLE
v0.3.0 assets binaries version is not align with the release

### ISSUE THREAD

**Issue by RainbowMango** [kubernetes-sigs/kubefed#1243]
**What happened**:
```
[root@ecs-d8b6 release]# tar -zxvf kubefedctl-0.3.0-linux-amd64.tgz 
[root@ecs-d8b6 release]# ./kubefedctl version
kubefedctl version: version.Info{Version:"v0.2.0-alpha.1-35-gd7b7b3c9-dirty", GitCommit:"d7b7b3c94f20c76c7405e393668ca26c59f94b43", GitTreeState:"dirty", BuildDate:"2020-05-01T21:21:13Z", GoVersion:"go1.13.7", Compiler:"gc", Platform:"linux/amd64"}
```
**What you expected to happen**:
The version tag should be `v0.3.0` not a `v0.2.0-alpha.1-35-gd7b7b3c9-dirty`.
https://github.com/kubernetes-sigs/kubefed/releases/download/v0.3.0/kubefedctl-0.3.0-linux-amd64.tgz

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`)
- KubeFed version
- Scope of installation (namespaced or cluster)
- Others

/kind bug

**Comment by hectorj2f** [comment]
Yes, we need to fix this, perhaps there is a step missing in the release process

**Comment by RainbowMango** [comment]
I guess you make these binaries before setting a tag.

**Comment by hectorj2f** [comment]
This has been fixed on recent releases.
