### ISSUE TITLE
request a ReplicaFree Option for cluster autoscale

### ISSUE THREAD

**Issue by pacoxu** [kubernetes-sigs/kubefed#1255]
**What would you like to be added**:

I want the hpa strategy to effect the replica of deployment in current cluster.

Something like "ReplicaFree" option. If this option is opened,  we can deploy deployments without fixed replica in each cluster. The hpa will decide the replica of pods according to the application/pod load.

**Why is this needed**:
For application autoscale, federated knative service can provide autoscale function.
However, if we want to use simple hpa and deployment, deployment replica is static in kube fed.

/kind feature

**Comment by GitHubxsy** [comment]
![image](https://user-images.githubusercontent.com/11901080/89192128-80de6e80-d5d6-11ea-8a5a-9eb9e9fe4588.png)
@pacoxu

**Comment by pacoxu** [comment]
close per https://github.com/kubernetes-sigs/kubefed/blob/5f2292c8ebaecfee1968329dc449c0b37be57a10/docs/userguide.md#scalable 

thanks @GitHubxsy
