### ISSUE TITLE
Error: Unauthorized slave

### ISSUE THREAD

**Issue by rushins** [kubernetes-sigs/kubefed#1257]
hi 

while running kubefedctl join i get the error unauthoried of the slave (second cluster ) 

kubefedctl join slave --v=2 --host-cluster-context master --kubefed-namespace=kube-federation-system
----
error
---
I0727 16:42:07.535733   38817 join.go:148] Defaulting cluster context to joining cluster name slave
I0727 16:42:07.535797   38817 join.go:160] Args and flags: name slave, host: master, host-system-namespace: kube-federation-system, kubeconfig: , cluster-context: slave, secret-name: , dry-run: false
I0727 16:42:07.567766   38817 join.go:242] Performing preflight checks.
F0727 16:42:07.584377   38817 join.go:127] Error: Unauthorized
----

**Comment by hectorj2f** [comment]
Based on the logs, you seem to have authorization problems with the `slave` cluster. You seem to miss the `--cluster-context` for the `slave` cluster or the KUBECONFIG in your environment is not configured to talk to `slave`.

**Comment by rushins** [comment]
@hectorj2f : No, i do have the context of slave in my kubeconfig file along with master cluster as master..
.can you check below kubeconfig file and suggest what was missing or needs for kubefedctl join 
---------
[root@node1 ~]# more ~/.kube/config
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWU
VFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJd01EUXlOREF6TWpBek5Wb1hEVE13TURReU1qQXpNakF6TlZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS2
9aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTVR4Clo1THc0Y3NmeTdKS1ZZUkZnUWdHOFVvT05zQW0rZUNWbUFveGpDaUI3VXhmSFVuOFdwSTErTU9kRFc5ODJvVlYKVWZURnl
2ZjZNNjU2Mmg1cVR6MWRpUERPczR2RlZETzkxeEd3cENIMmlLZzJWZlhucnZhODFjdzBLd0xYd2RBUwpFdWNRMmlLdHFNUVhRa0pQZXNrNUFFS05XMFBjQVk4SzFlUk1HQnd6WmRFNzUy
M09HTXRMSU5Da1hXVGlDTkRHCnNBcDZIbzVsNElteVVYc1V0cTNzZ0pmbzFHVmplVW9SY05nVDkzZE83L2FLVzFDMHJVdGl1dzM4N2hOWklyckQKZG5maGRNQ0NmN29WK3ovNlJwdGtNN
XRrUGhWcDBQSjN0UkltYXR0OFhHOENYZVN4R3M4U0Y4WWNFRjNnU3hXSQoyYzRRcmU5UlNidnBkcmp6ZDdFQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0
VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFHUG1hUkFaTWNuR2RCMWtGS2hYcy9ONUN2aXIKaFNwYVM4RGpZWTNjd3ViQ2RBclRrc2JCZVo1RmFrSEdJTzk0NzJ
tVXVGSDYxUlBCdkVCczJORmJBcWhjK3JvSQo1N3ZUbWN3ZzNPdCt2VVhZeFJ2cExzWC9Sa0poTjVIaFVlenBkVXFCOHBtd0RpbHhUQVhZWlp1bXAvWUFYVFBzClJjZ1JFRXhDelBwYkxS
WFlFZ1EzTUp5NldsdzlMYUJxSHdOWDBMenBwZlJOTTM0dTViL2tNMjg4TzQ3TytTVFYKcHZvTHhmUExVeHNBNlhLL2ozcXgrc3hRQlNTTmVQQXVWa3FCbit2YUlTeUtxQkF1bjBLRG1QV
jhqOVV2T3ZEdgpDdUZDSUtwbExuU0FMZVczeU13aWhDMEFiVFREL2RhU29mUHQyS2lwY0VxUVVoN2xvdkVQT1Q2Y3Rodz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://10.48.185.33:6443
  name: cluster.local
- cluster:
    server: https://lvpaldbsvm11:6443/
    certificate-authority: /root/federation/slave-lvpaldbsvm11-13-rancher/ca.crt
  name: kubefedRemote
contexts:
- context:
    cluster: cluster.local
    user: kubernetes-admin
  name: master
- context:
    cluster: kubefedRemote
    namespace: default
    user: kubefed-user
  name: slave
current-context: master
kind: Config
preferences: {}
users:
- name: kubefed-user
  user:
    token: /root/federation/slave-lvpaldbsvm11-13-rancher/token.txt
- name: kubernetes-admin
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM4akNDQWRxZ0F3SUJBZ0lJRjNyd3RDcEpyYXd3RFFZSktvWklodmNOQVFFTEJRQXdGVEVU
TUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TURBME1qUXdNekl3TXpWYUZ3MHlNVEEwTWpRd05UVTNORGhhTURReApGekFWQmdOVkJBb1REbk41YzNSbGJUcHRZWE4wWlhKe
k1Sa3dGd1lEVlFRREV4QnJkV0psY201bGRHVnpMV0ZrCmJXbHVNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXNKU1FPYXd6anYxWVI0S1oKVFRjZnpTRz
lLd2l3RmZFUXEzbW9pRCs5YjRMRU9XMGs2L2lFTHlacGJMRjVFbUxhWEh2SU0wNmlKQnNIbk5YMQpMcmljRjZZNHhKNnhBdXFDQTFCRklGdVFZbnFuU2VNNGhRT0tqVlRGSW40eHRDV04
zcDZPdnAzVTE3VVI3Kzd0CjlIM0NuRDlCc3FPQUFEM1pzZFpEMDUxNFE3WkY2NXdXRjFqSWkyN3FDRmVXSGxxM0IwUmpRaTRLK0YyRjd1M0sKMjRsakYxR2Qva1B0WGd0MVNMc2NBS2FE
UlQ1S2RKTDQ4ZVFzV0ZVeVYxdjBhOUx6eUhpREM4N3JpR3FSUFprQQpOZmN0S2tRSkNIMzhhaXF1L09wYTRjTHFrOFIrNEJLQXpnd05SVnpQVkhDeFR6dE56dVU3NzlvdUhkK3lPL2xMC
kxOYXN2d0lEQVFBQm95Y3dKVEFPQmdOVkhROEJBZjhFQkFNQ0JhQXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUgKQXdJd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFCRTR3ek9pbjB6VX
pDNlpFaDAvVnlKZC9kSEVjYTFaaDd2aQoxSHFaUW9mbGpqaG0wYnBrUy9KdDRjV29CRWFQb0ppQUtIM1dub08xbEljR01yenlWSXFWU1hrUkkrc0dZSXcrCitiUHd6R25YRUVFNWR6T0E
wdEJFaXFQZURPelJHeXdTemhZRHd0U24xeTk0S0VJV2YyRFV4SWNuaFJrZmFTakIKRG9vSStBdEZ0b1pjVmdPc1FYWXJrNG8vNzdaNzBEWHM2bmhycUgrL1NnaDVieFgyRzlONnZJc0w5
YmVuc2hmbgptOVZHeHJrVHB1dzJOOEFWUGcrdG5oc2FoamlEMm5SZXpHc1FYQXdrVHJsN0Irb2NaU2lRVkQ0N09TTTUwQVJwCjZvYVhpTmJaRUdrR3VwdDRRR3Z2VkJEeFdMUzVqVEFlL
05LcXdPb29sQjB2eGw2d1NVND0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBc0pTUU9hd3pqdjFZUjRLWlRUY2Z6U0c5S3dpd0ZmRVFxM21vaUQrOWI0
TEVPVzBrCjYvaUVMeVpwYkxGNUVtTGFYSHZJTTA2aUpCc0huTlgxTHJpY0Y2WTR4SjZ4QXVxQ0ExQkZJRnVRWW5xblNlTTQKaFFPS2pWVEZJbjR4dENXTjNwNk92cDNVMTdVUjcrN3Q5S
DNDbkQ5QnNxT0FBRDNac2RaRDA1MTRRN1pGNjV3VwpGMWpJaTI3cUNGZVdIbHEzQjBSalFpNEsrRjJGN3UzSzI0bGpGMUdkL2tQdFhndDFTTHNjQUthRFJUNUtkSkw0CjhlUXNXRlV5Vj
F2MGE5THp5SGlEQzg3cmlHcVJQWmtBTmZjdEtrUUpDSDM4YWlxdS9PcGE0Y0xxazhSKzRCS0EKemd3TlJWelBWSEN4VHp0Tnp1VTc3OW91SGQreU8vbExMTmFzdndJREFRQUJBb0lCQUJ
0U0lTNkxNajhCZTlNMApwYnVJdCticFBYZVhGSWVRa04rM0p4aE5wR1hJZWN2WTAwbWZYZlJkb1Jvc0sydG8yQmhQSHA2eG4reXVNZk5XCk4yVlBNdmVGeEdySGt1TzhuUGtlUmxQSFZ3
T2xycFNFRDQ2bENaN3Nhc1AzZW9GQS9qNWZrZjUwTlNaYTRiZVoKNUQ5YjVleCs3UTlTdE05VXdvWDlmT2tWQ0RLUmt5ejJycXpMMHRTa1FsaHEwbjhZV29ycE5CM0xMek9VdXFaegovb
GRWZzd1WEtzcUN4UHRXOVNYVHJlaXUrQXZPV1A5RjhZd3NLOEZ4ZE02SkoxbklqWk1icWZCMmUzK2dsK0ZFCmRIS0ZKZ2ZzcEJCMWRHcHF3TFlMTUJYdEpvVHZxenJGZXdZMmRsRXdPUX
FiNHhKR3hIMWgrdE1XL2Y0QndPRUMKNFl5R2V1RUNnWUVBNVVjemJFTEJNOE4xdmxoM1BYVU0rQ3l6djE2UmNtdXRNMmN4YldMWnFqZ3RLVkRSWGs4Zgp5VHZoc1cvZjNnckl1bnloSFo
4NEFrc0hqNkpiMkh4Rk1RclhLNW5lMFlkS1NhbFowZThSMmJLS2s1RzRkSXY3ClgxUGcxMld5K3JJdkJhZm9Rck5DU0VvUUxtVzZjMkF6dDNBcjFHTkdwcHBzQ1I2N2lSVjNGeVVDZ1lF
QXhTa08KeTNqVlpPYmw2R25ETUZISEZ1NnE2OUVNUXZISEZzUmNuRE5wM1A4dXpCYldjbTBLajhFV3VMZzlTU2p0blZ2WQp5cHRXMVM3TTBrV1FLellsUVphRWJ0N2tMNm5GVGJFNHJLT
DBkY2FnMFlrYzNKazdjNWRkL0R4bzVRWGlPQVdOCmtWTXpzTXNRbGlnTWNSUS9RdzE0RDZvRXRTSlBPNU5NMTJvVWtSTUNnWUE1T1dVZlB5WURhbVJueHFLMEp4TysKbVVHZm9OWENiaG
VEZmR6N1JURzRaMTcyTWVLZm5EWDl2c0Zjek9SZUFla0ppbk9YOWhZL2xFUmwyQXIrWkQzTQp1THp0ZC9FQjhMZGMzVFM2emVWeHBUc3JDN0t5L0FFWVVOSU1VS2kwSTJiVERZNU5uM29
LbXRtaEN1alhSUXFEClhTN0RTcWZtaXlJdHdJcmo4d1NQTlFLQmdRQ3BWcjluVWN4dkVzYUxIVFBScjV1QS9kTCtJaG9XOFpUZTRCN3UKNWxYWnc2K05DVng5QVZ6ZDVhay9WTGNHdkVt
Q0sxNERmdkpRdmhhYno3V285Nk4rTnVwZVU4REhrMWhzaDNlMwpCMnRTTVJ6MWUzKzNsVUR6NGlHT1FOQ1RUTDlsQUpmOEp1c3h3T2ZwSUZLM1dQMlErT09UQ0tOc2RDQjdlZU80CjdWc
m0wd0tCZ1FDOTYyQWVoWGJHem02N2JYVWdEOWVpWWRnK3FtdE5GcnNqcnhkSE8rNkdPbjBtSHI3cjI3b0gKRTZlbFhCK0FmRW5jSThLS2xNM25YK0FEN1M4UlhQVjBFVlFLWnVEUGp6eV
FrSVRpSlBJTUxoV2F0UGNRbW1NYgptMmowZ3BzbnFqT2pUNExxNmgwWnhEZnAzN1BKQ2t3RGYyeEhUOHg2dVRVdlE0c05JYW8weEE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0
tLQo=
---------

**Comment by rushins** [comment]
it seems a bug in the kubefedctl with kubectl ..i have updated both with latest version  and the error is gone.

**Comment by hectorj2f** [comment]
Glad to know the error is fixed with the latest version.
