### ISSUE TITLE
Should not delete namespace when unjoin cluster

### ISSUE THREAD

**Issue by davidwtf** [kubernetes-sigs/kubefed#1258]
**What would you like to be added**:

`UnjoinCluster` in `pkg/kubefedctl` should not delete the kubefed namespace. 

**Why is this needed**:

Because maybe there are other resources in this namespace, which can not and should not be deleted.
This will leave a `Terminating` namespace, and will cause a failure when joining this cluster again.
Because it's not allowed to create any resource (include the RBAC resources) in a `Terminating` namespace. 

We cann't stop user to use the kubefed namespace to store other resources. So it' better to keep the namespace left, like what we do on the `Primary` cluster.

/kind feature

**Comment by hectorj2f** [comment]
@davidwtf I don't think it is a good and recommended practice to use the kubefed namespace to federated resources. I'd recommend to use a different namespace that you can after federate to the clusters. If you don't want to get the resource deleted when unjoining you could also make usage of an annotation `kubefed.io/orphan: true`. This annotation ensures retention of the resource (e.g.. namespace) when unjoining.

**Comment by davidwtf** [comment]
@hectorj2f Thanks for your suggestion. 
But I think the main point is not which namespace to save the federated resources, but is that we can not stop the user to save something in the kubefed namespace.
The user may save just normal resources. And maybe there are other operators will create their CR in the kubefed namespace.
If we delete the namespace, we will delete the resources that not create by us. And we don't know what will happen, the deleting may be blocked.

**Comment by davidwtf** [comment]
To be clear,  the namespace which I mentioned, is the not the user defined federated namespace, but the namespace used by `kubefed`'s control plane .
