### ISSUE TITLE
federation storage class, federation PVClaim

### ISSUE THREAD

**Issue by rushins** [kubernetes-sigs/kubefed#1268]
HI 

I am using kubernetes federation (federated control plane ) on 2 clusters with NetApp trident as a storage class on-prem using NetApp CDOT storage, both clusters (Federation master and Federation slave) are working and i can run deployments, services , however. was not able to do storage class, storage persistence volume and persistence volume claims. 

So, would like to get idea of  Federated storage class and federaeted. persistence volume to make sure the replication of master volume get replicated to slave federation . 

Here is the link below link reference to netApp Trident but no detailed way how this wors.
kubernetes-sigs/kubefed#1165

Any help is appreciated.

BR

**Comment by hectorj2f** [comment]
@rushins I federated storage classes without problem across kubefed clusters. But I didn't try to federated persistent volumes claims although I don't see why it won't work. Can you describe what problem are you facing with more details?
