### ISSUE TITLE
kubefedclusters 

### ISSUE THREAD

**Issue by htlabc** [kubernetes-sigs/kubefed#1271]
environment
 kubectl version:v1.16.3 (K8s cluster created by kubeadm)
kubefed version:v0.3.1
tow clusters:
CURRENT   NAME           CLUSTER    AUTHINFO           NAMESPACE
*         cluster1       cluster1   kubernetes-admin   
          cluster2-htl   htl        htl   

htl clusters can be accessed by executing the command kubectl config use-context cluster2-htl on the server of cluster1.
and then i joining the clusters htl into host-cluster,
[root@k8s-cluster1 ~]# kubefedctl join htl --cluster-context cluster2-htl --host-cluster-context cluster1 --v=3 --kubeconfig=/root/.kube/config
I0811 16:03:12.272096   15256 join.go:160] Args and flags: name htl, host: cluster1, host-system-namespace: kube-federation-system, kubeconfig: /root/.kube/config, cluster-context: cluster2-htl, secret-name: , dry-run: false
I0811 16:03:12.528042   15256 join.go:242] Performing preflight checks.
I0811 16:03:12.579297   15256 join.go:248] Creating kube-federation-system namespace in joining cluster
I0811 16:03:12.620729   15256 join.go:256] Created kube-federation-system namespace in joining cluster
I0811 16:03:12.620798   15256 join.go:412] Creating service account in joining cluster: htl
I0811 16:03:12.631636   15256 join.go:422] Created service account: htl-cluster1 in joining cluster: htl
I0811 16:03:12.631661   15256 join.go:450] Creating cluster role and binding for service account: htl-cluster1 in joining cluster: htl
I0811 16:03:12.712109   15256 join.go:459] Created cluster role and binding for service account: htl-cluster1 in joining cluster: htl
I0811 16:03:12.712243   15256 join.go:820] Creating cluster credentials secret in host cluster
I0811 16:03:12.729940   15256 join.go:848] Using secret named: htl-cluster1-token-8pddw
I0811 16:03:12.742687   15256 join.go:893] Created secret in host cluster named: htl-b9lj5
I0811 16:03:12.766341   15256 join.go:284] Created federated cluster resource

nothing error!!!!!
but one of the clusters is not ok :
[root@k8s-cluster1 ~]kubectl -n kube-federation-system get kubefedclusters 
NAME       AGE     READY
cluster1   6h12m   True
htl        107m 

[root@k8s-cluster1 ~]# kubectl -n kube-federation-system describe kubefedclusters htl
Name:         htl
Namespace:    kube-federation-system
Labels:       <none>
Annotations:  <none>
API Version:  core.kubefed.io/v1beta1
Kind:         KubeFedCluster
Metadata:
  Creation Timestamp:  2020-08-11T08:03:12Z
  Generation:          1
  Resource Version:    311716
  Self Link:           /apis/core.kubefed.io/v1beta1/namespaces/kube-federation-system/kubefedclusters/htl
  UID:                 fdd35bc9-2638-4809-aab5-f443312392cc
Spec:
  API Endpoint:  https://192.168.30.142:6443
  Ca Bundle:     LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJd01EZ3dOekE0TkRJME5Gb1hEVE13TURnd05UQTROREkwTkZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTzNTCnJrZ1p0R2dhS0xidGo5bFJhRjMrazRnU1dsUTA1d2poWmhZSnRhU2JXcDE1VjBDSm56eEozbGplbUJxWldwTFMKVE9aSjdaQU9SVDZNTm11dTFLcVVIY2xhSXUyUEhqRmpIUGduTWZoWmZmTnFXSkVTbjhHQmRTTVgwU09ZOFNsUApqL2lhNDNKc3F5ZHRmRzhZdlYyTkx4WkZpRmdMT0x6VWlBSGRyYitnT1BIeGJhUFVmNXdsZ21HL1VyelVmbTUwCmUySVRaR3AyRlJwOVFKWUhoc1RLQyt2d2N1Q2ZCR0Qra281eWpubjc2VldDd0xsakUvcnZwQUg1WlZNb2NDMloKUUlNTU5QUW9IRUhYTWl1T0toNjQ4cnB6eEN6MTM0d1l6bWtJTzZzYjZuTkN0ejhrbWtnekFEdktFNzJ0RjUwdwpqeXk5dEZKZW0yUERoeEN0UmVNQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFGMmlrZlpRMFZ5YlJJZU81WERyL2pvWmlmelQKcWVNMjZSWFk1MnJpYTY5WTRCdVhFV01LL0tSdlV4TFdET3dQOGlYQ1ZITTUyUDEzSWljMGRWaGFVYmpCSmxiQQo1SlNlOHBuaEY3RlJuYndPZGRYZnNHbTdlaEpnZHBJVGVSRTBLZ1I2NXI3YktaWE83dUVuRU51aFJPV1RLeTh5CjFFWFF1WWpRRGRhQ2Q2MWNIUGR5WWVnRUlaN2dZZ3JPYWFLbWcwQ1l4RDY1WTVKOXY1dlZocW5WWjRjalVpNi8KNFRHem1VemJXemxxQkJ4TFBCVit4S1NiTktUQi85Njl0SDkzQ3E4WjZYd1hrUmJMYTk4NTZRY08wU2ducmladQpiUnNzbmZreVM5QjNEUHRzT0dDSkhud2xMcVNmV09rTnVDSnRIVGJ2VkMrY210ZnN1c2NjNGMxQ0gyRT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  Secret Ref:
    Name:  htl-b9lj5
Status:
  Conditions:
    Last Probe Time:       2020-08-11T10:04:40Z
    Last Transition Time:  2020-08-11T08:03:14Z
    Message:               cluster is not reachable
    Reason:                ClusterNotReachable
    Status:                True
    Type:                  Offline
Events:
  Type     Reason                         Age                   From                       Message
  ----     ------                         ----                  ----                       -------
  Warning  RetrievingClusterHealthFailed  11m (x9 over 103m)    kubefedcluster-controller  Failed to retrieve health of the cluster: Get "https://192.168.30.142:6443/healthz?timeout=3s": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  Warning  RetrievingClusterHealthFailed  83s (x527 over 121m)  kubefedcluster-controller  Failed to retrieve health of the cluster: Get "https://192.168.30.142:6443/healthz?timeout=3s": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

 always occurs  error Failed to retrieve health of the cluster: Get "https://192.168.30.142:6443/healthz?timeout=3s": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

and then I try to visit the https address of aipserver。
 curl https://192.168.30.142:6443/healthz --insecure
ok[root@k8s-cluster1 ~]# 

What caused this error and how to troubleshoot！please help me!

**Comment by makkes** [comment]
It looks like kubefed cannot reach your cluster from it's controller so you might have a connectivity issue from *inside* cluster1. Would you mind trying this out and pasting the result here?

```
k run debug --image=digitalocean/doks-debug --restart=Never -it -- curl https://192.168.30.142:6443/healthz
```

**Comment by htlabc** [comment]
ok!!i will try it .thanks your adviser

**Comment by htlabc** [comment]
> It looks like kubefed cannot reach your cluster from it's controller so you might have a connectivity issue from _inside_ cluster1. Would you mind trying this out and pasting the result here?

I follow your method to try command in the cluster1,but the ttl is no response
curl: (7) Failed to connect to 10.57.4.21 port 6443: Connection timed out
