### ISSUE TITLE
multi-cluster join failed

### ISSUE THREAD

**Issue by nzncngz** [kubernetes-sigs/kubefed#1276]
**What happened**:

I am install two k8s cluster on same region(aws).I want to manage 2 clusters with multi-cloud.But it failed
CONFIG

Cluster1:   k8s-cluster-kubefed
Cluster2:   demo2

Cluster1 is host cluster and kubefedctl installed.

export KUBECONFIG=$PWD/k8s-cluster-kubefed-kubeconfig

kubectl config get-contexts
CURRENT   NAME                                                          CLUSTER                     AUTHINFO           NAMESPACE
*                 kubernetes-admin@k8s-cluster-kubefed   k8s-cluster-kubefed   kubernetes-admin

****************************************************************************************************

export KUBECONFIG=/home/ubuntu/kubeone_1.0.0_Linux_amd64/examples/terraform/aws/demo2-kubeconfig

kubectl config get-contexts                                
CURRENT     NAME                                            CLUSTER                 AUTHINFO           NAMESPACE
*                   kubernetes-admin@demo2          demo2                    kubernetes-admin

*****************************************************************************************************
touch $PWD/k8s-multi-kubeconfig
export KUBECONFIG=$PWD/k8s-multi-kubeconfig:$PWD/k8s-cluster-kubefed-kubeconfig:/home/ubuntu/kubeone_1.0.0_Linux_amd64/examples/terraform/aws/demo2-kubeconfig

kubectl config get-contexts
CURRENT   NAME                                                         CLUSTER                      AUTHINFO            NAMESPACE
                   kubernetes-admin@demo2                       demo2                        kubernetes-admin
*                 kubernetes-admin@k8s-cluster-kubefed   k8s-cluster-kubefed   kubernetes-admin

**Environment**:
kubefedctl join demo2 --cluster-context kubernetes-admin@demo2  --host-cluster-context kubernetes-admin@k8s-cluster-kubefed --v=2

FAILED

16919 join.go:160] Args and flags: name demo2, host: kubernetes-admin@k8s-cluster-kubefed, host-system-namespace: kube-federation-system, kubeconfig: , cluster-context: kubernetes-admin@demo2, secret-name: , dry-run: false
F0823 20:17:02.308211   16919 join.go:127] Error: Failed to get kubefed clientset: Unauthorized

- Kubernetes version (use `kubectl version`)
1.18.0(kubeone)
- KubeFed version

kubefedctl version: version.Info{Version:"v0.3.1-113-g6eeeac232", GitCommit:"6eeeac232dcd7556054d2c2042069684f11a08cc", GitTreeState:"clean", BuildDate:"2020-08-17T16:13:02Z", GoVersion:"go1.14.7", Compiler:"gc", Platform:"linux/amd64"}
- Scope of installation (namespaced or cluster)

- Kubectl version

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

**Comment by htlabc** [comment]
your cluster name kubernetes-admin@k8s-cluster-kubefed is not allow

**Comment by makkes** [comment]
@nzncngz were you able to verify that it works with a different cluster name?
