### ISSUE TITLE
release build for windows

### ISSUE THREAD

**Issue by tuananh** [kubernetes-sigs/kubefed#1277]
I'm not sure what's the reason for not having windows build. i searched through the issues and found nothing.

I want to to test kubefed by creating clusters with `kind` and join them with kubefedctl but kubefedctl is not available for windows.

**Comment by asears** [comment]
#1101 related.  Release on Chocolatey or other Windows package manager could be helpful too.

https://chocolatey.org/docs/create-packages

```shell
git clone --depth 1 https://github.com/kubernetes-sigs/kubefed.git
cd kubefed\cmd\kubefedctl
go build -o kubefedctl.exe main.go
```
