### ISSUE TITLE
retainReplicas failed

### ISSUE THREAD

**Issue by lmmmml** [kubernetes-sigs/kubefed#1278]
**What happened**: 
When retainReplicas is set to true, the replicas of the member cluster deployment is still overrided by federatred sync controller.

**What you expected to happen**: 
When retainReplicas is set to true,  the replicas of the member cluster deployment cannot be change by modify the rsp.

**How to reproduce it (as minimally and precisely as possible)**: 
set the retainReplicas to true, and then change the totalReplicas of rsp.

**Anything else we need to know?**:
the order of these two functions mybe wrong, the  RetainClusterFields should be affer ApplyOverrides.
https://github.com/kubernetes-sigs/kubefed/blob/57a1852ce9db67cdca440687998c026bf878f142/pkg/controller/sync/dispatch/managed.go#L203
https://github.com/kubernetes-sigs/kubefed/blob/57a1852ce9db67cdca440687998c026bf878f142/pkg/controller/sync/dispatch/managed.go#L209

**Environment**:
- Kubernetes version (use `kubectl version`)
- KubeFed version
- Scope of installation (namespaced or cluster)
- Others

/kind bug

**Comment by makkes** [comment]
@lmmmml thanks for filing this issue.  I was trying to reproduce your issue but wasn't available to so let's try to get on the same page:

I created a `FederatedDeployment` with `replicas: 2`. This causes a `Deployment` with `replicas: 2` to be created on the attached cluster, leading to two pods. Then scaling down the `Deployment` to 1 replica on the attached cluster will lead to only one pod and kubefed rapidly changing the `Deployment` again to 2 replicas.

Now adding the field `retainReplicas: true` to the `FederatedDeployment's` `spec` and then scaling down the `Deployment` on the attached cluster to 1 replica leads to 1 pod left and kubefed will not change that.

This is how it worked for me so I'd love to hear what went wrong on your side.

**Comment by makkes** [comment]
Interestingly enough I was able to reproduce an error when setting `retainReplicas: false` again which should lead to the `Deployment` scaled up again but that didn't happen in my scenario. I'll look into this.

**Comment by lmmmml** [comment]
> @lmmmml thanks for filing this issue. I was trying to reproduce your issue but wasn't available to so let's try to get on the same page:
> 
> I created a `FederatedDeployment` with `replicas: 2`. This causes a `Deployment` with `replicas: 2` to be created on the attached cluster, leading to two pods. Then scaling down the `Deployment` to 1 replica on the attached cluster will lead to only one pod and kubefed rapidly changing the `Deployment` again to 2 replicas.
> 
> Now adding the field `retainReplicas: true` to the `FederatedDeployment's` `spec` and then scaling down the `Deployment` on the attached cluster to 1 replica leads to 1 pod left and kubefed will not change that.
> 
> This is how it worked for me so I'd love to hear what went wrong on your side.

You can try to change the total copy of rsp after adding `retainReplicas: true`, and `Deployment` on the attached cluster may change accordingly.

**Comment by makkes** [comment]
> You can try to change the `totalReplicas` of rsp or the `overrides.replicas` of `FederatedDeployment` after adding `retainReplicas: true`, and `Deployment` on the attached cluster may change accordingly.

I'm not sure I totally understand the reason to set `overrides.replicas` instead of just setting `spec.template.spec.replicas` directly. Would you mind enlightening me here? And does setting `spec.template.spec.replicas` work fine together with `spec.retainReplicas` for you as it does for me?

I haven't tested RSPs in this regard, yet.
