### ISSUE TITLE
service dns controller ignores err while reconciling

### ISSUE THREAD

**Issue by yuswift** [kubernetes-sigs/kubefed#1285]
**What happened**:
```pkg/controller/servicedns/controller.go```
```
	if err != nil {
		runtime.HandleError(errors.Wrap(err, "Failed to get ready cluster list"))
		return util.StatusError
	}

	fedDNSStatus := make([]dnsv1a1.ClusterDNS, 0, len(clusters))
	// Iterate through all ready clusters and aggregate the service status for the key
	for _, cluster := range clusters {
		if cluster.Status.Region == nil || *cluster.Status.Region == "" || len(cluster.Status.Zones) == 0 {
			runtime.HandleError(errors.Wrapf(err, "Cluster %q does not have Region or Zones Attributes", cluster.Name))
			return util.StatusError
		}
		clusterDNS := dnsv1a1.ClusterDNS{
			Cluster: cluster.Name,
			Region:  *cluster.Status.Region,
			Zones:   cluster.Status.Zones,
		}
```
Because err is nil, so runtime.HandleError function will not handle the err.
**What you expected to happen**:
It should print the err.
**How to reproduce it (as minimally and precisely as possible)**:
If one of the cluster does not have region or zone, the err happens and will be ignored.
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`)
v1.17.9
- KubeFed version
v0.4.0
- Scope of installation (namespaced or cluster)
- Others

/kind bug

**Comment by yuswift** [comment]
Should I open a pr to fix the bug?
I think just use errors.Errorf() instead of errors.Wrapf() with an empty err can fix it

**Comment by hectorj2f** [comment]
@yuswift Can you explain what you see or share the error you get in the logs ?

**Comment by yuswift** [comment]
> @yuswift Can you explain what you see or share the error you get in the logs?
I think we should see logs like " "Cluster1 does not have Region or Zones Attributes"" if nodes of cluster1 do not have failure-domain.beta.kubernetes.io/region or failure-domain.beta.kubernetes.io/zone label.
But I did not see any logs like that, because errors.Wrapf() returned a nil err with the given nil err.
And runtime.HandleError() will not handle the nil err returned by errors.Wrapf(). So this is why I didn't see any logs like that.
 Hope I've made my point. Thanks for your reply.

**Comment by RainbowMango** [comment]
@hectorj2f I guess it's a mistake and the log will be ignored by `errors.Errorf()`. Because will not wrap a nil error.

> Should I open a pr to fix the bug?
I think just use errors.Errorf() instead of errors.Wrapf() with an empty err can fix it.

Sure thing! If @hectorj2f no other comments.

I'd prefer just use `klog.Errorf` to replace `runtime.HandleError` as follows:
```diff
- runtime.HandleError(errors.Wrapf(err, "Cluster %q does not have Region or Zones Attributes", cluster.Name))
+ klog.Errorf("Cluster %q does not have Region or Zones Attributes", cluster.Name)
```

**Comment by hectorj2f** [comment]
Yes, it looks like a good option to me ;). Thanks @RainbowMango
