### ISSUE TITLE
Target cluster joins federation fine but after a "while", kubefed-controller-manager shows ClusterNotReachable

### ISSUE THREAD

**Issue by kiich** [kubernetes-sigs/kubefed#1287]
**What happened**:
Target cluster joins federation fine but after a "while", kubefed-controller-manager shows ClusterNotReachable

**What you expected to happen**:
Target cluster to stay in federation

**How to reproduce it (as minimally and precisely as possible)**:
kubefedctl join target-cluster --cluster-context target-cluster --host-cluster-name host-cluster --host-cluster-context host-cluster --v=2 --kubefed-namespace=kube-federation-system

Let that above work and wait 40 minutes or so.
Output of above command looked fine:
```
I0930 09:40:54.868390   23317 join.go:160] Args and flags: name target-cluster, host: host-cluster, host-system-namespace: kube-federation-system, kubeconfig: , cluster-context: target-cluster, secret-name: , dry-run: false
I0930 09:40:57.574874   23317 join.go:242] Performing preflight checks.
I0930 09:40:57.766002   23317 join.go:248] Creating kube-federation-system namespace in joining cluster
I0930 09:40:57.960535   23317 join.go:386] Already existing kube-federation-system namespace
I0930 09:40:57.960577   23317 join.go:256] Created kube-federation-system namespace in joining cluster
I0930 09:40:57.960607   23317 join.go:407] Creating service account in joining cluster: target-cluster
I0930 09:40:58.162961   23317 join.go:417] Created service account: target-cluster-host-cluster in joining cluster: target-cluster
I0930 09:40:58.163008   23317 join.go:445] Creating cluster role and binding for service account: target-cluster-host-cluster in joining cluster: target-cluster
I0930 09:40:58.951307   23317 join.go:454] Created cluster role and binding for service account: target-cluster-host-cluster in joining cluster: target-cluster
I0930 09:40:58.951355   23317 join.go:813] Creating cluster credentials secret in host cluster
I0930 09:40:59.334572   23317 join.go:839] Using secret named: target-cluster-host-cluster-token-qrxzf
I0930 09:40:59.538259   23317 join.go:882] Created secret in host cluster named: target-cluster-pp2gn
I0930 09:40:59.970396   23317 join.go:284] Created federated cluster resource
```
**Anything else we need to know?**:
when the cluster goes unhealthy, this is the log in kubefed-controller-manager
```
E0929 23:31:32.200579       1 clusterclient.go:131] Failed to do cluster health check for cluster "target-cluster": the server has asked for the client to provide credentials
```

**Environment**:
- Kubernetes version (use `kubectl version`)
```Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976"```

- KubeFed version
```KubeFed controller-manager version: version.Info{Version:"v0.4.0-13-gb31dd08", GitCommit:"b31dd086f79e8c18a4eb08735d6af40d778b6af1", GitTreeState:"clean", BuildDate:"2020-09-28T09:37:05Z", GoVersion:"go1.14.7", Compiler:"gc", Platform:"linux/amd64"}```

/kind bug

**Comment by makkes** [comment]
@kiich thanks for reporting this bug. After running `kubefedctl join`, would you please run `kubectl get kubefedclusters -Aw` and paste the output here? Does the cluster get ready eventually?

**Comment by kiich** [comment]
Thanks for getting back @makkes 
This turned out to be user error 🤦  where we were using the "generated" token as our secret on the host cluster which only lasted for 1 hour! once we used the proper token, this stayed up and target cluster in federation continued to stay.

Appreciate you getting back - i'm closing this one now. thanks!
