### ISSUE TITLE
Add e2e upgrade tests

### ISSUE THREAD

**Issue by makkes** [kubernetes-sigs/kubefed#1313]
**What would you like to be added**: End-to-end test verifying upgrade behaviour between two different kubefed versions.

**Why is this needed**: 

* Follow-up to #1296 
* These tests could (should?) be run on each PR to ensure existing kubefed clusters don't break with a certain change.

/kind feature

**Comment by hectorj2f** [comment]
I might take care of this test ;).

**Comment by hectorj2f** [comment]
@makkes  We added a test to upgrade from a previous image to the latest in master.

**Comment by makkes** [comment]
@hectorj2f would you mind linking it here and closing the issue then, please? Thanks!

**Comment by hectorj2f** [comment]
@makkes it was added here https://github.com/kubernetes-sigs/kubefed/pull/1346/commits/8a435bc9eb59adf6712a812868077491527c12b4.
