### ISSUE TITLE
No log output

### ISSUE THREAD

**Issue by mYmNeo** [kubernetes-sigs/kubefed#1314]
**What happened**:
add --v=X, X is log level. There is no log output for any level.

**What you expected to happen**:
option --v=X works well

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`)
- KubeFed version
master
- Scope of installation (namespaced or cluster)
- Others

/kind bug

**Comment by makkes** [comment]
Hi @mYmNeo, would you mind providing some more details on where (which component, kubefedctl, controller,...) and how you provided the flag, please? Thanks!

**Comment by mYmNeo** [comment]
> Hi @mYmNeo, would you mind providing some more details on where (which component, kubefedctl, controller,...) and how you provided the flag, please? Thanks!

I've tried `controller` and `hyperkube`, I think `kubefedctl` is the same situation. Since a commit about upgrade to kubernetes 1.19 dependency, this problem occurred. And v0.4.1 is not affected.

The flags is very simple, just run any of these binary with `--v=4`, For example, `controller` should print all flags result because of the print level greater than 1 , but in fact none of flags printed.

**Comment by hectorj2f** [comment]
@mYmNeo You are right, I can see the same behavior. It seems it ignores the verbose level in v0.5.0. For v0.4.0 and v0.4.1, it works as expected. Perhaps we have some hidden bugs when upgrading the new dependencies.

**Comment by hectorj2f** [comment]
@mYmNeo I pushed a bugfix if you have the chance to have a look at it https://github.com/kubernetes-sigs/kubefed/pull/1315

**Comment by mYmNeo** [comment]
> @mYmNeo I pushed a bugfix if you have the chance to have a look at it #1315

@hectorj2f I've tried this patch, it works. :+1:
