### ISSUE TITLE
planner 

### ISSUE THREAD

**Issue by htlabc** [kubernetes-sigs/kubefed#1317]
**What would you like to be added**:
I think node replica distribution can simulate the process of adding nodes through scheduler framwork. Then find the most suitable copy allocation number for each kubefed cluster, or dynamically allocate copies based on the resources of monitoring k8s

**Why is this needed**:

/kind feature

**Comment by hectorj2f** [comment]
@htlabc I think other people might miss some context here. Could you add more details about this issue such as user scenarios for this ? Is it a feature proposal or an improvement/addition to any existing feature ?
