### ISSUE TITLE
support kubernete  below kubernete v1.16

### ISSUE THREAD

**Issue by huiwq1990** [kubernetes-sigs/kubefed#1327]
**What would you like to be added**:

As upgrade `CustomResourceDefinition` solved with #1296 , kubefed could not deploy on kubernete v1.16 below.

**Why is this needed**:
 
We could not keep up with the newest k8s.

/kind feature

**Comment by makkes** [comment]
Thanks for raising this issue, @huiwq1990. However, Kubernetes 1.16 [isn't supported by the community, anymore](https://kubernetes.io/docs/setup/release/version-skew-policy/):

> The Kubernetes project maintains release branches for the most recent three minor releases (1.20, 1.19, 1.18). Kubernetes 1.19 and newer receive approximately 1 year of patch support. Kubernetes 1.18 and older received approximately 9 months of patch support.

You will not receive patches for 1.16 by the community. I understand some vendors still support older versions but I'm not sure whether kubefed should support any Kubernetes version older than the three most recent minor revisions.

**Comment by huiwq1990** [comment]
Thanks, whether support not latest version really matter for me or someone else, any result please notify us.
