### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by WoodpeckerBaby** [kubernetes-sigs/kubefed#1344]

**Comment by hectorj2f** [comment]
@WoodpeckerBaby It isn't. Why are you asking ?

**Comment by WoodpeckerBaby** [comment]
I check back every few months, and I feel this project is not getting as much love as before. Recent comments are more maintenance in nature, and this has been in Alpha since I noticed that V1 was deprecated. I’m wondering if it’s stuck for some Engineering reason like Apple’s AirPower. Since that this is a really complex and high risk project, there is no guarantee that it will work, at least until it does.

**Comment by hectorj2f** [comment]
Please, check the Slack channel and attend to the sig meeting if possible. There is a plan for an official beta release even if it is consistent enough to be considered as beta regarding core feat.

**Comment by hectorj2f** [comment]
@WoodpeckerBaby I am sharing the plans for kubefed beta that I presented in one of our previous sig meetings https://docs.google.com/presentation/d/1YSk7y-qZvfdz8hUNgB6tQtz8EdAhmhqrjDEsMJXzV-o/edit?usp=sharing.

**Comment by hectorj2f** [comment]
I am closing this issue for now. Please, feel free to re-open it again if you need more answers to your initial question.
