### ISSUE TITLE
No DnsEndpoint created

### ISSUE THREAD

**Issue by npu21** [kubernetes-sigs/kubefed#1345]
**What happened**:
After creation of a Service Domain and a ServiceDNSRecord for the federated service，there's no DNSEndpoint result.
Any help will be appreciated！
```
root@master1:~# kubectl get dnsendpoint -A
No resources found
```
**What you expected to happen**:
A DnsEndpoint created

**Environment**:
- Kubernetes version (use `kubectl version`)
- v1.18.8
- KubeFed version
- v0.5.1
- Scope of installation (namespaced or cluster)
- Others
 ```
root@master1:~/kubefed# kubectl get  svc -n namespace-fed --context=cluster.ggz 
NAME            TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)          AGE
nginx-fed-svc   LoadBalancer   10.105.92.186   172.16.13.100   8000:31557/TCP   2d8h
root@master1:~/kubefed# kubectl get svc -n namespace-fed 
NAME            TYPE           CLUSTER-IP       EXTERNAL-IP     PORT(S)          AGE
nginx-fed-svc   LoadBalancer   10.105.189.154   172.16.12.101   8000:32152/TCP   2d8h
root@master1:~/kubefed# kubectl get domain -A
NAMESPACE                NAME          AGE
kube-federation-system   test-domain   20m
root@master1:~/kubefed# kubectl get servicednsrecord -A
NAMESPACE       NAME            AGE
namespace-fed   nginx-fed-svc   20m
```

/kind bug

**Comment by yuswift** [comment]
See [there](https://github.com/kubernetes-sigs/kubefed/issues/1316).

**Comment by conquerorAlex** [comment]
I got the same error. And All nodes have region/zone labels. As follow:
![image](https://user-images.githubusercontent.com/45348944/109940567-327c8400-7d0d-11eb-837c-3af86a9e9aa8.png)

error log:
![image](https://user-images.githubusercontent.com/45348944/109940608-3dcfaf80-7d0d-11eb-8c2f-b8a1dbe1b9a8.png)

**Comment by hectorj2f** [comment]
@conquerorAlex That functionality would be removed within the next release. I would try to have a look and test it with `v0.5.1` to check if I can reproduce it.
