### ISSUE TITLE
Upgrade controller-runtime to 0.8.1

### ISSUE THREAD

**Issue by sagikazarmark** [kubernetes-sigs/kubefed#1358]
**What would you like to be added**:

Upgrade controller-runtime to 0.8.1

Required changes:

- Upgrade admission webhook to v1
- kubernetes/kube-openapi#220

**Why is this needed**: Allow clients to use newer controller-runtime

/kind feature

**Comment by yuswift** [comment]
@sagikazarmark 
The latest controller-runtime version is v0.8.3. Should we upgrade to this version? If so, I'm willing to open a pr for this issue.

**Comment by sagikazarmark** [comment]
Sure, why not. Not sure if the above linked PR is updated everywhere.

**Comment by hectorj2f** [comment]
@yuswift Sure, please do it :).

**Comment by makkes** [comment]
I'm trying to take another stab at this as this will bite more and more clients are upgrading to controller-runtime v0.7.0+
