### ISSUE TITLE
Use Docker credentials to circumvent request limit

### ISSUE THREAD

**Issue by makkes** [kubernetes-sigs/kubefed#1359]
**What would you like to be added**:
The kubefed project is now included in Docker's Open Source Program: https://kubernetes.slack.com/archives/C09R1PJR3/p1611587365011500

We need to use the credentials of the Docker Hub "kubefed" project in our CI builds.

**Why is this needed**:
To get around Docker Hub rate limits in CI and thus build failures.

/kind feature

**Comment by hectorj2f** [comment]
Yes, we need to apply these changes. We are getting some rate limit errors in PRs.

**Comment by hectorj2f** [comment]
Yes, we need this fix as soon as possible.

**Comment by hectorj2f** [comment]
@makkes I believe we can close this ticket now :).

**Comment by makkes** [comment]
From @jimmidyson on a related PR:
> GitHub actions are not rate limited under partner agreement
