### ISSUE TITLE
failed to set propagation 

### ISSUE THREAD

**Issue by conquerorAlex** [kubernetes-sigs/kubefed#1368]
**What happened**:
according user guide(https://github.com/kubernetes-sigs/kubefed/blob/master/docs/userguide.md) to build test, after creating the test-namespace for the test resources, got error log as follow:
![image](https://user-images.githubusercontent.com/45348944/109783026-7f485800-7c44-11eb-875c-fb6c07a3f644.png)

Operation Steps:
`./scripts/create-clusters.sh`
`helm --namespace kube-federation-system upgrade -i kubefed ./kubefed-0.6.1.tgz --create-namespace`
`kubefedctl join cluster1 --cluster-context cluster1 --host-cluster-context cluster1 --v=2`
`kubefedctl join cluster2 --cluster-context cluster2 --host-cluster-context cluster1 --v=2`
`kubectl apply -f example/sample1/namespace.yaml \
    -f example/sample1/federatednamespace.yaml`

**Environment**:
- Kubernetes version: v1.19.1
- KubeFed version: v0.6.1
- Scope of installation (namespaced)

/kind bug

**Comment by conquerorAlex** [comment]
`kubectl apply -f example/sample1/federateddeployment.yaml`
got similar error logs:
![image](https://user-images.githubusercontent.com/45348944/109784915-86706580-7c46-11eb-9741-f9da115c0863.png)

**Comment by hectorj2f** [comment]
How does your kubefedclusters look `kubectl get kubefedclusters -o yaml -A ?

**Comment by conquerorAlex** [comment]
@hectorj2f 
`[root@work1 sample1]# kubectl get kubefedclusters -o yaml -A
apiVersion: v1
items:
- apiVersion: core.kubefed.io/v1beta1
  kind: KubeFedCluster
  metadata:
    creationTimestamp: "2021-03-04T01:47:51Z"
    generation: 1
    managedFields:
    - apiVersion: core.kubefed.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          .: {}
          f:apiEndpoint: {}
          f:caBundle: {}
          f:secretRef:
            .: {}
            f:name: {}
      manager: kubefedctl
      operation: Update
      time: "2021-03-04T01:47:51Z"
    - apiVersion: core.kubefed.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:conditions: {}
      manager: controller-manager
      operation: Update
      time: "2021-03-04T01:48:45Z"
    name: cluster1
    namespace: kube-federation-system
    resourceVersion: "167403"
    selfLink: /apis/core.kubefed.io/v1beta1/namespaces/kube-federation-system/kubefedclusters/cluster1
    uid: 31cda3b5-451d-4f76-908a-b4d877638f9b
  spec:
    apiEndpoint: https://172.18.0.2:6443
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeE1ETXdNekE1TkRFMU5sb1hEVE14TURNd01UQTVOREUxTmxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTXNmCjFqbDhhRWwxckV0RUFGYlM5TDZtUVdVYlgxWTl6NWtMeGJweXpITkVYZnBuQ3ZzM2tZN2ZQK1h1TWlOMUo5bm0KVFFheGJQSVVEYkNKNnRwTHdvTVdUWEY1SkhuQVhFVENxNStETlpkL3pOV3FTMHRKMU9JN2NGOWRydkVVNnU0bQpUaldMM3F4Uy8wc0pNdTE2Z3VwNUl5QjluZWpDN1VhN2p0M1dueWlaTlZxMnhNbGFpWEhxQmQ4Z0taYlJIeVdOCkk2Y3V0b20vM0d6TEpOUDNNZVgyVXhhR2xvZkFLVEZjZTExUDJxUFUyWGZiYm9PZGNMR00wcDZyT1hyTmZMbVcKU2ovTFg1clhHWjRkS0MyT0VWbU1uZ1VMNnFEWGM4Ukh3M0lueGlsVFdnd2g5WDlYS3ZYSnU5dk9sWFFKUHVUZAp0UktmVHFCWWlrQ1BiZ0JITXhVQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZKZ2FLM2xVUUxBTDRHaXl3ajJTaXM5Ymp3T25NQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFBTGs4ZjdJNWZMQ2hNeGhGNXF4YTFyalBUVkJBUFB6b0cwdGhPdjczbUpBU25hSDN0eQpNZE5ObjlmZUtHRkk4NTIxUGlMbzlTVHg3STlKTXQzOHdENmxxUUpVNVdHd3BYaFpYWFRSdjliUTBkdzlJcFpyCno5Z0YvRWw5bDUzNDNTWUFzeEJ5dWtMaG5JZzMxQzM4REFjaUFZSldrcEJxdmk0VWlTZkFnRXUvRklpbGtBU0IKcElZc1dMSitGcHhmb3VrdEtBSWZLSkpLN2dTVGZqNStkRzUyN2t1dEdaSVpSeFNnQy9VR1JJSWtUVDVWanpDaAovSm5rREF6TjZQNDFTYTBycGZhZWJOMEN0eVNGenF1N0pEYk13bEY4REVmNFlBMTQ0Y2hlRHQ3Rm5hamlGblFEClBjTml4Q0dtWElMSStKVHlVK0Z0KzNPclN4QmlUZjlKd1pwdQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    secretRef:
      name: cluster1-gvvgb
  status:
    conditions:
    - lastProbeTime: "2021-03-04T01:48:45Z"
      lastTransitionTime: "2021-03-04T01:47:55Z"
      message: /healthz responded with ok
      reason: ClusterReady
      status: "True"
      type: Ready
- apiVersion: core.kubefed.io/v1beta1
  kind: KubeFedCluster
  metadata:
    creationTimestamp: "2021-03-04T01:48:02Z"
    generation: 1
    managedFields:
    - apiVersion: core.kubefed.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          .: {}
          f:apiEndpoint: {}
          f:caBundle: {}
          f:secretRef:
            .: {}
            f:name: {}
      manager: kubefedctl
      operation: Update
      time: "2021-03-04T01:48:02Z"
    - apiVersion: core.kubefed.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:conditions: {}
      manager: controller-manager
      operation: Update
      time: "2021-03-04T01:48:45Z"
    name: cluster2
    namespace: kube-federation-system
    resourceVersion: "167402"
    selfLink: /apis/core.kubefed.io/v1beta1/namespaces/kube-federation-system/kubefedclusters/cluster2
    uid: e5c01e22-c388-4112-80e8-5e4ad734ae88
  spec:
    apiEndpoint: https://172.18.0.3:6443
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeE1ETXdNekE1TkRJeU5Wb1hEVE14TURNd01UQTVOREl5TlZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTHo2Ck1xUk5URDZNd1doLzVscndNQWdOaWUzWHBKbm1uZUd3Vk5nMEh6NnplRlhOd213NjlJTDhVa29pcSt6b2k0SGQKM0NYYWc1cndJeXUrVWNtYkp6NWs5YUJLaGR5a0dxaXNOK2lQTzhMTS9sK1JyOGdzNmxLL2dHZktSbjd1WEU3QwpHeU5tNzVkQmJkMUNTUjBtNGNDd0UwMFY5VTd3UDEwV3VJaVZFdVJJaU9WbUZaUVdwSTR2R0lJS1NER0pKb0NKCnVYWndxcTVlRzF3c2IyVjlvWjFwVitoOWVqUzF3TXhzVE5BZVVTNGdjZFZoNW1GVEtUVkppc2ZRQmNtMzdOSTcKWGlYQjczNVF1a1JjaDUwOWhIYXRkUXBmODhTUWk2N0JVc2VIcEo5dWFLRy9rdk5tdEpXVnAvclBoTzVkajh3eApUNFZ6U056Ym1yVkZzUG9yYThzQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZJUUpnWmppSHBlZXhiYWh5SU5GdWROSHJrUTNNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFBLzhDRDdlcFVrMTdxei8vZG9ET1U1QVlWT1haRkNFbWd1YjJzWjZTMFNkOTJuRmwxNgpIeDRKbTArbGE2YW1zS0d0UTZ0WWt4UWVxYTdmNkNrVDNqQnN4RnNPMXp0cE0veHpTOVlJaXdTQmZOWTdaUTRGCmRzNTJIKytTdmc1MENZVlZoUHBOd2FOanFmenU5dEwwUlkzSXR6Zm4rOVV1TlUyTEhLcnd3OU1FWDNVODlFZEIKZTUrSDludDdmZUNwWXJVNnNkeFlDVFZ3cE1pL1ozMkZXSndBUVZNNVFpYURiNlVVdXhSNlJwV3FLTzdLREpNOQpwUFpaSmtuNFhTVFZQTmhqeS9XY3hscHNtazQ5bW5yeUl0U1JmN20zWXZNTlFNTm5iUm1EcWFSc0hvVXlFSUJhCjFLNVNBdDhRdDRXNUxEc2RCKzJCcTErUmFNbmFzMkVNM24wYwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    secretRef:
      name: cluster2-wx7pq
  status:
    conditions:
    - lastProbeTime: "2021-03-04T01:48:45Z"
      lastTransitionTime: "2021-03-04T01:48:05Z"
      message: /healthz responded with ok
      reason: ClusterReady
      status: "True"
      type: Ready
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
`
![image](https://user-images.githubusercontent.com/45348944/109898749-b31c8f80-7ccf-11eb-8bf9-6021d0360c11.png)

**Comment by luoMonkeyKing** [comment]
Version v.0.6.1, I also encountered the same error, is there any solution?
![image](https://user-images.githubusercontent.com/31637804/113959026-b36ef400-9854-11eb-8e3c-4146fd7ece8f.png)
Although an error was reported, it was successfully created in the federated cluster
![image](https://user-images.githubusercontent.com/31637804/113960894-c0411700-9857-11eb-9e07-a6f356724a01.png)
