### ISSUE TITLE
workqueue metrics do not work.

### ISSUE THREAD

**Issue by tehlers320** [kubernetes-sigs/kubefed#1372]
Due to the do.Once in this: 
https://github.com/kubernetes/client-go/blob/master/util/workqueue/metrics.go#L217-L227

This causes these 2 items to go first.

```
vendor/k8s.io/apiserver/pkg/endpoints/filters/storageversion.go:	_ "k8s.io/component-base/metrics/prometheus/workqueue" // for workqueue metric registration
vendor/k8s.io/apiserver/pkg/storageversion/manager.go:	_ "k8s.io/component-base/metrics/prometheus/workqueue" // for workqueue metric registration

```
Then finally 

https://github.com/kubernetes-sigs/kubefed/blob/master/cmd/controller-manager/app/controller-manager.go#L117

which has the doOnce flag already set from the other two and will not register. 

/kind bug

**Comment by mars1024** [comment]
I'm sorry but I've not got your point,

> Due to the do.Once in this:
> https://github.com/kubernetes/client-go/blob/master/util/workqueue/metrics.go#L217-L227

Yes, metrics provider can only be set once, and that depends on who call [SetProvider](https://github.com/kubernetes/client-go/blob/a5722b416f4b141ac9482ea884f6a5101087445c/util/workqueue/metrics.go#L259-L261) firstly.

> 
> This causes these 2 items to go first.
> 
> ```
> vendor/k8s.io/apiserver/pkg/endpoints/filters/storageversion.go:	_ "k8s.io/component-base/metrics/prometheus/workqueue" // for workqueue metric registration
> vendor/k8s.io/apiserver/pkg/storageversion/manager.go:	_ "k8s.io/component-base/metrics/prometheus/workqueue" // for workqueue metric registration
> ```

Actually, `SetProvider` is called by two upstreams as I know, one is `controller-runtime/pkg/metrics` and the other is `component-base/metrics`, in the whole project, only `controller-runtime/pkg/metrics` is [imported](https://github.com/kubernetes-sigs/kubefed/blob/16b2f5cc4f05c9e9b696970295f353c56d33aa3a/pkg/metrics/metrics.go#L24) , so obviously `metricsProvider` will be registered and generated by `controller-runtime`.

> Then finally
> 
> https://github.com/kubernetes-sigs/kubefed/blob/master/cmd/controller-manager/app/controller-manager.go#L117
> 
> which has the doOnce flag already set from the other two and will not register.
> 
> /kind bug

In the end, kubefed is only using the `metricsRegistry` defined in `controller-runtime`, for both `workqueue` metrics and some kubefed-inner metrics.

And I have been collecting workqueue metrics through PR #1371 in our product enviorments.

**Comment by tehlers320** [comment]
Hmm well i'm not sure what is going on then, but i'm building with `make controller` off master branch currently `16b2f5cc4f05c9e9b696970295f353c56d33aa3a`

Anything different in your process or is there a public build server with the master releases, maybe i've done something wrong.

**Comment by mars1024** [comment]
Nothing different I think, could you help to print collected metrics here?

**Comment by mars1024** [comment]
I can show an example in ours,
```
workqueue_queue_duration_seconds_bucket{name="federatedtypeconfigs",le="1e-08"} 0
workqueue_queue_duration_seconds_bucket{name="federatedtypeconfigs",le="1e-07"} 0
workqueue_queue_duration_seconds_bucket{name="federatedtypeconfigs",le="1e-06"} 0
workqueue_queue_duration_seconds_bucket{name="federatedtypeconfigs",le="9.999999999999999e-06"} 0
workqueue_queue_duration_seconds_bucket{name="federatedtypeconfigs",le="9.999999999999999e-05"} 2
workqueue_queue_duration_seconds_bucket{name="federatedtypeconfigs",le="0.001"} 8
workqueue_queue_duration_seconds_bucket{name="federatedtypeconfigs",le="0.01"} 8
workqueue_queue_duration_seconds_bucket{name="federatedtypeconfigs",le="0.1"} 8
workqueue_queue_duration_seconds_bucket{name="federatedtypeconfigs",le="1"} 8
workqueue_queue_duration_seconds_bucket{name="federatedtypeconfigs",le="10"} 8
workqueue_queue_duration_seconds_bucket{name="federatedtypeconfigs",le="+Inf"} 8
workqueue_queue_duration_seconds_sum{name="federatedtypeconfigs"} 0.001559293
workqueue_queue_duration_seconds_count{name="federatedtypeconfigs"} 8
```

**Comment by tehlers320** [comment]
@mars1024  thanks for being patient with me. 

Exact steps taken to ensure i have a 100% clean environment.

```
cd /tmp/
git clone git@github.com:kubernetes-sigs/kubefed.git
cd kubefed/
./scripts/download-binaries.sh
kind create cluster
make deploy.kind 
kubectl -n kube-federation-system port-forward kubefed-controller-manager-7c9bc5555f-8qjpg 9090
```

First pod:
https://gist.github.com/tehlers320/d836db9a72e86a2f05c5a05397a6be30
Second pod:
https://gist.github.com/tehlers320/e5586c22aaf6844230b45fcbfddd4282

**Comment by mars1024** [comment]
Did you ever run the controllers? I mean metrics are only visible after a valid collection.

**Comment by tehlers320** [comment]
@mars1024 ah thats a good point, ive been loading these into another kind cluster as well. But for cleanliness sake i added a federated namespace to the /tmp/kubefed cluster. Still no metrics.


```
Spec:
  Placement:
    Cluster Selector:
Status:
  Clusters:
    Name:    kind-kind
    Status:  ClusterNotReady
  Conditions:
    Last Transition Time:  2021-03-16T12:11:19Z
    Last Update Time:      2021-03-16T12:11:23Z
    Reason:                CheckClusters
    Status:                False
    Type:                  Propagation
  Observed Generation:     1
Events:
  Type     Reason           Age                From                           Message
  ----     ------           ----               ----                           -------
  Warning  ClusterNotReady  80s (x4 over 84s)  federatednamespace-controller  Cluster not ready
```

Is there some old version of something in a vendor folder? The docker builds still pickup vendor. If i change this to a version where i edited the client-go/workqueue/metrics.go in the same cluster 

Master branch:
https://gist.github.com/tehlers320/553f74516363a7aaa8b0d68fabbc3379

Reloading my edited vendor version:
https://gist.github.com/tehlers320/bf3e4c7f2799378adb09f74fb854fd76

**Comment by mars1024** [comment]
What do you mean by "reloading my edited vendor version"? I see the second gist contains the metrics what we expect.

**Comment by tehlers320** [comment]
> What do you mean by "reloading my edited vendor version"? I see the second gist contains the metrics what we expect.

I have done 
`go mod vendor`
and edited this line https://github.com/kubernetes/client-go/blob/master/util/workqueue/metrics.go#L217-L227 taking out the do.once to make this functional on `Reloading my edited vendor version (built locally):`

**Comment by mars1024** [comment]
try to visualize the dependency tree between two metrics registers and kubefed, 
```
➜  controller-manager git:() depth -explain sigs.k8s.io/controller-runtime/pkg/metrics .
. -> sigs.k8s.io/kubefed/cmd/controller-manager/app -> sigs.k8s.io/controller-runtime/pkg/metrics
. -> sigs.k8s.io/kubefed/cmd/controller-manager/app -> sigs.k8s.io/kubefed/cmd/controller-manager/app/leaderelection -> sigs.k8s.io/kubefed/cmd/controller-manager/app/options -> sigs.k8s.io/kubefed/pkg/controller/util -> sigs.k8s.io/kubefed/pkg/controller/util/ldcintegration -> sigs.k8s.io/kubefed/pkg/controller/util/ldcintegration/metrics -> sigs.k8s.io/controller-runtime/pkg/metrics
. -> sigs.k8s.io/kubefed/cmd/controller-manager/app -> sigs.k8s.io/kubefed/cmd/controller-manager/app/leaderelection -> sigs.k8s.io/kubefed/cmd/controller-manager/app/options -> sigs.k8s.io/kubefed/pkg/controller/util -> sigs.k8s.io/kubefed/pkg/metrics -> sigs.k8s.io/controller-runtime/pkg/metrics
➜  controller-manager git:() depth -explain k8s.io/component-base/metrics/prometheus/workqueue .
```

Seems `k8s.io/component-base/metrics/prometheus/workqueue` has never been imported, a little puzzled :)
Still working on this...

**Comment by mars1024** [comment]
check the three packages who have indirect dependency on `k8s.io/component-base/metrics/prometheus/workqueue`,
```
➜  controller-manager git:(bugfix/worker) depth -explain k8s.io/component-base/metrics/prometheus/clientgo .
➜  controller-manager git:(bugfix/worker) depth -explain k8s.io/apiserver/pkg/storageversion .              
. -> k8s.io/apiserver/pkg/server -> k8s.io/apiserver/pkg/storageversion
➜  controller-manager git:(bugfix/worker) depth -explain k8s.io/apiserver/pkg/endpoints/filters .
. -> k8s.io/apiserver/pkg/server -> k8s.io/apiserver/pkg/endpoints/filters
```

**Comment by mars1024** [comment]
So, the two dependency paths below will have a race,
```
kubefed-controller-manager -> k8s.io/apiserver/pkg/server -> k8s.io/apiserver/pkg/storageversion -> k8s.io/component-base/metrics/prometheus/workqueue
kubefed-controller-manager -> sigs.k8s.io/kubefed/cmd/controller-manager/app -> sigs.k8s.io/controller-runtime/pkg/metrics
```

And the second metrics register（which we expect）will not work with the limitation of `doOnce`.

**Comment by mars1024** [comment]
Thanks to @tehlers320 , I think this issue has been fixed, could you try again with the new version?

**Comment by tehlers320** [comment]
@mars1024 
Sorry this does not resolve the issue. I tried this earlier as well. 

This is what i built off of https://github.com/ExpediaInc/kubefed/commits/tehlers/metrics_and_reconcile which is current master + the reconcile patch.

**Comment by mars1024** [comment]
:?
Could you help to use `depth` tool to analyze the dependency trees about metrics?

**Comment by tehlers320** [comment]
@mars1024  i think i have it in this PR https://github.com/kubernetes-sigs/kubefed/pull/1386 if we can get our CLAs sorted out.

**Comment by tehlers320** [comment]
I thought this was fixed in image 0.7.0
```
 quay.io/kubernetes-multicluster/kubefed:v0.7.0
```

```
docker-pullable://quay.io/kubernetes-multicluster/kubefed@sha256:6d56f69b15a3a27e43792298bfd972f4f3e180d6abf642e79b70aaf1492ebd32
```

But i'm still not seeing the queue metrics, can anybody else confirm ?

**Comment by mars1024** [comment]
I see PR #1388 was merged just after v0.7.0 release, so maybe you need a private release for the metrics till v0.7.1 . @tehlers320

**Comment by hectorj2f** [comment]
We could schedule a release tomorrow. I think we have couple of minor bug fixes.

**Comment by hectorj2f** [comment]
Closing this issue as https://github.com/kubernetes-sigs/kubefed/pull/1388 got merged.
