### ISSUE TITLE
Adding the type identification of the cluster

### ISSUE THREAD

**Issue by algebra2k** [kubernetes-sigs/kubefed#1374]
**What would you like to be added**:
Currently, it is not possible to know what type of cluster is through the KubeFedCluster object。

**Why is this needed**:
In our actually practice, we often wrap a Cluster object on top of a KubeClusterObject and then we add `Type` fields to one, so we hope to add the  `Type` field to the KubeFedCluster object

/kind feature

**Comment by yuswift** [comment]
Does the `Type` field mean connection type or something else? I think we need to modify the field more clearly.
