### ISSUE TITLE
invalid kubefedctl version

### ISSUE THREAD

**Issue by dfateyev** [kubernetes-sigs/kubefed#1390]
**What happened**:
Kubefedctl downloaded from the 0.7 release page reports 0.6.1 version.

`kubefedctl version: version.Info{Version:"v0.6.1-34-ge13973ce-dirty", GitCommit:"e13973ceaaba961a9abb6c7cb17a1d6a92c6eaf8", GitTreeState:"dirty", BuildDate:"2021-03-25T17:37:15Z", GoVersion:"go1.15.3", Compiler:"gc", Platform:"linux/amd64"}
`

**What you expected to happen**:
Updated binary which represents a proper version

**How to reproduce it (as minimally and precisely as possible)**:
- Upgrade chart ("helm -n kube-federation-system upgrade kubefed kubefed-charts/kubefed")
- Download a release binary, e.g. "kubefedctl-0.7.0-linux-amd64.tgz"
- Check "kubefedctl version"

**Anything else we need to know?**:

**Environment**:
- Kubernetes version: 1.19.8
- KubeFed version: 0.6.1 / 0.7.0

/kind bug

**Comment by hectorj2f** [comment]
@dfateyev Let me check it, but I'll update the binaries. If I remember correctly, it is more of a tagging problem rather than a wrong downgraded version.

**Comment by hectorj2f** [comment]
@dfateyev It should be fixed now. Please, check it again.

**Comment by dfateyev** [comment]
@hectorj2f now the proper version is reported, thanks for the fix.
`kubefedctl version: version.Info{Version:"v0.7.0", GitCommit:"e13973ceaaba961a9abb6c7cb17a1d6a92c6eaf8", GitTreeState:"clean", BuildDate:"2021-04-01T15:30:57Z", GoVersion:"go1.15.3", Compiler:"gc", Platform:"linux/amd64"}
`
