### ISSUE TITLE
Multicluster Service DNS

### ISSUE THREAD

**Issue by luoMonkeyKing** [kubernetes-sigs/kubefed#1395]
Hi, what about Multicluster Service DNS
Is there any documentation for Multicluster Ingress DNS operation? I think there is no relevant document in the master branch, is it not supported?

**Comment by hectorj2f** [comment]
This feature has been removed from kubefed #1360  and #1283.

**Comment by luoMonkeyKing** [comment]
> This feature has been removed from kubefed #1360 and #1283.
Ok, thanks. Is there any relevant Multicluster DNS case operation document? I don’t know how to do it now.

**Comment by yuswift** [comment]
Hope this [link](https://github.com/kubernetes-sigs/kubefed/blob/v0.6.1/docs/servicedns-with-externaldns.md) be helpful for you. If you really want to use `Multicluster Service DNS` with kubefed, please use v0.6.1 and enable the feature manually. But just as @hectorj2f said, the feature has been deprecated.

**Comment by luoMonkeyKing** [comment]
> Hope this [link](https://github.com/kubernetes-sigs/kubefed/blob/v0.6.1/docs/servicedns-with-externaldns.md) be helpful for you. If you really want to use `Multicluster Service DNS` with kubefed, please use v0.6.1 and enable the feature manually. But just as @hectorj2f said, the feature has been deprecated.

ok，thanks!
