### ISSUE TITLE
dnsendpoints.multiclusterdns.kubefed.io is forbidden

### ISSUE THREAD

**Issue by luoMonkeyKing** [kubernetes-sigs/kubefed#1398]
**What happened**:
Did not generate dnsendpoints, query the external-dns pod log and report an error, federatedclusterrolebinding.yaml has been executed

`time="2021-04-09T01:37:00Z" level=error msg="dnsendpoints.multiclusterdns.kubefed.io is forbidden: User \"system:serviceaccount:kube-system:default\" cannot list resource \"dnsendpoints\" in API group \"multiclusterdns.kubefed.io\" at the cluster scope"`

**Environment**:
- Kubernetes version ：v1.17.4
- KubeFed version : v0.6.1
- Scope of installation (namespaced or cluster)
- Others

**Comment by yuswift** [comment]
`kubefed` use `kubefed-controller` as sa instead of `default`. I suggest you reinstalling `kubefed` by helm to avoid such environment errors.

**Comment by luoMonkeyKing** [comment]
> `kubefed` use `kubefed-controller` as sa instead of `default`. I suggest you reinstalling `kubefed` by `helm` to avoid such environment errors.

This is an error from external-dns, do I need to reinstall kubefed? I installed kubefed through the following command:
`helm --namespace kube-federation-system upgrade -i kubefed kubefed-charts/kubefed --version=0.6.1 --create-namespace`
external-dns is in the kube-system namespace。

**Comment by yuswift** [comment]
> > `kubefed` use `kubefed-controller` as sa instead of `default`. I suggest you reinstalling `kubefed` by `helm` to avoid such environment errors.
> 
> This is an error from external-dns, do I need to reinstall kubefed? I installed kubefed through the following command:
> `helm --namespace kube-federation-system upgrade -i kubefed kubefed-charts/kubefed --version=0.6.1 --create-namespace`
> external-dns is in the kube-system namespace。

I thought the log came from `kubefed`. You don't need to reinstall `kubefed`. Just need to assign `RBAC` permissions to `external-dns`. See docs [here](https://kubernetes.io/docs/reference/access-authn-authz/rbac/).

**Comment by luoMonkeyKing** [comment]
> > > `kubefed` use `kubefed-controller` as sa instead of `default`. I suggest you reinstalling `kubefed` by `helm` to avoid such environment errors.
> > 
> > 
> > This is an error from external-dns, do I need to reinstall kubefed? I installed kubefed through the following command:
> > `helm --namespace kube-federation-system upgrade -i kubefed kubefed-charts/kubefed --version=0.6.1 --create-namespace`
> > external-dns is in the kube-system namespace。
> 
> I thought the log came from `kubefed`. You don't need to reinstall `kubefed`. Just need to assign `RBAC` permissions to `external-dns`. See docs [here](https://kubernetes.io/docs/reference/access-authn-authz/rbac/).

Yes, I have successfully bound the sa, but the binding of serviceAccountName: external-dns is missing in this operation document
`https://github.com/kubernetes-sigs/kubefed/blob/v0.6.1/docs/ingress-service-dns-with-coredns.md`

**Comment by yuswift** [comment]
I remembered that the docs were offered by `external-dns` repo.

**Comment by xunpan** [comment]
This feature was removed from `kubefed`.

FYI: https://github.com/kubernetes-sigs/kubefed/pull/1360

**Comment by yuswift** [comment]
Could we close this issue? @luoMonkeyKing

**Comment by luoMonkeyKing** [comment]
> I remembered that the docs were offered by `external-dns` repo.



> close



> Could we close this issue? @luoMonkeyKing

ok，thanks
