### ISSUE TITLE
How to implement Multicluster Service DNS function in v0.7.0 version？

### ISSUE THREAD

**Issue by luoMonkeyKing** [kubernetes-sigs/kubefed#1403]
Hi, the Multicluster Service DNS function has been deleted in v0.7.0 version. I want to use the changed function in the new version. Are there any examples? I saw in [https://github.com/kubernetes-sigs/kubefed/issues/1283](url) that it says to use service meshes or multi-cluster mesh, but I don’t know how to use it. How to do it, is there any relevant documentation?

**Environment**:
- KubeFed version  v0.7.0

**Comment by wdwangcumt** [comment]
I have the same question. Anybody can help us?

**Comment by wdwangcumt** [comment]
The multi-cluster service discory feature has been removed in the verison `0.7.0`, you can see the details at https://github.com/kubernetes-sigs/kubefed/issues/1284

**Comment by luoMonkeyKing** [comment]
> The multi-cluster service discory feature has been removed from kubefed with the verison `0.7.0`, you can see the details at #1284

Yes, I have seen this, but I don’t know how to use service meshes in version 0.7. Do you know how to use it?

**Comment by wdwangcumt** [comment]
Service mesh（eg: istio） is a standalone project, which can be deployed in a member k8s cluster separately. As far as I know, in general, Istio only does service governance for a single cluster. As for service governance for multiple clusters, you can learn it from its official website. I have got a guide from https://istio.io/latest/blog/2020/multi-cluster-mesh-automation/, I hope it is useful for you.

**Comment by wdwangcumt** [comment]
> > The multi-cluster service discory feature has been removed from kubefed with the verison `0.7.0`, you can see the details at #1284
> 
> Yes, I have seen this, but I don’t know how to use service meshes in version 0.7. Do you know how to use it?

Service mesh（eg: istio） is a standalone project, which can be deployed in a member k8s cluster separately. As far as I know, in general, Istio only does service governance for a single cluster. As for service governance for multiple clusters, you can learn it from its official website. I have got a guide from https://istio.io/latest/blog/2020/multi-cluster-mesh-automation/, I hope it is useful for you.

**Comment by luoMonkeyKing** [comment]
> > > The multi-cluster service discory feature has been removed from kubefed with the verison `0.7.0`, you can see the details at #1284
> > 
> > 
> > Yes, I have seen this, but I don’t know how to use service meshes in version 0.7. Do you know how to use it?
> 
> Service mesh（eg: istio） is a standalone project, which can be deployed in a member k8s cluster separately. As far as I know, in general, Istio only does service governance for a single cluster. As for service governance for multiple clusters, you can learn it from its official website. I have got a guide from https://istio.io/latest/blog/2020/multi-cluster-mesh-automation/, I hope it is useful for you.

ok, thank you very much, let me study. If you succeed later, can you share this case?
