### ISSUE TITLE
the federatedtypeconfigs in chart are installed in the default namespace

### ISSUE THREAD

**Issue by zqzzq** [kubernetes-sigs/kubefed#1404]
**What happened**:
The federatedtypeconfigs in chart are installed in the default namespace and cannot be recognized by the controller. 
**What you expected to happen**:
The federatedtypeconfigs in chart are installed in kube-federation-system namespace.
**How to reproduce it (as minimally and precisely as possible)**:
```
helm template --name kubefed --namespace kube-federation-system ./kubefed/  > fed.yaml
kubectl apply -f fed.yaml
```
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`)
- KubeFed version v0.7.0
- Scope of installation (namespaced or cluster)
- Others

/kind bug

**Comment by yuswift** [comment]
Docs can be found [here](https://github.com/kubernetes-sigs/kubefed/blob/master/charts/kubefed/README.md#installing-the-chart). When you execute `helm template --name kubefed --namespace kube-federation-system ./kubefed/  > fed.yaml`, you get the manifest which don't contain `kube-federation-system`. But if you execute `helm --namespace kube-federation-system upgrade -i kubefed kubefed-charts/kubefed --version=0.7.0 --create-namespace`, `federatedtypeconfig` will be installed in `kube-federation-system` namespace. Adding namespace for federatedconfig in chart will be better for `helm template`, but I don't think it's a bug for kubefed. Need more suggestions from @irfanurrehman .
