### ISSUE TITLE
failed to upgrade kubefed from v0.7.0 to v0.8.1

### ISSUE THREAD

**Issue by swiftslee** [kubernetes-sigs/kubefed#1452]
**What happened**:
helm --namespace kube-federation-system upgrade -i kubefed kubefed-charts/kubefed --version=0.8.1 --create-namespace
```
Error: UPGRADE FAILED: error validating "": error validating data: [ValidationError(KubeFedConfig.spec): unknown field "statusController" in io.kubefed.core.v1beta1.KubeFedConfig.spec, ValidationError(KubeFedConfig.spec.syncController): unknown field "maxConcurrentReconciles" in io.kubefed.core.v1beta1.KubeFedConfig.spec.syncController]
```
**What you expected to happen**:
successfully upgraded kubefed
**How to reproduce it (as minimally and precisely as possible)**:
install kubefed v0.7.0 on k8s v1.21, then upgrade it to v0.8.1
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`)
- KubeFed version
- Scope of installation (namespaced or cluster)
- Others

/kind bug
I think this error is caused by the old crd. If we apply the new `kubefedconfig` crd manually, we can avoid this error. Any better solutions?

**Comment by yuswift** [comment]
After I applied the new `kubefedconfig` crd, another error happened:
```
F0902 10:52:40.193071       1 controller-manager.go:358] Error: invalid KubeFedConfig "kube-federation-system/kubefed": [spec.syncController.maxConcurrentReconciles: Required value spec.statusController: Required value]
```
I checked the `kubefedconfig` and found that the `spec.statusController` filed was missing.
I think we should patch the `kubefedconfig` in the `post-install-job` just like what @hectorj2f did.

**Comment by yalctay93** [comment]
I had the same issue. For us, we just deployed the helm chart AGAIN and that time it worked. Apparently the CRD for some reason was not updated in the first run. Interestingly, our pipeline first applies the CRDs each time before doing an helm upgrade - seems like either kubernetes was not fast enough on updating the CRDs or we really just have a timing issue.

Still, I find it interesting that someone else has encountered the same problem as me.

**Comment by yuswift** [comment]
> I had the same issue. For us, we just deployed the helm chart AGAIN and that time it worked. Apparently the CRD for some reason was not updated in the first run. Interestingly, our pipeline first applies the CRDs each time before doing an helm upgrade - seems like either kubernetes was not fast enough on updating the CRDs or we really just have a timing issue.
> 
> Still, I find it interesting that someone else has encountered the same problem as me.

Interesting.
