### ISSUE TITLE
Support selector-based overrides

### ISSUE THREAD

**Issue by mvaal** [kubernetes-sigs/kubefed#1462]
**What would you like to be added**:

Ability to define a clusterSelector on all FederatedOverride objects.

**Why is this needed**:
Re-opening this as issues with this keep coming up.

https://github.com/kubernetes-sigs/kubefed/issues/581
https://github.com/kubernetes-sigs/kubefed/issues/643

I had commented on the ticket a year ago but wasn't able to reactivate it.

The original concerns on this was that we didn't have a way to handle conflicting overrides, but I think the solution to this is just make the order the priority. Last override in the list wins.

/kind feature

**Comment by zqzten** [comment]
That's what I plan to do then. But it do need some concern on conflicts and propagated version calculating issues.

/assign

**Comment by mrbobbytables** [comment]
Project is to be archived - closing all issues and PRs

see https://github.com/kubernetes/org/issues/4122 and https://groups.google.com/d/msgid/kubernetes-sig-multicluster/9f8d81d1-07d1-4985-a7bf-d76197deb971n%40googlegroups.com

for details

/close
