### ISSUE TITLE
Remove deprecate klog flag usage

### ISSUE THREAD

**Issue by serathius** [kubernetes-sigs/kubefed#1470]
/kind feature

Hey, in K8s 1.23 we are planning to deprecate multiple klog flags. [KEP-2845](https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/2845-deprecate-klog-specific-flags-in-k8s-components/README.md)

Deprecated flags: `--log-dir`, `--log-file`, `--log-flush-frequency`, `--logtostderr`, `--alsologtostderr`, `--one-output`, `--stderrthreshold`, `--log-file-max-size`, `--skip-log-headers`, `--add-dir-header`, `--skip-headers`, `--log-backtrace-at`

One of the alpha milestones is requires us to remove usage of deprecated flags within K8s repo. Examples found for kubefed:
* https://github.com/kubernetes-sigs/kubefed/blob/2fc7e363a78e5e4ab9853382e799b00a66dfa429/scripts/sync-up-helm-chart.sh#L84 
/wg structured-logging

**Comment by NikhilSharmaWe** [comment]
@serathius I would like to contribute for this case. I am little bit confused about how to remove deprecated klog flags usage in this case, could you please give me some direction about how to proceed while tackling this issue.

**Comment by serathius** [comment]
We need to stop using `--log-file=${WORKDIR}/kube-apiserver.log --logtostderr=false` flags and use other means to redirect command output to file. In case of this script I think we can use standard bash redirection. You can read about them here https://www.gnu.org/software/bash/manual/html_node/Redirections.html

My first guess would be that we should replace
```
${ROOT_DIR}/bin/kube-apiserver --etcd-servers=http://127.0.0.1:2379 --service-cluster-ip-range=10.0.0.0/16 --cert-dir=${WORKDIR} --log-file=${WORKDIR}/kube-apiserver.log --logtostderr=false 2> /dev/null &
```
with 
```
${ROOT_DIR}/bin/kube-apiserver --etcd-servers=http://127.0.0.1:2379 --service-cluster-ip-range=10.0.0.0/16 --cert-dir=${WORKDIR} 2> ${WORKDIR}/kube-apiserver.log &
```

kube-apiserver writes by default to stderr, in the line we are chaning it uses:
* `--logtostderr=false` to disable writing to stderr
* ` 2>/dev/null` drop any output send to stderr 
* ` --log-file=${WORKDIR}/kube-apiserver.log` write log to file

Instead we use `2> ${WORKDIR}/kube-apiserver.log` which just redirects stderr to file.
