### ISSUE TITLE
test case failed frequently with no relationship of code change

### ISSUE THREAD

**Issue by xunpan** [kubernetes-sigs/kubefed#1474]
**What happened**:
PR fails in non-related test case even with retry.
https://github.com/kubernetes-sigs/kubefed/pull/1469
https://github.com/kubernetes-sigs/kubefed/pull/1455

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`)
- KubeFed version
- Scope of installation (namespaced or cluster)
- Others

/kind bug

**Comment by irfanurrehman** [comment]
Was fixed by https://github.com/kubernetes-sigs/kubefed/pull/1500
/close
