### ISSUE TITLE
Delete Federated Resources

### ISSUE THREAD

**Issue by AndyLZY** [kubernetes-sigs/kubefed#1482]
How to delete federated resources on member clusters together when executing the unjoin command？

**Comment by swiftslee** [comment]
I think you should delete the federated resources first on the host cluster.

**Comment by irfanurrehman** [comment]
@AndyLZY the unjoin does not delete the cluster local resources. You as a user are expected to delete the resources before or after unjoin.
Closing this as explained.
/close
