### ISSUE TITLE
velaux: Bind Environments can't load

### ISSUE THREAD

**Issue by SUMMERLm** [kubernetes-sigs/kubefed#1487]
**What happened**:
![image](https://user-images.githubusercontent.com/92348982/150906765-f2142dc2-9d51-4459-8db3-10e4b7c95ead.png)

**What you expected to happen**:
should load env 
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
vela version
Version: v1.2.1
GitRevision: git-12f392c
GolangVersion: go1.16.13
**Environment**:
- Kubernetes version (use `kubectl version`)
- KubeFed version
- Scope of installation (namespaced or cluster)
- Others

/kind bug

**Comment by irfanurrehman** [comment]
Closing as not applicable to kubefed
/close
