### ISSUE TITLE
metrics volume is un-sustainable. 

### ISSUE THREAD

**Issue by tehlers320** [kubernetes-sigs/kubefed#1488]
**What happened**:

```
curl http://localhost:9090/metrics -o /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:30 --:--:--     0
curl: (56) Recv failure: Connection reset by peer
```

**What you expected to happen**:
Fast responses from the metrics url.

**How to reproduce it (as minimally and precisely as possible)**:
add 100+ clustsers with many federated types.

**Anything else we need to know?**:
Yes you can filter the metrics quantity and increase the timeout. But we have 315930 metrics now and its putting excessive load on kubfed as it gets queried then filtered including a 63.8MB download.

```
cat ~/Downloads/metrics  |cut -d \{ -f1 |sort |uniq -c |sort -nr |head
 265496 rest_client_request_latency_seconds_bucket
  24136 rest_client_request_latency_seconds_sum
  24136 rest_client_request_latency_seconds_count
    520 rest_client_requests_total
    489 kubefedcluster_total
    319 workqueue_work_duration_seconds_bucket
    319 workqueue_queue_duration_seconds_bucket
     66 controller_runtime_reconcile_duration_seconds_bucket
     44 dispatch_operation_duration_seconds_bucket
     29 workqueue_work_duration_seconds_sum
```
We should stop this from sending a 63.8MB payload every 30s by having an option to remove just the rest_client data.

**Environment**: 
- Kubernetes version (use `kubectl version`) 1.20
- KubeFed version 0.8.1
- Scope of installation (namespaced or cluster)
- Others

/kind bug

**Comment by tehlers320** [comment]
https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.10.0 <--- this version turns off the rest metric by default. 

So it may be as simple as upgrading. https://github.com/kubernetes-sigs/kubefed/blob/master/go.mod#L28

**Comment by tehlers320** [comment]
I have it building here with controller 0.11.0 but it forced upgrading to 0.23.2 https://github.com/tehlers320/kubefed/commit/c22e25192d853b5ef4649d7bd924a65ea2eec976

**Comment by irfanurrehman** [comment]
@tehlers320 thanks for pointing out the issue. Would you be able to post a PR with the upgrade for the package. It seems you have already done it privately.

**Comment by tehlers320** [comment]
@irfanurrehman  https://github.com/kubernetes-sigs/kubefed/pull/1492 but it jumps golang versions (i couldnt get it working on 1.16, maybe it was my workstation not sure) and it jumps module versions skipping .22 

I also cant get the CLA thing working even though i've signed everything.
