### ISSUE TITLE
Helm chart 0.x.x to 0.9.x upgrade fails

### ISSUE THREAD

**Issue by tehlers320** [kubernetes-sigs/kubefed#1489]
**What happened**:
The new settings in the chart CRD appear to be set before the CRD goes in

```
Error: error validating "": error validating data: ValidationError(KubeFedConfig.spec.controllerDuration): unknown field "cacheSyncTimeout" in io.kubefed.core.v1beta1.KubeFedConfig.spec.controllerDuration
```

**What you expected to happen**:
upgrades work.

**How to reproduce it (as minimally and precisely as possible)**:
upgrade helm from 0.8.1 to 0.9.0

**Anything else we need to know?**:

I think this may fix it, not sure.
```
annotations:
  "helm.sh/hook": pre-install
```
on the CRD
**Environment**:
- Kubernetes version (use `kubectl version`)
- KubeFed version
- Scope of installation (namespaced or cluster)
- Others

/kind bug

**Comment by jimmidyson** [comment]
Could you please provide simplest repro steps?

**Comment by ra-grover** [comment]
Hey @jimmidyson , upgrading the helm chart from 0.8.1 to 0.9.2 you will face this error. 
```helm upgrade  -n kube-federation-system --set docker_tag=v0.9.2 kubefed .```

**Comment by mimmus** [comment]
Same issue.
@tehlers320 Do you were able to solve this?
