### ISSUE TITLE
cluster 1 and cluster2 not ready

### ISSUE THREAD

**Issue by lemon360cn** [kubernetes-sigs/kubefed#1498]
ubectl -n kube-federation-system get kubefedclusters
NAME       AGE   READY
cluster1   47m   
cluster2   46m   

**kubectl -n kube-federation-system describe kubefedclusters.core.kubefed.io cluster2
Name:         cluster2
Namespace:    kube-federation-system
Labels:       <none>
Annotations:  <none>
API Version:  core.kubefed.io/v1beta1
Kind:         KubeFedCluster
Metadata:
  Creation Timestamp:  2022-03-14T09:52:17Z
  Generation:          1
  Managed Fields:
    API Version:  core.kubefed.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        .:
        f:apiEndpoint:
        f:caBundle:
        f:proxyURL:
        f:secretRef:
          .:
          f:name:
    Manager:      kubefedctl
    Operation:    Update
    Time:         2022-03-14T09:52:17Z
    API Version:  core.kubefed.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:conditions:
    Manager:         controller-manager
    Operation:       Update
    Subresource:     status
    Time:            2022-03-14T09:52:19Z
  Resource Version:  3212
  UID:               c1c4b5a9-8a07-4fdb-836c-bbd6409aa94e
Spec:
  API Endpoint:  https://127.0.0.1:63219
  Ca Bundle:     LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCakNDQWU2Z0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRJeU1ESXhNekF6TURneU1Gb1hEVE15TURJeE1qQXpNRGd5TUZvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTmp2ClVrcHJPd0VJaE9UR3pDZXk2STJOLzJ5QW8xQk5XR0UvNWUvdmlQZEhyYVBxS0k5eWpZUEJ1TUFteGxFbXp6VzcKVkdIYjRZNW5HdlBiQmR2RkR4dUI5cThxVmg2WUFnRFJuMmRJMXEydUd0alp2UzlYd0VVcFZ1VjNldzd6RmpmVAp2RWFlbHV2SVZ5V01DRzZzTTVXSU1ydlhjaXZBK1hRU25nS0k5YVoxUDdqREhuSG5HOGJ5V1p1dlliTFNiVDBrCjljNk5yd1ZhdFB0M04raFhpREtsM2twbHNkaWt4N0VYWllxSXVUbjlCejB6U2c4SUpobDNoRE5LUDdFOGZVWUQKeG9XWXlibXlyYmYzUEJnN05GMk5WUnk5TWNlYkQ2Wno5SGJITE4vcml0SDBLWXA2SEc3MEVCc3VkV1pJSEdWYQplckgyNnFBdU44YVI1OFROY2VrQ0F3RUFBYU5oTUY4d0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVcKQkJTVW1TZTJrMWZ5dGFoS0k0ME9ocGx2ai9aNkdUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFvbGMzQU9HegpiblpRMkFDQkVhS3NLcEhnWHJHUjgxN09qcUxzcUpOTktQTjEzQzdGUDRyS2dSOUZSYUpuNG94cmJDUXVZM25BCnFNUC9pY1lNVE9LdjVBL09iMERCOFV0L2RVTXJCY2tBVUZLbmlnRW9xaWJoQ3lueE54RTYxWUszYWFWMmh5ekIKRlhrd0hYOTNlTHVOdHhFcmpvSVVqbytaczBlRElLRFdLWFdudlZqVmJscldyR2tsWTJBWldRem1FNjZUT3F0KwpZMTBhdnhCemRQZm5Fc3grbzVQZWVDODdjeS8rTE5IelJLYmthSnJkOGhKWmRNR3hBVHRlTlorbUdkRllTakJzCmkrOXRGRExhbFY3eEF2YUY0VUFVamh2SHhabFc5RmlSaEVTeUNLUGNNNnl2Z2doMGViWTJXUVpJcEt0UFZyZlUKY0pJY3JidVRUbWlEOWc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  Proxy URL:     
  Secret Ref:
    Name:  cluster2-6ltzk
Status:
  Conditions:
    Last Probe Time:       2022-03-14T10:14:00Z
    Last Transition Time:  2022-03-14T09:52:19Z
    Message:               cluster is not reachable
    Reason:                ClusterNotReachable
    Status:                True
    Type:                  Offline
Events:
  Type     Reason                         Age                   From                       Message
  ----     ------                         ----                  ----                       -------
  Warning  RetrievingClusterHealthFailed  108s (x121 over 21m)  kubefedcluster-controller  Failed to retrieve health of the cluster: Get "https://127.0.0.1:63219/healthz?timeout=3s": dial tcp 127.0.0.1:63219: connect: connection refused

**Comment by lemon360cn** [comment]
use macOS minikube env

**Comment by ameena007** [comment]
I used minikube but issue is still there

**Comment by ameena007** [comment]
(base) meenaam@meenaam-a01 kubefed % kubectl -n kube-federation-system describe  kubefedclusters  --cluster=master
Name:         master
Namespace:    kube-federation-system
Labels:       <none>
Annotations:  <none>
API Version:  core.kubefed.io/v1beta1
Kind:         KubeFedCluster
Metadata:
  Creation Timestamp:  2022-05-02T12:01:37Z
  Generation:          1
  Managed Fields:
    API Version:  core.kubefed.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        .:
        f:apiEndpoint:
        f:caBundle:
        f:proxyURL:
        f:secretRef:
          .:
          f:name:
    Manager:      kubefedctl
    Operation:    Update
    Time:         2022-05-02T12:01:37Z
    API Version:  core.kubefed.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:conditions:
    Manager:         controller-manager
    Operation:       Update
    Subresource:     status
    Time:            2022-05-02T12:01:38Z
  Resource Version:  1232
  UID:               36b402f0-b0fc-431c-bfbf-883b38386ebe
Spec:
  API Endpoint:  https://127.0.0.1:49374
  Ca Bundle:     <my_ca_bundle>
  Proxy URL:     
  Secret Ref:
    Name:  master-bzck5
Status:
  Conditions:
    Last Probe Time:       2022-05-02T12:03:29Z
    Last Transition Time:  2022-05-02T12:01:38Z
    Message:               cluster is not reachable
    Reason:                ClusterNotReachable
    Status:                True
    Type:                  Offline
Events:
  Type     Reason                         Age                 From                       Message
  ----     ------                         ----                ----                       -------
  Warning  RetrievingClusterHealthFailed  7s (x12 over 118s)  kubefedcluster-controller  Failed to retrieve health of the cluster: Get "https://127.0.0.1:49374/healthz?timeout=3s": dial tcp 127.0.0.1:49374: connect: connection refused

**Comment by ameena007** [comment]
Posted on StackOverflow:  https://stackoverflow.com/questions/72094070/unable-to-implement-multicluster-fedeartion-using-kubefed . Somehow not able to find a working example on mac with minikube and  latest helm, Kubernetes version.

**Comment by irfanurrehman** [comment]
Just noticed this, will check it out over the weekend

**Comment by OneCricketeer** [comment]
You need to use a script like this. This one is for kind, but I believe similar steps are required for minikube. 

https://github.com/kubernetes-sigs/kubefed/blob/master/scripts/fix-joined-kind-clusters.sh
