### ISSUE TITLE
Can I use kubefed to deploy a helm chart to multiple clusters？

### ISSUE THREAD

**Issue by AlawnWong** [kubernetes-sigs/kubefed#1509]
Can I use kubefed to deploy a helm chart to multiple clusters？

**Comment by 0xff-dev** [comment]
There should be two options for deploying to multi-cluster through helm.
1. Write kubefed's CR directly in the chart.
2. Use [`flux`](https://github.com/fluxcd/flux2) and `kubefed`. Change the CRD of flux into FederatedFluxCRD(`kubefedctl enable xxxx`), let the operator of flux distribute to multiple clusters through kubefed, and then create `FedeartedFluxCRD` to achieve multi-cluster deployment

**Comment by jpuskar** [comment]
We federate the FluxCD HelmRelease CR to do this. It works very well.
