### ISSUE TITLE
Determine versioning scheme for APIs / releases

### ISSUE THREAD

**Issue by pmorie** [kubernetes-sigs/kubefed#151]
The APIVersion of our APIs (example: v1alpha1) and release version (example: 2.0.0 etc) should be consistent. This issue is to pick a release versioning scheme and make it consistent with existing code/artifacts.

**Comment by pmorie** [comment]
My $0.02:

- the first alpha release should be version `0.0.1`, with next alpha releases `0.0.2`, `0.0.3` and so on
- the first beta release should be `0.1.0`

Thoughts?

**Comment by xunpan** [comment]
I think APIVersion should be independent from release version. However, as we're entering beta, do we plan to use `v1beta1` to our API version?

@shashidharatd @marun @pmorie

**Comment by marun** [comment]
@xunpan Yes, part of the beta release process will be renaming the API groups we intend to take to beta.  I've filed #856 to ensure we track the work involved.

**Comment by marun** [comment]
Thus far we've been incrementing the patch version (i.e. `v0.0.x`) with each alpha release.  With the move to beta, we will:

 - switch to incrementing the minor version (i.e. `v0.x.0`) for successive beta releases
 - switch to incrementing the patch version (i.e `v0.0.x`) to release bug fixes for a given beta release

When the project goes GA, we will:

 - update the major version to 1 (i.e. `v1.0.0`)
 - update the minor or patch versions according to how substantive a release is

Regarding API versioning:

 - types intended to be supported at the beta level will be transitioned to `v1beta1` 
 - types intended to be supported at the GA level will be transitioned to `v1`
