### ISSUE TITLE
Mark a portion of source manifest as "do not sync"

### ISSUE THREAD

**Issue by afoninsky** [kubernetes-sigs/kubefed#1510]
**What would you like to be added**:
Have possibility to mark a portion of manifest "do not override this if changed in managed cluster". For instance, it can be done bringing additional field into Federated specs together with _Overrides_, _Placement_ etc.

**Why is this needed**:
In the current paradigm kubefed acts as a single source of truth for all deliverables. The problem is - in the real word there is a bunch of controllers who also does modifications, in this case they start to fight with kubefed.

Kubefed has "[Local Value Retention](https://github.com/kubernetes-sigs/kubefed/blob/master/docs/userguide.md#local-value-retention)" but it is limited for a specific set of cases, and every new case requires code modification. As kubefed aims to be a framework for other platform it looks like a blocker.

**Use-case example to demonstrate the problem**:
I deliver _admission webhooks_ via _kubefed_. At the same time I'm using [cert-manager CA injector](https://cert-manager.io/docs/concepts/ca-injector/) feature in every target cluster in order to **generate/update tls certificates for webhooks**.

So I have a state when _cert-manager_ updates `ValidatingWebhookConfiguration.webhooks.clientConfig.caBundlepart` of the manifest in the target cluster and _kubefed_ controller erases it as source `FederatedValidatingWebhookConfiguration` manifest doesn't have it. Because of it **the whole cert-manager feature is not available**.

/kind feature

**Comment by zqzten** [comment]
This feature is indeed reasonable, but I'm not sure if there's need to customize retentions for every single resource object. If not, we might expose the customization in FederatedTypeConfig which would be much cleaner.

**Comment by afoninsky** [comment]
Hello. 

I assume by saying "retention" you mean if controller propagates changes to member clusters or not? So you're saying (please fix me if I wrong) that to have rule in `FederatedTypeConfig` is more preferable than in separate `FeredatedResource` manifests, right?

This is a good idea, but let me present for discussion another option:
describe this thing in FederatedResources itself, for instance using JSONPath.

I like it for the following reasons:
1. It is possible to divide RBAC roles for admins who maintain kubefed and operators deliver own manifests - very good option to build own workflows.
2. Makes deliveries more granular and explicit - when describe manifest and rule how to propagate it in one file it is easier to maintain and support, split into components etc.
3. Standard templating engines can be applied. For instance, we use helm and kustomize with custom plugins to deliver manifests, so can change logic on-the-fly based on requirements.
4. I do not think that `FederatedResource` type is currently overloaded, in fact there are only few items on the top of `Resource` there.

**Comment by zqzten** [comment]
@irfanurrehman Would be grateful if you can also give some opinions on this!

**Comment by irfanurrehman** [comment]
I can think of several usecase around this. 
- The retention can be specified once and applied globally to all resources of a specific federatedType
- It can be specified on each federated resource
- It can be further fine grainer to be applied to certain clusters and not to others.

I think we can do this in steps, with a goal that all the above configurations are possible eventually.
My recommendation would be to first extend existing local value retention to make it configurable, such that a user can specify new fields (probably via FTC) without having to change the code. Most of the current user needs might be solved only by this.

**Comment by zqzten** [comment]
> I think we can do this in steps, with a goal that all the above configurations are possible eventually. My recommendation would be to first extend existing local value retention to make it configurable, such that a user can specify new fields (probably via FTC) without having to change the code. Most of the current user needs might be solved only by this.

+1, let's first make it configurable in FTC, and leave others till there's a real need.

**Comment by afoninsky** [comment]
I'm fine with any solution which allows me to continue using kubefed, FTC sounds better that nothing :)
Now, how do you plan a feature. Is there ETA when it could be delivered (roadmap/plan, next release etc), or this will wait for opensource contributor? (sorry, It is not like I'm pushing or something, just for curiosity)

**Comment by zqzten** [comment]
> Now, how do you plan a feature. Is there ETA when it could be delivered (roadmap/plan, next release etc), or this will wait for opensource contributor?

This feature would need a KEP first than implementation, as KubeFed is in short of maintainers, we cannot provide an ETA with confidence. It would be mostly welcomed if there's some contributor who would like to work on this (or even take part in the maintenace). If not, I can carry on with it but I cannot give a clear ETA for now.

**Comment by zqzten** [comment]
@afoninsky KEP is here FYI: #1514
