### ISSUE TITLE
Supported kubernetes versions / webhook issues

### ISSUE THREAD

**Issue by ttasharski73** [kubernetes-sigs/kubefed#1513]
What kubernetes versions are supported with Kubefed? I have been trying to get to install on an AKS cluster v1.23.5 and I am assuming the API versions (v1betav1) are not supported anymore. 

**What happened**:

Error: failed to create resource: Internal error occurred: failed calling webhook "kubefedconfigs.core.kubefed.io": failed to call webhook: Post "https://kubefed-admission-webhook.kube-federation-system.svc:443/default-kubefedconfig?timeout=10s": no endpoints available for service "kubefed-admission-webhook"

**What you expected to happen**:

Controller connect to the webhook

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`) - 1.23.5
- KubeFed version 0.9.2
- Scope of installation (namespaced or cluster) - Cluster
- Others - AKS

/kind bug

**Comment by kundan2707** [comment]
@ttasharski73  
>What kubernetes versions are supported with Kubefed? 

The KubeFed deployment requires kubernetes version >= 1.16.  
There could be some other issue with other components and its configuration

**Comment by eugene-dm** [comment]
admissionregistration.k8s.io/v1beta1 is deprecated (and removed) in 1.23 in favor of admissionregistration.k8s.io/v1
