### ISSUE TITLE
Clusters are not getting joined in Kubernetes V1.24 and above using kubefedctl join

### ISSUE THREAD

**Issue by shivanisinghnitp** [kubernetes-sigs/kubefed#1528]
**What happened**: When I try joining clusters using kubefedctl join, it throws an error and the clusters aren't joined.
<img width="1728" alt="Screenshot 2022-11-23 at 9 38 30 AM" src="https://user-images.githubusercontent.com/58537821/203467670-cfc0136d-d1f7-4b09-a94b-fbc4ab7ae5eb.png">
**What you expected to happen**: The clusters should join

**How to reproduce it (as minimally and precisely as possible)**:  
<img width="835" alt="Screenshot 2022-11-23 at 9 30 01 AM" src="https://user-images.githubusercontent.com/58537821/203467318-4d93648f-a3ba-4143-adea-cbf79f901fda.png">
<img width="1494" alt="Screenshot 2022-11-23 at 9 31 39 AM" src="https://user-images.githubusercontent.com/58537821/203467419-deaaab8a-623b-4ebd-915f-47e957fdc17f.png">

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`) - 1.25
- KubeFed version - latest
- Scope of installation (namespaced or cluster)
- Others

/kind bug

**Comment by ebiiim** [comment]
I had the same issue and found that kubefedctl [v0.10.0](https://github.com/kubernetes-sigs/kubefed/releases/tag/v0.10.0) might work.

Might be related to #1515.

**Comment by lpc-v** [comment]
Have you met a problem: cluster 2 is not ready

**Comment by mrbobbytables** [comment]
Project is to be archived - closing all issues and PRs

see https://github.com/kubernetes/org/issues/4122 and https://groups.google.com/d/msgid/kubernetes-sig-multicluster/9f8d81d1-07d1-4985-a7bf-d76197deb971n%40googlegroups.com

for details

/close
