### ISSUE TITLE
Kubefed is heading for archival

### ISSUE THREAD

**Issue by ohkinozomu** [kubernetes-sigs/kubefed#1531]
Kubefed will be archived. We should warn about it in this repository.
https://groups.google.com/g/kubernetes-sig-multicluster/c/aZv-YuafSko

**Comment by hak33m16** [comment]
Hey, looks like it might be time to mark it as archived. Could you break down why you decided to do this? We had design discussions and ended up with almost the exact same architecture as this project, and were really excited when we found it as we were considering adoption. I'm wondering if as a group you felt this was fundamentally flawed in some way?

**Comment by RainbowMango** [comment]
@hak33m16 If you like the architecture, I'd like to recommend another project to you, that is [Karmada](https://github.com/karmada-io/karmada) which inherits the concept of Kubefed.

**Comment by levenhagen** [comment]
Please feel free to check out https://open-cluster-management.io/ as well. It's another alternative to kubefed.

**Comment by ohkinozomu** [comment]
Close this issue as https://github.com/kubernetes-sigs/kubefed/pull/1532 was merged.
