### ISSUE TITLE
Don't support istio?

### ISSUE THREAD

**Issue by aogg** [kubernetes-sigs/kubefed#1536]
Why can't it be injected automatically?
 istiod-1-11-2
kubesphere  v3.3.1

kubesphereio/kubefed:v0.8.1

**Comment by mrbobbytables** [comment]
Project is to be archived - closing all issues and PRs

see https://github.com/kubernetes/org/issues/4122 and https://groups.google.com/d/msgid/kubernetes-sig-multicluster/9f8d81d1-07d1-4985-a7bf-d76197deb971n%40googlegroups.com

for details

/close
