### ISSUE TITLE
Federated read access to cluster API objects

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/kubefed#154]
There are some discussions here https://groups.google.com/forum/#!topic/kubernetes-sig-multicluster/47vST8EPHq0

This is also heavily requested feature feature for federation v1 at https://github.com/kubernetes/features/issues/71 .

A basis use case is as follows: How can I use federated control panel to retrieve resources from each cluster? Such as I have cluster1 and cluster2, cluster1 has configmap cm1 and cm2, cluster2 has configmap cm3 and cm4, then I install the federation control manager, how can I use federation controller manager to get all of those four configmaps from the two clusters? Here the sequence is I was creating configmaps in each cluster first, then install the federation control manager.

/cc @quinton-hoole @pmorie @marun

**Comment by marun** [comment]
'heavily requested', yes, but the complexity suggested by the [design document](https://docs.google.com/document/d/1H2BkqSKvoCSifi7c8D2gASSJo20ocIEYDMSfNfcylBc/edit#heading=h.gjdgxs) is considerable.  Given that complexity, it's not clear to me that this feature would be best implemented as a kubernetes api at all - it would really depend on the use cases.  The cases listed in the design document are pretty light compared to the proposed implementations, and I'd like to see more detail to better understand the potential cost that could be justified.

Regarding the use case you have documented, I don't see enough detail to justify the feature.  Why is it necessary to read the config maps?  How current does the view of those config maps need to be?  Are the config maps expected to change, and if so, in response to what?  etc, etc.  It's hard to know whether a feature is necessary if the logic behind it's use isn't well-documented.  There may be simpler/cheaper ways of accomplishing the a given goal, but for that to be discovered the goal needs to be effectively communicated.

**Comment by gyliu513** [comment]
Thanks @marun , perhaps it is not good to take the configMap as examples, but we can take Node as an example.

In a multiCluster, the customer often have the requirement that they want to get all nodes cross clusters from one central point, and check the node status, resource utilization etc.

For the [design document](https://docs.google.com/document/d/1H2BkqSKvoCSifi7c8D2gASSJo20ocIEYDMSfNfcylBc/edit#heading=h.gjdgxs), it is a bit out of date, as the design was based on federation v1, but federation v2 only have a controller manager, and all resources are managed by CRD, we may need to re-consider the design.

One of the solution in my thinking is as follows, perhaps we can define a CRD named as `queryJob` or something else, and the `queryJob` will help call different apiserver to get the requested resources; After the `queryJob` finished, the end user can query the status/result of the `queryJob`  to get the result. If the `queryJob` is for Node, it will return Node status; if for pod, it will return pod status etc.

**Comment by marun** [comment]
What you're describing is an aggregation of state from multiple clusters.  Why do you think that implementing a kubernetes API is the best way to accomplish this goal?  It could as well be an entirely separate application that queries target clusters and computes a view of the state that satisfies the user's requirements.

What those requirements were would depend on the use case, and I still don't see sufficient detail to understand what that use case might be.  'want to get all nodes cross clusters' doesn't indicate what use that information is intended to be used for.

**Comment by gyliu513** [comment]
Thanks @marun , using `queryJob` is just some proposal and I'm open to have more discussion here before we come to a solution. 

> It could as well be an entirely separate application that queries target clusters and computes a view of the state that satisfies the user's requirements.

Can you please show more detail for your proposal here? What do you mean of `separate application`, how does it query target cluster?

Here I also want to share more use cases for the federated read access:

- Inventory for multi cluster.
  - As admin I would like to view an summary of hardware capacity (servers, storage etc) across multiple clusters.
  - As admin I would like to get the total resources consumed by a team across multiple clusters.

**Comment by marun** [comment]
`separate application` is an exercise for you to consider.  I'm not convinced that a Kubernetes-style API is a particularly good fit for implementing a cross-cluster state reporting application, and am encouraging you to explore alternatives.

**Comment by gyliu513** [comment]
@marun For `separate application`, do you mean that I can leverage the kubernetes resources to do the query cross clusters? Such as create a `job`, and use the `job` to computes a view of the state?

Or does the `separate application` means a user defined application for query resources cross cluster?

In my understanding, I think that the `Fderated Read Access` is a very common requirement, seems we need to have the build-in function for this in Federation v2? Comments? Thanks!

**Comment by qiujian16** [comment]
IMHO, an operator of multiple clusters will need to know the info of each cluster. At least, operator should be able to select a cluster, check the capacity and resource usage in this cluster, check if nodes in this cluster is healthy, check if pods in this cluster are all in running state, etc. I do not think operator needs to know any details of a single cluster, but he/she should be able to get some overview info.
