### ISSUE TITLE
Update scripts to use Makefile

### ISSUE THREAD

**Issue by irfanurrehman** [kubernetes-sigs/kubefed#182]
A Makefile was recently updated to trivial stuff like build bins, build image, run tests, etc.
We should ideally reuse the same in the scripts where-ever need be.
Listing, not exhaustive:
1. scripts/deploy-federation.sh
2. scripts/imagebuild.sh
3. scripts/pre-commit.sh

Warning: `make test` fails as of now would need additional steps mapping to `scripts/pre-commit.sh` to make it pass.

**Comment by marun** [comment]
@irfanurrehman Is this issue still actionable?

**Comment by irfanurrehman** [comment]
Yes I see that there still are some items using stuff outside make, which can as well be done using the Makefile.
These "some items" are mostly where building or pushing the image are involved.
