### ISSUE TITLE
Federation V2 Pull Mode

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/kubefed#252]
Open this ticket to trace the work that we are doing for Fderation V2 Pull Mode.

Design: https://docs.google.com/document/d/1JK8VMwx_pqnAChkjhmwoi7u78yu5oKnmgIuw8IM_XsM/edit?usp=sharing

Mail list Discussion: https://groups.google.com/forum/#!topic/kubernetes-sig-multicluster/nI28ORF-j5M 

/cc @marun @pmorie @quinton-hoole @irfanurrehman @xunpan

**Comment by marun** [comment]
I don't think this belongs here, since the work will be performed in a different repo.  Please close.

**Comment by gyliu513** [comment]
In the weekly meeting, I think we have some discussion that we can finish the prototype first, and then check if use a separate repo or federation v2 repo? So here I want to keep this open until we finished the prototype, hope it is OK.
