### ISSUE TITLE
Use cases for federation reprogramming load balancers

### ISSUE THREAD

**Issue by pmorie** [kubernetes-sigs/kubefed#261]
Follow-up from September 12 working group meeting.

A common pattern for deploying services and applications across multiple clusters is to have an externally deployed load balancer that routes requests to different clusters. We are interested in assessing level of interest from the community and specific use-cases that people may have for making federation able to reprogram load balancers; this issue is to collect those use-cases. If you have a use-case in this general area, we would love for you to comment here!

**Comment by gyliu513** [comment]
@pmorie I also posted a message to mail list to get more attention for this issue at https://groups.google.com/forum/#!topic/kubernetes-sig-multicluster/avj0luBwaIg

**Comment by rosskukulinski** [comment]
This was a key goal in our development of [Heptio Gimbal](https://github.com/heptio/gimbal) in partnership with Yahoo Japan's subsidiary, Actapio.  More details [here](https://blog.heptio.com/introducing-heptio-gimbal-bridging-cloud-native-and-traditional-infrastructure-9d6224bece5a).

**Comment by ErikLundJensen** [comment]
Implementation of load balancing across multiple clusters must support the Istio multi-cluster setup.
Having a simple "pod-aware" load balancer in-front will not work for clusters using Istio as the load balancer must have knowledge of the Istio route rules.

**Comment by marun** [comment]
@pmorie Is this issue worth tracking in this repo, given that it is can be an orthogonal concern implemented elsewhere?
