### ISSUE TITLE
Multi Cluster Ingress DNS Status Improvement

### ISSUE THREAD

**Issue by danehans** [kubernetes-sigs/kubefed#324]
I configure a fed ingress tmpl/placement for one of the two clusters and an associated `MultiClusterIngressDNSRecord`, the status of the object displays both clusters:
```
$ kubectl get multiclusteringressdnsrecords -o yaml
apiVersion: v1
items:
- apiVersion: multiclusterdns.federation.k8s.io/v1alpha1
  kind: MultiClusterIngressDNSRecord
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"multiclusterdns.federation.k8s.io/v1alpha1","kind":"MultiClusterIngressDNSRecord","metadata":{"annotations":{},"name":"test-ingress","namespace":"default"},"spec":{"hosts":["nginx.external.daneyon.com"],"recordTTL":300}}
    creationTimestamp: 2018-10-10T20:37:38Z
    generation: 2
    name: test-ingress
    namespace: default
    resourceVersion: "751812"
    selfLink: /apis/multiclusterdns.federation.k8s.io/v1alpha1/namespaces/default/multiclusteringressdnsrecords/test-ingress
    uid: 5370b15b-cccc-11e8-bebb-42010a8a00b8
  spec:
    hosts:
    - nginx.external.daneyon.com
    recordTTL: 300
  status:
    dns:
    - cluster: cluster1
      loadBalancer:
        ingress:
        - ip: 35.227.192.192
    - cluster: cluster2
      loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

I would expect the Ingress DNS controller to use `spec.clusterNames` from `FederatedIngressPlacement` to populate  `status.dns` of `MultiClusterIngressDNSRecord`.

@shashidharatd thoughts?

**Comment by shashidharatd** [comment]
That looks fine to me when `sync controller` is part of the federation control plane. But this feature could also be used independent of sync controller and how it propagates the federated resources. 

when there are no LoadBalancer in a member cluster, the `DNS Endpoint` controller will not produce DNSEndpoint for it. In effect its the same result which we wanted. @danehans, wdyt?

**Comment by danehans** [comment]
@shashidharatd OK, that makes sense. I do think displaying the following can cause confusion for users:
```
    - cluster: cluster2
      loadBalancer: {}
```

I also thought using `spec.clusterNames` from `FederatedIngressPlacement` would be more efficient.

**Comment by marun** [comment]
@shashidharatd Can this issue be closed?

**Comment by guanzo** [comment]
The output is indeed confusing me, what does it mean? My federated ingresses all have ips, but the `IngressDNSRecord` doesn't reflect that.

IngressDNSRecord
```
apiVersion: v1
items:
- apiVersion: multiclusterdns.kubefed.k8s.io/v1alpha1
  kind: IngressDNSRecord
  metadata:
    generation: 1
    name: test-ingress-dns-record
    namespace: default
  spec:
    hosts:
    - test.arc.io
    recordTTL: 300
  status:
    dns:
    - cluster: arc-us-west1
      loadBalancer: {}
    - cluster: arc-us-west2
      loadBalancer: {}
```

Ingress 1 & 2 (with different ips)
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  generation: 1
  labels:
    kubefed.k8s.io/managed: "true"
  name: test-ingress-nginx
  namespace: default
spec:
  rules:
  - host: test.arc.io
    http:
      paths:
      - backend:
          serviceName: hello-kubernetes
          servicePort: 80
  tls:
  - hosts:
    - test.arc.io
    secretName: letsencrypt-secret
status:
  loadBalancer:
    ingress:
    - ip: 35.247.115.141
```

**Comment by marun** [comment]
@guanzo The problem you are reporting appears to be a failure to collect ingress ip's, and does not appear related to this issue.  I think it is likely to represent a support request rather than a bug, and the best place to ask for support is on slack.

**Comment by shashidharatd** [comment]
@guanzo, please file a separate issue. i will look into this issue and reply.
