### ISSUE TITLE
Allow Federated Service DNS to Work without Endpoints

### ISSUE THREAD

**Issue by danehans** [kubernetes-sigs/kubefed#330]
The `serviceBackedByEndpointsInCluster` method of the Service DNS Controller requires a service to have an active endpoint (i.e. running pods) before creating a `dnsendpoint`. This inhibits app deployments that require cross-cluster Service Discovery using DNS. For example, etcd provides a DNS Discovery mechanism that requires A records for each member in the etcd cluster before starting the etcd pods. See the [etcd cluster guide](https://coreos.com/etcd/docs/latest/v2/clustering.html) for more details. I am trying to create a 3-member etcd cluster, where each member is located in a separate Kubernetes cluster. It would be beneficial for the Service DNS Controller to circumvent this check when a particular annotation is provided in the `MultiClusterServiceDNSRecord`.

**Comment by shashidharatd** [comment]
@danehans, the current implementation that service should be backed by endpoints is to provide a form of health check. if there are no endpoints for the service in cluster, that means virtually that service shard should be not routable. A dumb client might do a round-robin among the resolved IP's which cause its request to fail frequently. 

I am thinking, about introducing this flexibility to user. Like we can give an option to user on whether the service should be backed by endpoints or not to write the DNS names.

/cc @quinton-hoole-2

**Comment by quinton-hoole-2** [comment]
Ack.  I don't have time right now to give a thorough response today.  Ping me on slack if it's urgent.

**Comment by quinton-hoole-2** [comment]
From memory the DNS records for the federated service were distinct from those for the per-cluster service.  So the per-cluster services should be able to have their DNS records created as usual (with or without healthy pods behind them).  It's only the federated service records that are contingent on healthy pods.  At least that's how I implemented it in federation-v1.  I've not had time to look closely at what's changed in federation-v2.

**Comment by quinton-hoole-2** [comment]
You can take a look at the logic in federation-v1 and see whether that perhaps helps solve your problem.

**Comment by danehans** [comment]
@quinton-hoole-2 thanks for your input. Your understanding is correct for fed-v2 Service DNS.

@shshashidharatd I can understand why the health check was implemented. From my understanding `DNSEndpoint` is a wrapper for `Endpoint`, which represents a DNS resource record. I can create a DNS resource record in DNS without the IP address being reachable. Some IT workflows create the resource record before the associated endpoint is reachable. What about using `Endpoint` Status instead of requiring the IP to be reachable?

**Comment by marun** [comment]
@shashidharatd Can this issue be closed?
