### ISSUE TITLE
Rename DNS API Group

### ISSUE THREAD

**Issue by danehans** [kubernetes-sigs/kubefed#347]
The group name can be improved upon. #331 is renames the DNS API to `IngressDNS` and `ServiceDNS` and dns exists in the group name. If the DNS feature is no longer intended to be independent, then change the group to dns and the DNS API types to `IngressRecord` and `ServiceRecord`.

**Comment by marun** [comment]
@shashidharatd Do you have any interest in following up on this issue or can it be closed?
