### ISSUE TITLE
Add more logs in RSP for troubleshooting

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/kubefed#355]
Currently, I found the RSP do not have too much logs, so it seems a bit difficult to debug it when customer have issues, it is better add more logs in RSP to improve troubleshooting.

/cc @irfanurrehman can you please add a label as `good-first-issue`? Thanks.

**Comment by johnarok** [comment]
Hi @gyliu513 I can work on this.. can you assign this to me?

**Comment by gyliu513** [comment]
Thanks @johnarok , seems I can only assign to members of federation v2, but I think you can go ahead to create the PR, as I think no one is working on this for now. ;-)

**Comment by gyliu513** [comment]
/remove-lifecycle stale

FYI @nzoueidi
