### ISSUE TITLE
update the CI checks invoking make rather then calling various scripts

### ISSUE THREAD

**Issue by poothia** [kubernetes-sigs/kubefed#364]
Reference:
https://github.com/kubernetes-sigs/federation-v2/pull/361#issuecomment-433169782

**Comment by poothia** [comment]
i am working on this.

**Comment by marun** [comment]
@poothia Is there more to do here or can this issue be closed?

**Comment by poothia** [comment]
@marun yes, a couple of things are remaining in it, I'll try to finish it by next week. and close the issue. thanks.
