### ISSUE TITLE
Differentiating a controller created/updated spec vs a user created/updated spec

### ISSUE THREAD

**Issue by irfanurrehman** [kubernetes-sigs/kubefed#375]
Recently there has been some conversations about the need to differentiate the FederatedXXXX spec created/updated by a controller vs a user created/updated FederatedXXXX spec. The main question that arises is as follows:
- Should a user or a controller get the final say, for example another mechanism which can specify, who has higher powers.

A simple straightforward approach IMHO would be:
Spec could be updated by the user or the controller; if we take k8s precedence, we cannot allow (or disallow) one over the other. Both are treated as API users which could be same or different. In case the users are different, they can only have different access credentials.
We can however benefit from having some info (may be a field in status) which signifies as to who made the last update (or n updates).

This issue is to open discussion around this topic.
cc @kubernetes-sigs/federation-wg

**Comment by pmorie** [comment]
> We can however benefit from having some info (may be a field in status) which signifies as to who made the last update (or n updates).

A couple other thoughts about this, both pure statements of fact:

- This information would already be captured by audit
- If we want to capture user information, it would require a mutating webhook for each type where we wanted to store that information

See: https://github.com/kubernetes/kubernetes/blob/v1.10.0-beta.1/staging/src/k8s.io/api/admission/v1beta1/types.go#L67

**Comment by marun** [comment]
I don't think it is necessary to record status for user-initiated spec changes.  As per the incident that prompted this issue - a user not realizing that spec changes were being made by a controller - there is  potential value in highlighting to a user when spec is being changed by an automated mechanism.  This could be as simple as status fields indicating which controller last updated the spec and when that occurred.
