### ISSUE TITLE
Enable POWER and s390x support for federation

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/kubefed#434]
The current federation only support running on amd64 but no POWER and s390x , we should enable federation can also run on those two platforms to enlarge its adoption.

```
root@gyliu-c11:~# manifest-tool inspect quay.io/kubernetes-multicluster/federation-v2:canary
quay.io/kubernetes-multicluster/federation-v2:canary: manifest type: application/vnd.docker.distribution.manifest.v1+json
      Digest: sha256:248a66787482da0638e1a5500aa0e89e2632436ff288bdc750553399236212a7
Architecture: amd64
          OS: linux
    # Layers: 0
```

FYI @xunpan

**Comment by gyliu513** [comment]
Thanks @marun . I got some requirement in KubeCon Shanghai that someone (Non IBM) want to test federation V2 on POWER and s390x because they have a mixed Kubernetes environment: POWER, x86 and POWER machines, and each architecture in a different cluster.

I told them they can make the x86 cluster as the host cluster and manage POWER and s390x cluster, they agree with this solution for now. But I was thinking, we may still need to consider the case if someone only has POWER clusters or only has s390x clusters, it would be great if we can support those major architectures OOB, so that the end users can download the related arch image from community and do the test directly.

I found that Kubernetes already support those major architectures https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.10.md#server-binaries for every release, can we follow same way as Kubernetes to release federation v2 with different architectures?

**Comment by marun** [comment]
I'm guessing that Kubernetes didn't always support multiple architectures.  It's a mature product now, and we're still in alpha.  However, it might be worth investigating whether moving to test-infra ci infrastructure would give us the means to develop and test against other architectures.  I'm still not convinced it's a useful near-term priority, but we will want to get there eventually.

Given that you work for IBM, can you find out who is behind the support of the architectures in question?

**Comment by gyliu513** [comment]
Yes, +1 that this is not a near-term priority, and we can probably enable this after enter Beta. For now, I can enable POWER and s390x support internal first.

And regarding who is behind the support, as I work for systems group, it is also my responsibility to enable different architecture support for federation.

**Comment by gyliu513** [comment]
It was fixed at https://github.com/kubernetes-sigs/kubefed/pull/1039
