### ISSUE TITLE
<FederatedKind>Override cannot override immutable fields

### ISSUE THREAD

**Issue by sdminonne** [kubernetes-sigs/kubefed#44]
@marun @font @onyiny-ang 
@pmorie FYI

While I was trying to add `Completions` to `FederatedJobClusterOverride` type I realized that with today code it's impossible to override an [immutable field](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/batch/validation/validation.go#L153). 

I see this as a gap. My understanding is that overridden resource should be directly created while looks like they're updated.

Modified code is in this branch: https://github.com/sdminonne/federation-v2/tree/bug_fix

I'm investigating this issue, but it would be great if you may comment.

Thanks

**Comment by marun** [comment]
@sdminonne I think this is an interesting finding.  It will never be possible to override an immutable field, so if an override is to be effective it must exist before object creation.  If an override resource is added after the job template such that the reconciller has already had a chance to create job resources in the underlying clusters, adding an override will result in a validation error.

I don't think there is a technical fix for this.  Would the following documentation be helpful?

 - If per-cluster variation is desired for immutable fields in a federated resource  (e.g. FederatedJob), make sure to create the override resource in advance of template and/or placement resources to ensure that propagation does not take place until the overrides are available.
 - In the event of per-cluster variation not appearing as expected, check the logs for the federated resource for the precence of validation errors received from the affected clusters.

**Comment by marun** [comment]
Adding to v1beta1 to ensure this issue is documented for the release.

**Comment by xunpan** [comment]
Currently, there is only 1 `federatedjobs`. The change to the `immutable` filed also not allowed.
However, currently, controller accept the change with no err message in controller by default.

I think we can doc this behavior and cover it later in webhook implementation. 
@marun

**Comment by marun** [comment]
@xunpan This is also a problem with secrets - it's not possible to change the secret type after creation.  But yes, as per the doc tag we're targeting a doc fix rather than a technical one for beta.
