### ISSUE TITLE
question: vanity URLs for ServiceDNSRecords

### ISSUE THREAD

**Issue by raffaelespazzoli** [kubernetes-sigs/kubefed#456]
per the documentation for ServiceDNSRecords the system will create the following dns records
```
<service>.<namespace>.<federation>.svc.<federation-domain>
<service>.<namespace>.<federation>.svc.<region>.<federation-domain>
<service>.<namespace>.<federation>.svc.<availability-zone>.<region>.<federation-domain>
```
where is the `federation` value taken from?

I get that this naming scheme was devised to prevent name collisions. 
However, people will not want to expose their apps with those names. 
Application endpoints will be available to the end users via vanity url of the form: `<myapp>.<company-domain>`.

It looks like it is possible to create vanity URL DNS record with IngressDNSRecords. 
Is there a plan to support vanity URLs for ServiceDNSRecords?

**Comment by shashidharatd** [comment]
> where is the `federation` value taken from?

`federation` is a logical concept where part of the app could be distributed across clusters (like deployment & services). In most of the scenarios federation name need not be called out explicitly, but for cross cluster service discovery, the discoverer need to know which federation the service belong to as there could be multiple federations hosted by the system.
`federation` is taken from `DomainRef` field of `ServiceDNSRecord` [here](https://github.com/kubernetes-sigs/federation-v2/blob/master/pkg/apis/multiclusterdns/v1alpha1/servicednsrecord_types.go#L27). The Each `federation` is associated with a DNS domain (or DNS Zone). [`Domain`](https://github.com/kubernetes-sigs/federation-v2/blob/master/pkg/apis/multiclusterdns/v1alpha1/domain_types.go#L29) type is a mapping of federation name to federation domain.

> Is there a plan to support vanity URLs for ServiceDNSRecords?

yes, it is supported by [`DNSPrefix`](https://github.com/kubernetes-sigs/federation-v2/blob/master/pkg/apis/multiclusterdns/v1alpha1/servicednsrecord_types.go#L31) field in `ServiceDNSRecord`. right now it just creates a additional DNS record at global level. we will extend it to create vanity URL's at region & zone level also.
