### ISSUE TITLE
external DNS does not work correctly

### ISSUE THREAD

**Issue by xunpan** [kubernetes-sigs/kubefed#464]
I install federation cluster automatically.
After that:
1. install metallb on each member cluster. 
2. create externaldns with coredns as its backend
3. apply federation deployment and service. The service is LoadBalancer type.
4. create ServiceDNSRecord mentioned in [servicedns-with-externaldns.md](https://github.com/kubernetes-sigs/federation-v2/blob/master/docs/servicedns-with-externaldns.md)

After that, I can see 
```
 kind: DNSEndpoint
  metadata:
    creationTimestamp: 2018-11-30T08:20:25Z
    generation: 2
    name: service-test-service
    namespace: test-namespace
    resourceVersion: "40153"
    selfLink: /apis/multiclusterdns.federation.k8s.io/v1alpha1/namespaces/test-namespace/dnsendpoints/service-test-service
    uid: ca056c05-f478-11e8-b4cf-080027023c67
  spec:
    endpoints:
    - dnsName: test-service.test-namespace.test-domain.svc...example.org
      recordTTL: 300
      recordType: A
      targets:
      - 172.168.20.0
      - 192.168.20.0
    - dnsName: test-service.test-namespace.test-domain.svc..example.org
      recordTTL: 300
      recordType: A
      targets:
      - 172.168.20.0
      - 192.168.20.0
    - dnsName: test-service.test-namespace.test-domain.svc.example.org
      recordTTL: 300
      recordType: A
      targets:
      - 172.168.20.0
      - 192.168.20.0
  status:
    observedGeneration: 2
```

However, from dns (coredns for external-dns), I can only see 1 ip address.
```
$ kubectl run -it --rm --restart=Never --image=infoblox/dnstools:latest dnstools
dnstools# dig @10.96.63.24 test-service.test-namespace.test-domain.svc.example.org +short
172.168.20.0
```
**Question 1**: is this expected behavior? when the service on a cluster is down, other cluster IP address will be mapped here?

Then, I unjoin the cluster which has 172.168.20.0 to mimic service down case. I got below information.
```
dnstools# dig @10.96.63.24 test-service.test-namespace.test-domain.svc.example.org +short
192.168.20.0
172.168.20.0
```

**Question 2**: I guess this is not expected because if a cluster is unjoin, the related IP address should be cleaned. Even I wait more than TTL time, all ip addresses are there.

@shashidharatd

**Comment by gyliu513** [comment]
@danehans did you see such issues in your GKE cluster?

**Comment by shashidharatd** [comment]
@xunpan, i can see few problems in your testing.
1. Do you have 2 clusters in your environment? Are they both `minikube` clusters?
2. Looks like the clusters does not have `region` and `zone` labels. (here are the labels. `failure-domain.beta.kubernetes.io/zone` and `failure-domain.beta.kubernetes.io/region`).
3. It could be possible the lb ip's assigned by `metallb` is the same in both clusters, that's why you may be seeing only one ip. (just a guess).

**Comment by danehans** [comment]
@gyliu513 I did not see this issue with gcloud dns.

**Comment by xunpan** [comment]
@shashidharatd 
1. I have 2 cluste4rs with minikube in my environment
2. Even if I do not have region and zone label, the serice "test-service.test-namespace.test-domain.svc.example.org" should have the correct IP values I think
3. I configured metalb with different IP range. So, each cluster assigned different IP
```
      targets:
      - 172.168.20.0 
      - 192.168.20.0 
```
If the correct behavior is that we should have 2 IPs in DNS for this case. I will check related code to see if there has any issues for my case.

**Comment by shashidharatd** [comment]
@gyliu513, you are looking `IngressDNS` documentation, while this issue is for `ServiceDNS`.

**Comment by shashidharatd** [comment]
> Even if I do not have region and zone label, the serice "test-service.test-namespace.test-domain.svc.example.org" should have the correct IP values I think

@xunpan, this case may not be tested. we might need to fix this to work when there are no `zone` and `region` attributes to the cluster.

**Comment by gyliu513** [comment]
Thanks @shashidharatd , I mean the document here https://github.com/kubernetes-sigs/federation-v2/blob/master/docs/servicedns-with-externaldns.md , it is also returning two IP addresses which is different with our test cases append by @xunpan https://github.com/kubernetes-sigs/federation-v2/issues/464#issue-386102460

```
$ dig +short @ns-cloud-b1.googledomains.com. test-service.test-namespace.test-domain.svc.your.domain.name
$CLUSTER1_SERVICE_IP
$CLUSTER2_SERVICE_IP
```

**Comment by shashidharatd** [comment]
@gyliu513, @xunpan, the DNS records may be cached and that is one of the reason why you see some stale records. But if as you said, even after waiting more than TTL seconds both IP's are shown, we need to inspect more on the reason for this. 
- Have you checked the DNS service console (or the external-dns logs) if any directly, to see what happens to the DNS records?

**Comment by danehans** [comment]
> So here my question is when dig return two IP addresses, does both of the services are available? If so, when I access this service, which IP will handle my request? So here, seems dig should return only one IP address?

@gyliu513 yes, both IP's are reachable. Which one I use is based on the name query response of the dns server (gcloud DNS in my example). From my understanding gcloud dns uses multicast routing to respond with the IP closest to the source IP. You can also verify connectivity to both IP's by using the zone/region-level DNS names instead of the global or dnsPrefix (CNAME) record.

**Comment by xunpan** [comment]
I fixed kubernetes-incubator/external-dns#805 and merged.

There is still a new issue logged for obsolete IP address clean up:
https://github.com/kubernetes-incubator/external-dns/issues/808.

I keep this ticket open until external-dns with coredns works correctly.

**Comment by danehans** [comment]
@xunpan have you been able to test PR #805 with federation-v2?

**Comment by xunpan** [comment]
@danehans 
Yes. It works in federation v2 in my environment.

However, there still have issues in external-dns for related case. The obsolete record cannot be deleted. I'm working on it to make it work. This ticket will be cloased if related issue is resolved.
