### ISSUE TITLE
dnsendpoint does not always keep exist

### ISSUE THREAD

**Issue by magicwang-cn** [kubernetes-sigs/kubefed#489]
dnsendpoint is created when servicednsrecord or ingressdnsrecord has been created, but now if deleting dnsendpoint alone, the controller will not create if forever, only created it when servicednsrecord /ingressdnsrecord has been updated.

details:
dnsendpoint service controller just has [servicednsrecord list & watch method](https://github.com/kubernetes-sigs/federation-v2/blob/master/pkg/controller/dnsendpoint/service.go#L37-L45),  but without dnsendpoint's list & watch method

**Comment by magicwang-cn** [comment]
i have created a servicednsrecord:
```
[root@tianzhuo-mcp-1201-jzto ~]# wbkube get servicednsrecord nginx -ntest-namespace -oyaml
apiVersion: multiclusterdns.federation.k8s.io/v1alpha1
kind: ServiceDNSRecord
metadata:
  creationTimestamp: 2018-12-05T12:21:37Z
  generation: 1
  name: nginx
  namespace: test-namespace
  resourceVersion: "124609"
  selfLink: /apis/multiclusterdns.federation.k8s.io/v1alpha1/namespaces/test-namespace/servicednsrecords/nginx
  uid: 4fde3771-f888-11e8-831f-0255ac100014
spec:
  domainRef: test-domain
  recordTTL: 300
status:
  dns:
  - cluster: add-tz06796
    loadBalancer:
      ingress:
      - ip: 10.154.78.40
    region: southchina
    zone: az1.dc1
  - cluster: test111348532
    loadBalancer: {}
    region: southchina
    zone: az1.dc1
  domain: extian.club
```
and federation-v2 will create a dnsendpoint:
```
[root@tianzhuo-mcp-1201-jzto ~]# wbkube get dnsendpoint service-nginx -ntest-namespace -oyaml
apiVersion: multiclusterdns.federation.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  creationTimestamp: 2018-12-05T12:21:37Z
  generation: 4
  name: service-nginx
  namespace: test-namespace
  resourceVersion: "124630"
  selfLink: /apis/multiclusterdns.federation.k8s.io/v1alpha1/namespaces/test-namespace/dnsendpoints/service-nginx
  uid: 4fdfa0f2-f888-11e8-831f-0255ac100014
spec:
  endpoints:
  - dnsName: nginx.test-namespace.test-domain.svc.az1.dc1.southchina.extian.club
    recordTTL: 300
    recordType: A
    targets:
    - 10.154.78.40
  - dnsName: nginx.test-namespace.test-domain.svc.extian.club
    recordTTL: 300
    recordType: A
    targets:
    - 10.154.78.40
  - dnsName: nginx.test-namespace.test-domain.svc.southchina.extian.club
    recordTTL: 300
    recordType: A
    targets:
    - 10.154.78.40
status:
  observedGeneration: 4
```

but if i delete the dnsendpoint:
```
wbkube delete dnsendpoint -ntest-namespace
```

it's suggested that the dnsendpoint will be created again, right? but it will not.

the reason is that the dnsendpoint controller just care about the servicednsrecord's change, but not cat about the dnsendpoint. maybe this has another consideration?

**Comment by xunpan** [comment]
I reproduced this issue in my environment. 
I think this is an issue. Controller create dnsendpoint and should make sure it is there.

I can work on this. @shashidharatd, what do you think?

**Comment by shashidharatd** [comment]
I am not sure, whether recreating the dnsendpoint when manually deleted is the right choice. As delete action on this object could be controlled by something like rbac policy. My concern is to not put additional overhead on the controller to watch these resources. if we can achieve this without much overhead, please go ahead.

**Comment by shashidharatd** [comment]
Another alternative than to watch `DNSEndpoint` could be to use `resync` period in the ServiceDNSRecord informer [here](https://github.com/kubernetes-sigs/federation-v2/blob/master/pkg/controller/servicedns/controller.go#L124)

**Comment by magicwang-cn** [comment]
other issue is that when Domain is changed, the `dnsendpoint` is also not changed correctly.

**Comment by xunpan** [comment]
@magicwang-cn It cannot reproduce your issue.

When `Domain` is changed, the `dnsendpoint` is updated accordingly in my environment. In this case, even `dnsendpoint` was deleted before the change. It will be created again.

If it can reproduce in your environment, please more show details.

**Comment by magicwang-cn** [comment]
@xunpan see this: https://github.com/kubernetes-sigs/federation-v2/issues/489#issuecomment-445268251 

does the new version fix this issue?

**Comment by xunpan** [comment]
@magicwang-cn 
You mentioned 2 issues in this ticket here:
1. remove dnsendpoint
   it is not created automatically without any operation. Yes. I reproduced it before. As I append in comments before.

2. Domain is changed but dnsendpoint is not changed
   I cannot reproduce this issue. And you just show no information for details.
