### ISSUE TITLE
Lack of conditional preparation of the cross-cluster service discovery

### ISSUE THREAD

**Issue by magicwang-cn** [kubernetes-sigs/kubefed#514]
**use case:**
![image](https://user-images.githubusercontent.com/7587313/49926133-d5ab0e00-fef5-11e8-8e34-51d5db5d0b30.png)

**details:**
A -> B maybe includes cross-cluster service access, and use `b.ns.federation` domain name to do the service discovery. first, localdns(kubedns/coredns) will check if the local cluster has B's service, if so, it will use the local cluster's B service, if not, it is the upstream dns server's responsibility to resolv the domain name.

**need todo:**
so the localdns should be configed with federation configuration. but now, there is nowhere to do the configuration work. maybe we should consider somewhere to do the work? There are some aspects to consider：
- who will do the configuration work,  kubefed2, the specific controller or document to user itself to do the work. In my opinion, we should keep the localdns configuration corrent, right?
- the configuration work's result(failed or success) should effect the federation controller plane or the cluster's condition, because if it is failed, the cross-cluster service discovery is unavailable
- once we do the unjoin work, we should recover the localdns's configuration
- ...

any idea about this?
@shashidharatd @marun

**Comment by marun** [comment]
iirc multicluster dns records handle the case of delivering traffic to a local service if available, and otherwise to the same service in another cluster if not.  I'll leave it to @shashidharatd and @font to confirm.

**Comment by magicwang-cn** [comment]
@marun yes, you are right. but there are still something need to do:
so the localdns should be deployed with federation configuration. but now, there has nowhere to do the configuration work. maybe we should consider somewhere to do the work? There are some aspects to consider：

who will do the configuration work, kubefed2, the specific controller or document to user itself to do the work. In my opinion, we should keep the localdns configuration corrent, right?
the configuration work's result(failed or success) should effect the federation controller plane or the cluster's condition, because if it is failed, the cross-cluster service discovery is unavailable
once we do the unjoin work, we should recover the localdns's configuration
...
