### ISSUE TITLE
Support federating resources to a different/mapped namespace

### ISSUE THREAD

**Issue by csrwng** [kubernetes-sigs/kubefed#579]
**What would you like to be added**:
Allow annotating a namespace such that its contents federate to a different target namespace

**Why is this needed**:
In the use case of Openshift Hive we are planning to distribute system configuration to our target clusters using Federation. End users of Hive will create templates/placement resources in the Hive cluster that we will then federate to clusters they create through Hive. The issue is that we do not necessarily want to grant end users access to system namespaces (kube-* or openshift-*) in the Hive cluster. Ideally they'd have regular namespaces that target the system namespaces on their created clusters. 

/kind feature

**Comment by marun** [comment]
A foundational tenant of fedv2 is the 1:1 mapping of federated resources to their non-federated equivalents.  The implementation you are proposing would violate that tenant.  I encourage you to formulate the use case you are trying to address cleanly, without a specific implementation in mind.  I think that would make it more likely that a solution could be found that respected the 1:1 mapping.

**Comment by csrwng** [comment]
Our use case  is that we have a central cluster that multiple users will use to create and manage their own clusters. Managing those clusters includes distributing configuration resources to them (mainly 4.0 operator configs). These configs live in usually privileged namespaces of the target clusters. Ideally, we would like the users of the central cluster to not have access to those same namespaces in the central cluster.

**Comment by pmorie** [comment]
I talked with @csrwng offline about this and we're going to explore addressing this with RBAC instead of a feature request; will comment with the outcome of that exploration later.
