### ISSUE TITLE
Watch FederatedClusters and cluster-registry Clusters in any namespace

### ISSUE THREAD

**Issue by csrwng** [kubernetes-sigs/kubefed#580]
**What would you like to be added**:
Allow the federation controllers to watch/update FederatedClusters in any namespace and not just a single Federation namespace. Similarly allow cluster registry resources to live in any namespace and not just a single designated cluster registry namespace.

**Why is this needed**:
Just as FederatedClusters in Federation v2, OpenShift Hive's ClusterDeployment resource is namespaced. Namespaces will be used to manage RBAC for the different users of the Hive cluster. Ideally, the FederatedCluster resource, related secret and ClusterRegistry cluster can live in the same namespace as their corresponding Hive ClusterDeployment so they can be managed together.

/kind feature

**Comment by marun** [comment]
This issue appears similar to #526.  As per commentary on that issue, federated clusters are currently in a single namespace to ensure that a cluster name referenced in a placement directive can be unambiguous.  If federated clusters were allowed to exist in multiple namespaces, it would be necessary to implement a way to either maintain that characteristic (e.g. webhook validation ensuring system-wide uniqueness of a cluster name) or allow placement directives to accept namepspace-qualified cluster names.

**Comment by marun** [comment]
It should be possible to allow clusters to be defined in any namespace by ensuring references to those federated clusters are namespace-qualified.
