### ISSUE TITLE
Allow multiple namespaces to be part of the same federation

### ISSUE THREAD

**Issue by raffaelespazzoli** [kubernetes-sigs/kubefed#614]
**What would you like to be added**:

I'd like the ability to specify multiple namespaces to be part of the same federation. So instead of a federation scoped to one namespace, we would have the ability to specify a namespace selector with the contract that namespaces selected by that selector are to be federated (i.e. replicated to the federated clusters).
We can assume that if multiple federation control planes are running in the same cluster, the set of namespace identified by the namespace selectors will not be overlapping.

**Why is this needed**:

Allows for more flexible and dynamic configuration. Today in order to solve for the described scenario, one would have to create  a federation control plane per namespace and watch for the creation/removal of namespaces consequently add/remove the corresponding federation control plane.

/kind feature

**Comment by marun** [comment]
I think this requirement duplicates what is captured by the first bullet of #612.  If you agree, please close this issue.

**Comment by xunpan** [comment]
I think this is not duplicated with #612. 

This ticket asks for a federation control plane for a set of namespaces. It also asks for multiple federation control planes installation for different namespace sets.

#612 is only prefer cache optimization. Though it may limit namespace by selector to a federation control plane, it does not mention multiple control planes case.

**Comment by marun** [comment]
@xunpan I think this issue is only requesting the implementation of option 1 of #612. So long as a control plane can be limited to a subset of available namespaces, there is no implementation required to support running multiple control planes that target mutually-exclusive subsets of namespaces.

**Comment by raffaelespazzoli** [comment]
@marun @xunpan thanks for considering this request. Yes the objective is to be able to run multiple federations the same cluster targeting non overlapping namespace sets identified via label selector.
And this is where my knowledge of federation is blurry and probably why my message was a bit confusing. Why do I actually need multiple federation control planes? Can't a federation control plane manage multiple federations? Ideally the federation control plane listen on a CRD and if multiple CRs exists for that CRD it should be able to manage them.
Is the federatedcluster CRD what identifies a federation? Can I have multiple of them managed by the same control plane?

**Comment by marun** [comment]
I don't think a federation control plane that can manage multiple federations is justified.  Implementing such a change would incur an implementation cost and maintenance burden, and the same effective result can be achieved with the current code by running multiple control planes (assuming support for label selection of target namespaces).

**Comment by marun** [comment]
A `FederatedCluster` resource identifies a cluster that is a member of a federation.  There is no single resource defining a 'federation'.  Instead, a 'federation control plane' consists of the following resources (in the host cluster unless otherwise identified):
 
- A `StatefulSet` running the controller manager
- The set of`FederatedCluster` resources (and their related `Cluster` and `Secret` resources) residing in the same namespace as the controller manager
- The service account and rbac roles and bindings allowing the controller manager to access federated resources
- The service accounts and rbac roles and bindings in member clusters
