### ISSUE TITLE
Preserve local cluster changes to status, annotations and labels

### ISSUE THREAD

**Issue by HaraldGustafsson** [kubernetes-sigs/kubefed#633]
**What would you like to be added**:
Preserve local cluster changes to status, annotations and labels.

I did a simple test with a CRD `zzz`, did `kubefed2 enable zzz`. The federated CRDs where created. I then created a `FederatedZzz` resource which is federated to my other cluster. But when I update status, annotations or labels in the other clusters resource of the `zzz`type it is replaced by the template (although briefly visible). I make the patches using `kubectl` at the moment and not using any controller.
**Why is this needed**:
I was expecting that a local change to at least the status was preserved, how is otherwise a local controller supposed to store status for a CRD? It would also be useful to preserve local cluster added annotations and labels.

Am I using federation correctly or can this be accomplished already today?

/kind feature

**Comment by marun** [comment]
Federation's sync controller never sets status.  I suspect you're running into the lack of support for patching status via kubectl: https://github.com/kubernetes/kubernetes/issues/67455

As to retaining non-status local changes to federated resources, that is not possible.  Federation supports setting labels and annotations in the template and overrides, and has no way of knowing which labels and annotations were locally set and need to be retained in member clusters.

If you can explain the use case for a local controller setting labels or annotations, I may be able to assist you in accomplishing that goal in a federation-compatible way.  Feel free to describe it here or reach out to me via the email address in my github profile (since I don't see you on kube slack and registration is restricted right now).

**Comment by HaraldGustafsson** [comment]
I noticed I had forgotten the subresource/status in the CRD, that's why I could set the status using kubectl but it is part of the object and hence then also will be replaced. But just after noticing I got interrupted and did not manage to update the issue before your response.

About the labels/annotations. The thing is that our clusters will be used in an environment with potential long network partitions between clusters, but local users/services will likely need to update resources during such partitions. I'm struggling with a design that during normal conditions we can use the preferred central control, but during network partitions allow local changes. Then when normal conditions again, feed any local changes to the federated template. My thinking was that local changes could be patched in as annotations or labels, and the controller would prefer annotations over the real spec. This is a step on the way for a true two-way sync merge.

**Comment by marun** [comment]
fedv2 propagation assumes control over federated resources in member clusters, including annotations and labels.  Changing that would be non-trivial, let alone something like two-way merging.  

If you require central control combined with local control in the event of partition, have you considered a gitops model?  Local git repos containing cluster configuration could be synchronized with a master repo, and conflicts could be resolved as needed.  A local agent like kube-applier would apply the configuration to a cluster. 

Using gitops wouldn't necessarily require foregoing the federation api.  Today fedv2 only supports active (centralized) reconciliation, but there has been a lot of discussion of adding support for 'push' reconciliation.  Push reconciliation would rely on a controller that read the federation api and generated canonical kubernetes configuration into a git repo that could be used in a gitops deployment.

**Comment by HaraldGustafsson** [comment]
Interesting that there are discussions of combination between gitops and the federation api. Because with the tools available today you would loose the ability to easily schedule over several clusters with gitops. At least to my understanding. Is there any discussion of more than one federation host cluster as well?

**Comment by marun** [comment]
There have been recurring requests to implement a multi-cluster HA solution for federation ([most recently on this issue](https://github.com/kubernetes-sigs/federation-v2/issues/636).  Enabling reliable HA of kubernetes APIs, though, would be very expensive.  It would require constantly replicating a consistent snapshot of API state between two or more clusters and figuring out how to reliably perform leader election across clusters.   A much simpler solution would be of the disaster recovery variety - reconstitute the federation control plane on another host cluster from a recent snapshot .  There might be a period of downtime in which federation would not be capable of making changes to member clusters, but workloads in member clusters would continue to run.  If a gitops model of applying configuration were used, reconciliation at the local level would be unaffected.

**Comment by marun** [comment]
@HaraldGustafsson Annotations (as well as finalizers) are preserved as of #1010.  Do you have a compelling reason to retain labels given that they are intended to be declarative vs set by automation (as was the case with annotations and finalizers)?

**Comment by HaraldGustafsson** [comment]
I think annotations is enough, the only reason left for also supporting labels would be for filter support. For example locally label resources to get an overview of locally extended/annotated resources, but maybe that could be found in another way.
