### ISSUE TITLE
federation controller disaster recovery Support

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/kubefed#636]
**What would you like to be added**:
Currently, we can only have one host cluster, but if the host cluster goes down, then the federation controller will also goes down, and then the federation will not work.

**Why is this needed**:
It is better to enable the federation controller can support disaster recovery mode, such as we can introduce active-passive mode for federation controller, if the primary controller goes down, then another controller will take over to manage all of the clusters.

/kind feature

/cc @marun @kubernetes-sigs/federation-wg

**Comment by marun** [comment]
@gyliu513 Does this duplicate #402?

**Comment by gyliu513** [comment]
@marun those two issues are different I think. For #402 , it is claiming we want to deploy multiple federation controllers in **one** cluster, but if the cluster goes down, no matter how many federation controllers, the federation will not work; But my case is for **multiple** clusters, if the cluster which is hosting the federation controller goes down, then we should have another cluster take over and try to become another federation controller.

**Comment by marun** [comment]
I think it's important to note that the federation control plane not running or not being able to reach one or more member clusters does not affect running workloads in member clusters.   'the federation does not work' is only an indication that reconciliation will not be possible for the duration of downtime.

**Comment by gyliu513** [comment]
@marun Yes, `federation controller` goes down will not impact running workload on member clusters, but the problem here is the end user will not able to deploy new federation resources or query resources.

**Comment by gyliu513** [comment]
So the basic requirement is that we may want to deploy federation controller to multilple Kubernetes clusters, and when one cluster is down, the federation controller can be smoothly switched to another cluster.

**Comment by marun** [comment]
As per my revised comment above, I think a most reasonable goal than the one originally proposed for this issue could be documenting the procedure to reconstitute the API resources of a federation control plane on another cluster from a recent snapshot.  I think that would more accurately be described as a disaster recovery strategy than HA.  I'm not sure it should be in scope for fedv2 to implement an end-to-end solution to handle the switchover, though.  Disaster recovery strategies tend to be very environment-specific.

**Comment by gyliu513** [comment]
@marun how about introduce kind of federation-v2-operator as controller on multiple federation controllers in different clusters, and do failover for federation controller on each cluster?

**Comment by marun** [comment]
@gyliu513 How would that solve the problem of synchronizing api state?  Are you suggesting that this new master control plane be the API that users would access, and that they would work with federated federated types?

**Comment by gyliu513** [comment]
@marun my thinking is that enabling the `federation-v2-operator` in each cluster to be synchronized periodically, and once the primary host cluster down, `federation-v2-operator` can select a new host cluster without data loss (There maybe some data loss in a small time-window before data sync up).

**Comment by marun** [comment]
@gyliu513 Your last comment would seem to confirm my assertion that you're talking about disaster recovery and not HA.  I suggest revising this issue accordingly.

**Comment by marun** [comment]
Related: https://github.com/kubernetes-sigs/federation-v2/issues/450
