### ISSUE TITLE
Move federation-v2 from kubernetes-sigs to sigs.k8s.io under GOPATH

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/kubefed#697]
**What would you like to be added**:
As discussed in 20190327 meeting, we want to replace `kubernetes-sigs` to `sigs.k8s.io` for the url of federation-v2, like [cluster-api](https://github.com/kubernetes-sigs/cluster-api) and its related cloud providers.

/cc @marun @shashidharatd @kubernetes-sigs/federation-wg 

**Why is this needed**:
Keep consistent with [cluster-api](https://github.com/kubernetes-sigs/cluster-api) and other projects under kubernetes-sigs org.

/kind feature

**Comment by marun** [comment]
@shashidharatd Why does this need to be a beta1 priority?  This is an internal detail that wouldn't impact consumers of a released version of federation.

**Comment by shashidharatd** [comment]
@marun, its not a priority, but a nice to have before beta. we shall remove it from milestone if it is a blocker.

**Comment by font** [comment]
This has been addressed by issue #860.
