### ISSUE TITLE
FederatedClusters should indicate the scope of their join

### ISSUE THREAD

**Issue by marun** [kubernetes-sigs/kubefed#709]
Currently `kubefed2 join` results in a `FederatedCluster` and associated secret containing credentials for the service account used to access the member cluster.  There is no way of determining the join mode (namespace-scoped vs cluster-scoped) of a given cluster (at least those joined by a tool like `kubefed2`), and it would likely be a useful detail to be able to expose to the user.  

cc: @pmorie @xunpan 

/kind feature

**Comment by xunpan** [comment]
@marun
We've already had `limitedScope` in `FederationConfig`. Customer can get `FederatedClusters` and know these clusters are in namespaced or cluster-scoped federation based on `FederationConfig` information.

What do you think to make it in `FederatedCluster`?

**Comment by marun** [comment]
@xunpan As per the 'awaiting more evidence' priority, there is no requirement to implement this feature.  As we're experimenting internally with disaster recovery, it occurred to me that someone might attempt to migrate a 'FederatedCluster' between deployments, and if the deployment was of a different scope the behavior could be unexpected (i.e. migrate a namespace-scoped cluster to a cluster-scoped deployment).  If the scope of the join of the `FederatedCluster` was indicated, then it could simplify troubleshooting (vs having to inspect the permissions of the service account in the member cluster).
