### ISSUE TITLE
Request to break relevant sections from User Guide out into separate installation docs module

### ISSUE THREAD

**Issue by abrennan89** [kubernetes-sigs/kubefed#728]
**What would you like to be added**:
We should split the sections in the user guide up until 'Operations' into a separate doc for installation docs, and then just provide a link as/if needed to this.

**Why is this needed**:

- As the document grows it will become unwieldy to have just a single user guide, modules of documentation make it easier to find content a user needs than searching through a monolith.
- I've noticed this already in working with our team to plan docs updates for releases.
- Good opportunity to thoroughly review the existing content and ensure that required dependencies are covered.

**Somewhat related issues / PRs for my own reference**:
- https://github.com/kubernetes-sigs/federation-v2/pull/727 [only helm deployment supported]
- https://github.com/kubernetes-sigs/federation-v2/pull/451 [changes to user guide examples?]

I am happy to work on this but raising the issue first for visibility.

/kind feature

**Comment by shashidharatd** [comment]
@abrennan89, Thank you for taking this up. much appreciated.

**Comment by abrennan89** [comment]
PR added; https://github.com/kubernetes-sigs/federation-v2/pull/730
