### ISSUE TITLE
Unjoin should be idempotent

### ISSUE THREAD

**Issue by marun** [kubernetes-sigs/kubefed#745]
Currently, attempting to unjoin an already-unjoined cluster will result in error messages as unjoin tries and fails to remove resources that do not exist in the cluster targeted for unjoin.  Similar to join, unjoin should default to not reporting errors of missing resources unless provided with an argument like `--error-on-missing`.

/king bug

**Comment by xunpan** [comment]
I think `--force` should be removed if we support `unjoin` operation in idempotent way. 
Because no matter what happens (no `--error-on-missing`), `unjoin` always make related resources removed. @marun

**Comment by marun** [comment]
@xunpan SGTM

**Comment by xunpan** [comment]
Logic here should be:
1. if host cluster client failed, return false.
2. if unjoining cluster client failed, contrinue to operate on host cluster.
3. if error on missing, return false if any federation related `resource` does not exists.

@marun, is it only for logic equivalent of `join` or it is useful for `--error-on-missing`? Unjoin should clean resource as many as it can. What is the use case for `--error-on-missing`?

**Comment by marun** [comment]
@xunpan Maybe the only use-case is pathological testing - ensuring that the resources that were expected to be present were actually present.  If that is true, then I don't see a good reason to expose it to the user as a flag.
