### ISSUE TITLE
kubefedctl should indicate the referencing FederatedTypeConfig when generating for a duplicated plural name 

### ISSUE THREAD

**Issue by marun** [kubernetes-sigs/kubefed#747]
As per #746, it is possible to attempt to enable a type with a plural name that is already in use by another type.  When that occurs, it would be helpful if `kubefedctl` could report the name of the  `FederatedTypeConfig` representing the already enabled type that the attempted enable was conflicting with.

**Comment by xunpan** [comment]
@marun 
Did you mean reject this case?

e.g.
```
$ kubefedctl enable deployments.extensions
customresourcedefinition.apiextensions.k8s.io/federateddeployments.types.kubefed.k8s.io updated
federatedtypeconfig.core.kubefed.k8s.io/deployments.extensions created in namespace kube-federation-system
```
This is wrong, we should report it is already federated for `deployments.apps` and suggest to use another federated-group for it.

**Comment by marun** [comment]
@xunpan I question you pose is related but different, and I've filed #988 to address it.

**Comment by xunpan** [comment]
/assign
Let me try to check related conditions as a whole
