### ISSUE TITLE
Simplify placement

### ISSUE THREAD

**Issue by marun** [kubernetes-sigs/kubefed#75]
Resource placement currently requires resource-specific placement.  To be propagated to a given cluster, a template must have that cluster listed in its associated placement resource, and the containing namespace must also have a placement resource listing that cluster.

It would be desirable to make namespace-based placement the default.  If the placement for a namespace specified a given cluster, all federated resources in that namespace would be propagated to that cluster if resource-specific placement was not present.

Where more fine-grained control is required, resource-specific placement could be employed.  Where both namespace and resource-specific placement resources existed, placement could be determined either additively (namespace clusters + resource clusters) or exclusively (resource clusters only).  Both namespace and resource-specific placement resources could indicate via a boolean whether propagation should be restricted (e.g. `propagate: true|false`).

**Comment by marun** [comment]
Moving out of v1alpha1, this will be targeted at a subsequent alpha release.

**Comment by shashidharatd** [comment]
@marun, this feature is implemented and available. is there something pending for this, otherwise shall we close this issue?

**Comment by marun** [comment]
@shashidharatd I don't believe this feature is implemented yet.  The only option for placement is resource-specific.
