### ISSUE TITLE
Switch to go modules for dependancy management

### ISSUE THREAD

**Issue by poothia** [kubernetes-sigs/kubefed#778]
switching to go modules for depndancy management

REF:

https://github.com/liggitt/gomodules/blob/master/README.md

https://github.com/kubernetes/enhancements/blob/master/keps/sig-architecture/2019-03-19-go-modules.md

**Comment by marun** [comment]
I don't think this is something we want to tackle until after v1beta1.

**Comment by poothia** [comment]
seems logical.

**Comment by bharaththiruveedula** [comment]
@marun is this issue still valid? If yes, can I work on this?

**Comment by poothia** [comment]
@bharaththiruveedula yes, this issue is still valid you can take it if you want.
