### ISSUE TITLE
`kubefed2`: Add command(s) that report control plane state

### ISSUE THREAD

**Issue by marun** [kubernetes-sigs/kubefed#782]
The implementation of `FederationConfig` exposes the configuration of a federation controller manager, and suggests adding a command that outputs aggregated details of the control plane:

```
$ kubefed2 info --federation-namespace=myns
Configuration 
==========
Registry Namespace: myns
Scope: Namespaced
Leader Election Timeout: 5s
...

Federated Type Config
=====================

NAME              PROPAGATION_ENABLED   SYNC_CONTROLLER_RUNNING  
deployments.apps  true                  true
secrets           true                  false

Member Clusters
============

NAME        READY
cluster1    true
cluster2    false

```

Or maybe it makes more sense to have individual commands for each type of config (e.g. `get config`, `get clusters`, `get ftc`)?

/kind feature

**Comment by font** [comment]
+1
We could even do both and the aggregated info command can re-use code from the individual commands.

**Comment by draveness** [comment]
I could take a look at this issue and open a PR. :)

**Comment by marun** [comment]
@draveness I think we'll want to flesh out our intention before you go ahead with implementation.

**Comment by draveness** [comment]
> @draveness I think we'll want to flesh out our intention before you go ahead with implementation.

👍

**Comment by marun** [comment]
Being able to introspect on a control plane would seem like a feature worth implementing for beta2 to ensure an easy way of checking control plane health and configuration.
