### ISSUE TITLE
webhook for federation

### ISSUE THREAD

**Issue by xunpan** [kubernetes-sigs/kubefed#794]
**What would you like to be added**:
add webhook to avoid manually change the read only content for federation controller
 E.g. `ConfigurationConfig` scope part does not need to be changed after it is set during deployment. 

It will be used to validate related values in setting federated related resources.

**Why is this needed**:

/kind feature

**Comment by marun** [comment]
@xunpan I'm not sure this should be a near-term priority given how many items remain in [v1beta1](https://github.com/kubernetes-sigs/federation-v2/milestone/4).  I don't think shipping a webhook will be trivial given the certificate management it will require.

**Comment by xunpan** [comment]
This is logged for long term trace .

**Comment by xunpan** [comment]
Kubefed have webhook already. Close this.
