### ISSUE TITLE
use namespace from system in

### ISSUE THREAD

**Issue by xunpan** [kubernetes-sigs/kubefed#795]
**What happened**:

**What you expected to happen**:
It would be desirable to set federation-namespace via the config mechanism if scope == Namespace.

Follow up action for https://github.com/kubernetes-sigs/federation-v2/pull/771

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`)
- Federation version
- Install method (helm vs script)
- Install configuration (namespaced vs cluster-scoped)
- Others

/kind bug

**Comment by marun** [comment]
The federation namespace is implicitly the same namespace that the controller manage is running in.  The only case where it should be necessary to manually specify `--federation-namespace` is if running outside of a cluster (i.e. for testing), and even then the namespace could be defaulted to the namespace of the service account the controller manager is using to authorizing itself to the API server.

**Comment by pmorie** [comment]
I'm not sure that I understand what the value proposition of making this change would be - since you can get the same behavior in-cluster by setting the CLI argument from downward API env and just set it explicitly if you want to run the controller outside the cluster.

Am I missing something?

**Comment by marun** [comment]
@pmorie This change removes the need to define the env var via the downward api and use it in as an argument.  Running outside the cluster doesn't change (`--kubefed-namespace` must be specified).
