### ISSUE TITLE
`kubefed2 federate` should support input from disk

### ISSUE THREAD

**Issue by marun** [kubernetes-sigs/kubefed#800]
Current `kubefed2 federate` only takes converts resources sourced from a Kubernetes API.  A frequent request has been to source resources to federate from yaml.  A simple implementation could be `kubefed2 federate -f myresources.yaml`, without output automatically being to stdout as converted yaml.

**Comment by irfanurrehman** [comment]
How elaborate is the suggested need of this functionality before beta. For an example, kubectl can scan directories and read json or yaml files with multiple resources in each files. Should we support something similar or a single file input (say --filename) should suffice for now.

**Comment by marun** [comment]
This has been implemented for v0.1.0.
