### ISSUE TITLE
Cluster controller errors should be logged as events on clusters where possible

### ISSUE THREAD

**Issue by marun** [kubernetes-sigs/kubefed#809]
/kind feature

**Comment by draveness** [comment]
I'd like to take this.

**Comment by xunpan** [comment]
@draveness 
Do you still working on this? Any progress?

**Comment by draveness** [comment]
> @draveness
> Do you still working on this? Any progress?

Sorry, I'm not. I thought we would work on this after 0.1.0 released, and please feel free take it over.
