### ISSUE TITLE
Beta APIs should be validated

### ISSUE THREAD

**Issue by pmorie** [kubernetes-sigs/kubefed#812]
**What would you like to be added**:

We currently do not have any API validations for the core API resources (FederatedTypeConfig, etc). We should add a validating webhook for APIs we are going to elevate to beta so that we can meet the normal user expectation of not allowing invalid data into APIs.

**Why is this needed**:

Users have a baseline expectation that APIs are validated, which is especially important for beta APIs to ease the challenges that might be associated with future API changes. For example, it is much easier to make a field optional than to make it required. Without a validation to prevent invalid empty fields, for example, once we take an API to beta without validations it will be hard to add them without breaking user expectations.

/kind feature

**Comment by pmorie** [comment]
I should note that I mean this statement to apply only to the APIs of _federation_ - not to the APIs that we generate. Validation for generated APIs should be thought of as a different issue.

**Comment by marun** [comment]
Closing in favor of specific issues targeting the beta resources: #908, #909, and #916
