### ISSUE TITLE
Replace dynamic client usage with controller-runtime's generic client

### ISSUE THREAD

**Issue by font** [kubernetes-sigs/kubefed#83]
The current dynamic client in use has now been deprecated. We need to update the client-go vendored dependency and update the dynamic client to use the new version. See https://github.com/kubernetes/kubernetes/pull/63446 for more details.

**Comment by marun** [comment]
This will likely depend on upgrading all dependencies to match kube 1.11, not just client-go.

**Comment by marun** [comment]
The dynamic client has been superceded by the generic client defined by the `controller-runtime`:

https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/client/example_test.go
