### ISSUE TITLE
How should federate resource pick type info for conflicting types [kinds exposed in multiple groups]

### ISSUE THREAD

**Issue by irfanurrehman** [kubernetes-sigs/kubefed#833]
There is a possibility that same `target kind` exists across multiple groups. For example k8s core type `deployments` is available in both `extensions` and `apps`. 
This poses a problem while federating a resource (especially namespace with content), such that the same resource could be queried against all exposed group and versions (with internal API conversions). So effectively a single resource results in multiple resources in a `get me all resources in this namespace` query. 
We have chosen a strategy of skipping `extensions` considering it an older/going to be deprecated type for all such `kinds` for k8s core `API Resources`.

There could be other resources, especially CRDs where a `kind` which intentionally chooses do so, for which a strategy needs to be put in place. 
There are following possible options:
1. Error out when ever multiple API resources are found across different groups for same currently unknown `kind`. (This can be implemented right now).
2. Provide and option to resolve the above error by:
- Letting the user skip API Resource ( say by `--skip-resources`) such that the duplicate resource which is unwanted is skipped.
- Let the user choose a strategy (say by `--multi-resource-skip-strategy`=`choose-installed-typeconfig`) by picking the specific resource group version if a typeConfig for that is installed.

**Comment by irfanurrehman** [comment]
There is also a possibility that a `kind` under multiple `groups` is not meant for the same resource (implying different CRDs). This is the scenario handled right now in #741 by treating all `group resources` except those relevant to `extensions` as different resources.

**Comment by marun** [comment]
As per our discussions, I think erroring out is an acceptable solution and one that requires minimal effort to implement.  So long as a target type is enabled prior to attempting to convert a resource of that type with `kubefedctl federate`, conversion should work fine.  If the type of a resource intended for conversion has not been converted, and enabling with the default group would result in a conflict, the resulting error can indicate that the type needs to be enabled with a non-default group.
