### ISSUE TITLE
Documentation: integration with single-cluster controllers

### ISSUE THREAD

**Issue by michaelfig** [kubernetes-sigs/kubefed#838]
**What would you like to be added**: Documentation for how to integrate federation with useful controllers that are not aware of Federated resources, like [cert-manager](https://github.com/jetstack/cert-manager), [Weave Flux](https://github.com/weaveworks/flux), and similar systems that update non-Federated resources based on external state.

I am working on one particular solution at https://github.com/michaelfig/k8s-copier, but it is in early stages (and is a broken ball of mud right now, intended to be refactored once I get the basics working).  I'm documenting my goals in the README, to explain the model I intend to use.  Basically, the federation host cluster is designated to be the source for the controller changes (such as cert-manager generating a new Secret for a Certificate), and k8s-copier uses the generated host-cluster resources to update Federated resources, which federation then pushes to the other clusters.

k8s-copier is not necessarily the best way to do things, but I would like to begin the process of soliciting feedback in that repository, as well as suggestions for other solutions in the current issue.

**Why is this needed**: Some standards should evolve for how to use Federation in conjunction with existing systems, and ideally, in a systematic way to help accommodate unforeseen scenarios.  This is a gap in migrating existing workloads from single-cluster to federation.

Pointers to potential solutions would be much appreciated, and would make Federation more approachable.

/kind feature

**Comment by michaelfig** [comment]
A useful related feature would be a way to specify via `placement` that a given Federated resource should not be scheduled on the host cluster, without also deleting a source resource that has the same name.

Currently, if I have a cert-manager Certificate that generates a Secret called `cloud-secret` in the host cluster, which k8s-copier uses to update the `spec.template` of a FederatedSecret also called `cloud-secret`, but whose `placement` avoids the host cluster, federation will try to delete the host cluster's source `cloud-secret`.

I work around this by having the Certificate generate a `cloud-secret-master` secret, and have the FederatedSecret `cloud-secret` placement in all clusters, but that solution is not optimal for controllers such as Flux HelmReleases, where the resource must be unique and named the same in all clusters, or there are differences in behaviour.

Suggestions for proper solutions to this problem are also solicited, as I don't know what's idiomatic for federation users.

**Comment by marun** [comment]
@michaelfig fedv2 supports 2 ways of leaving existing resources alone in a given cluster (any cluster, not just the host cluster).   The implementation of #612 ensures that federation only operates on resources that are labeled with `federation.k8s.io/managed: true` (that includes deletion).  If a federated resource were created without placement for a given cluster (including the host cluster), then an existing resource in that cluster would not be deleted.  The catch is that if unselected cluster were ever selected for placement, the resource would be automatically adopted and subsequent unselection would result in resource removal.

Automatic adoption can be disabled for the entire control plane as per #805.  See the chart documentation for `syncController.skipAdoptingResources`: 

https://github.com/kubernetes-sigs/federation-v2/blob/master/charts/federation-v2/README.md#configuration

It may be that we need to support a label that when appearing on a resource disables adoption.  The pending implementation of #740 would allow unintentional use of this label to be discovered via the status of a federated resource.

**Comment by marun** [comment]
Does the above comment satisfy this issue?  Otherwise I'm not clear on what exactly is intended to be the actionable result of the issue.  The mention of 'single cluster controllers' in the title suggests it may have to do with respecting local modifications, but if that is the case this issue should likely be closed in favor of #633.

**Comment by michaelfig** [comment]
Thanks so much for your feedback!  It looks like #612 solves this for me.

You can close this issue if you'd like.  I'd created it as a placeholder for communicating the process around using one cluster's automatically-updated resources as a template for Federated resources.  Maybe I didn't make that explicit.

Maybe that belongs in a different forum, but I thought it was a frequent-enough situation that a suggested solution should be at least hinted in the user guide.

**Comment by marun** [comment]
Feel free to propose additions to the user guide that you think would be helpful to others.
