### ISSUE TITLE
Allow -oyaml for kubefedctl join

### ISSUE THREAD

**Issue by michaelfig** [kubernetes-sigs/kubefed#841]
**What would you like to be added**:

As discussed in https://github.com/kubernetes-sigs/federation-v2/pull/781#issuecomment-486460654 I would like to settle on a design for a dry-run `kubefedctl join -oyaml`.  I may be able to work on it if there is agreement on the direction to take.

The main constraint is that (unlike `kubefedctl enable` and `kubefedctl federate`) portions of the generated YAML are targeted to the host cluster, and other portions to the target cluster.

One idea I had would be to have an additional join flag (`--role=host` or `--role=target`) and have `kubefedctl join -oyaml ...` without a `--role` return an error message that says `--role` is necessary to generate YAML.  I'm uncertain whether `--role` would be useful outside of `-oyaml`.

Another idea would be to add `kubefedctl phase join-host -oyaml` and `kubefedctl phase join-target -oyaml` subcommands, like `kubeadm` has for advanced usage without polluting the main CLI.  This may be more cognitive burden as `join-host`, `join-target`, and `join` should probably support all the same options.

Anyway, please add your two cents, especially if you envision a better design.

**Why is this needed**: I want to audit the YAML that `kubefedctl join` applies, and potentially to apply the host and target role's YAML in separate commands (as there is no single user/kubeconfig that has all the required RBAC in both the host and target cluster).

/kind feature

**Comment by marun** [comment]
The yaml that is applied to a cluster targeted to be joined will be easy enough.  The resulting yaml would be the same for any cluster for a given scope.

Yaml for the host cluster side of a given join isn't so simple, because it depends on the the auth credentials of the service account created in the joined cluster by the first part of the join operation.  How would you propose to address this dependency in the context of yaml?

The primary reason the `kubefedctl` cli tool being created was coordinating a join across clusters.  If we could have done it trivially with yaml alone, we surely would have done so.

**Comment by michaelfig** [comment]
I'm not suggesting that the two phases/roles need to be independent.  They would need the same input parameters, but could be dependent on a specific ordering.

For example, the `join-host` could look up values (such as the service account credentials), and if they were not yet created, squawk with `join-target` needs to be applied first.

Then, I could do:

1. Run `join-target -oyaml` (or `join --role=target -oyaml`).
2. Inspect and apply the YAML to the target.
3. Run `join-host -oyaml` (or `join --role=host -oyaml`) with the same parameters as 1.
4. Inspect and apply the YAML to the host.

2 and 4 would be implicitly done if `-oyaml` was not specified.

**Comment by marun** [comment]
I think what you are suggesting is reasonable.  The caveats to my tentative go-ahead are: 

 - This will be sufficiently risky that I think it should be deferred until after `v1beta1`
 - Comprehensive testing will be required.  We currently lack good coverage for many cli commands, including `join`, and I would like to see decent coverage merged for the command (via something like the cli testing framework proposed by #828) before we consider changing it in a major way.

**Comment by michaelfig** [comment]
Okay, sounds good.  Is there some GitHub label you can apply to this issue so that we remember to come back to it?
