### ISSUE TITLE
Attempting to enable a type in group `extensions` should fail 

### ISSUE THREAD

**Issue by marun** [kubernetes-sigs/kubefed#855]
Currently it is possible to enable a type in the `extensions` group (e.g. `kubefedctl enable deployments.extensions`).  Given that `extensions` is deprecated, and the types it contains have been available in other groups for some time, any `enable` invocation should instead be made for the type in the new non-deprecated group.  This would avoid the potential of someone accidentally enabling an `extensions` group. 

/kind bug

**Comment by marun** [comment]
I was under the impression that the `extensions` group was long deprecated, but it was only deprecated as of kube `1.14`.  `Ingress` resources, at a minimum, were still in the `extensions` group as of `1.13`.  I think this precludes ignoring the extensions group for the purposes of enabling a type unless we only want to support kube >= `1.14`.

@irfanurrehman This suggests that you will need to adjust the lookup strategy used by `federate`.

cc: @font @shashidharatd @xunpan @pmorie

**Comment by irfanurrehman** [comment]
Ack!
