### ISSUE TITLE
Rename repo to kubefed

### ISSUE THREAD

**Issue by pmorie** [kubernetes-sigs/kubefed#860]
This issue represents our group consensus to rename the repo to `kubefed`.

- [x] Rename software references to `federation` to `kubefed`
  - [x] API groups
  - [x] Helm chart name
  - [x] Name of `federation-system` namespace
- [x] Rename repository to `kubernetes-sigs/kubefed`
- [x] Rename appropriate doc references to `kubefed`

/kind feature

**Comment by marun** [comment]
#697 should be coordinated with this issue so that import references in the code are changed from `github.com/kubernetes-sigs/federation-v2` to  `sig.k8s.io/kubefed`.

cc: @gyliu513

**Comment by shashidharatd** [comment]
probably docker image needs a rename too.

**Comment by shashidharatd** [comment]
IMHO, `federation-system` namespace name is standard and does not warrant a name change.

**Comment by marun** [comment]
@shashidharatd I think the default system namespace should become `kubefed-system` to avoid confusion, but wouldn't prevent anyone from deploying with the old name.

**Comment by shashidharatd** [comment]
Some additional TODOs from https://github.com/kubernetes-sigs/federation-v2/pull/865#issuecomment-491027453.  This is by no means complete, and I intend to re-review as you post updates and add to this list as I find more items.

 - [ ] - `s/federation controllers/kubefed controllers/` (comments and docs)
 - [ ] - `s/federation-namespace/kubefed-namespace/` (controller manager and e2e arg)
 - [ ] - `s/federation namespace/kubefed namespace/` (comments and docs)
 - [ ] - `s/federation-config/kubefed-config/` (controller manager arg)
 - [ ] - `s/federationConfig/kubefedConfig/` (controller manager code)
 - [ ] - `s/federation config/kubefed config/` (controller manager comments)
 - [ ] - `s/FederationSystemNamespace/KubefedSystemNamespace/`
 - [ ] - `s/federationNamespace/kubefedNamespace/`
 - [ ] - `s/federation-controller-manager/kubefed-controller-manager/`
 - [ ] - `s/federation control plane/kubefed control plane/` (comments and docs)
 - [ ] - `s/FederationConfig/KubefedConfig/` (also need to rename example config files)
 - [ ] - `s/federation/kubefed/` (in docs and comments where appropriate.  'federation of a resource' is an appropriate use.  something like 'federation API' needs to be changed to 'kubefed API')
 - [ ] - `s/federation v2/kubefed/` (commands and docs)
 - [ ] - `s/federation/kubefed/` (names of roles, role bindings, service accounts, deployment name for helm chart and related documentation)
 - [ ] - `s/federation.k8s.io/kubefed.k8s.io/` group names for kubefed types (including generated types)
 - [ ] - `s/FederatedCluster/KubefedCluster/` (The `Federated` prefix is used for resources that are managed in member clusters, and I'm not sure if ever made sense for a resource configuring a member cluster.)

**Comment by shashidharatd** [comment]
This issue can be closed as there is another issue to reexamine docs https://github.com/kubernetes-sigs/kubefed/issues/891.
