### ISSUE TITLE
Retry if attempt to add cluster client fails

### ISSUE THREAD

**Issue by font** [kubernetes-sigs/kubefed#878]
**What happened**:
`FederatedCluster` never became `Ready` after initial attempt to add cluster client failed:

```
I0510 14:25:51.330936       1 federated_informer.go:207] Cluster federation-test/cluster1 not added; it is not ready.
I0510 14:25:51.330938       1 federated_informer.go:207] Cluster federation-test/cluster1 not added; it is not ready.
I0510 14:25:51.331001       1 federated_informer.go:207] Cluster federation-test/cluster1 not added; it is not ready.
I0510 14:25:51.331147       1 controller.go:132] ClusterController observed a new cluster: cluster1
E0510 14:25:51.331259       1 controller.go:136] Failed to create corresponding restclient of kubernetes cluster: no matches for kind "Cluster" in version "clusterregistry.k8s.io/v1alpha1"
W0510 14:26:00.535202       1 controller.go:169] Failed to retrieve stored data for cluster cluster1
W0510 14:26:10.541271       1 controller.go:169] Failed to retrieve stored data for cluster cluster1
W0510 14:26:20.548210       1 controller.go:169] Failed to retrieve stored data for cluster cluster1
W0510 14:26:30.550183       1 controller.go:169] Failed to retrieve stored data for cluster cluster1
W0510 14:26:40.557431       1 controller.go:169] Failed to retrieve stored data for cluster cluster1
W0510 14:26:50.565333       1 controller.go:169] Failed to retrieve stored data for cluster cluster1
W0510 14:27:00.572202       1 controller.go:169] Failed to retrieve stored data for cluster cluster1
W0510 14:27:10.579465       1 controller.go:169] Failed to retrieve stored data for cluster cluster1
W0510 14:27:20.586610       1 controller.go:169] Failed to retrieve stored data for cluster cluster1
```

We should probably re-attempt to add cluster if the following fails:
https://github.com/kubernetes-sigs/federation-v2/blob/68bca8c23e006a0ebcbdc66e1555d034d5c2d4bb/pkg/controller/federatedcluster/controller.go#L168-L171

This means we have a `FederatedCluster` stored in the API but no cluster client stored for it because the following failed:
https://github.com/kubernetes-sigs/federation-v2/blob/68bca8c23e006a0ebcbdc66e1555d034d5c2d4bb/pkg/controller/federatedcluster/controller.go#L134-L138

**What you expected to happen**:
`FederatedCluster` becomes `Ready`

**How to reproduce it (as minimally and precisely as possible)**:
Initial attempt to add cluster client for `FederatedCluster` in function `addToClusterSet` fails:
https://github.com/kubernetes-sigs/federation-v2/blob/68bca8c23e006a0ebcbdc66e1555d034d5c2d4bb/pkg/controller/federatedcluster/controller.go#L123-L140

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`)
- Federation version 0.0.10
- Install method (helm vs script)
- Install configuration (namespaced vs cluster-scoped)
- Others

/kind bug

**Comment by marun** [comment]
This represents a big hole in how cluster health is determined.  Cluster clients are added once, when the `KubeFedCluster` is first encountered, and then never updated.  We need a proper reconcile loop that responds to changes in cluster configuration.

Prior to #869, this same issue would have affected the federated informer since the cluster registry clusters were not being watched for changes, but the api endpoint is now on the kubefed cluster which is being watched.

cc: @shashidharatd

**Comment by marun** [comment]
Moving to v0.1.0 - this needs to be fixed for beta.
