### ISSUE TITLE
Refactor federatedtypeconfig controller

### ISSUE THREAD

**Issue by font** [kubernetes-sigs/kubefed#884]
The `FederatedTypeConfig` controller is in need of a refactor, particularly the `reconcile` method. Starting/stopping the sync and status controllers as well as the status update should be refactored. Additionally status should not be updated if it has not changed.

/kind feature

**Comment by marun** [comment]
@font I don't think status updates should be avoided, even if nothing has changed.  As per the example of propagation status, `lastProbeTime` should always be updated to ensure that the currency of status can be trivially determined.
