### ISSUE TITLE
problems in deploying Federaion v2 using kubeadm

### ISSUE THREAD

**Issue by yongzhedamaoxian** [kubernetes-sigs/kubefed#889]
**Which test(s) are failing**:
I deployed Federation v2 in GKE,now I want to deploy it using kubeadm.I did as I saw in user guide except the part Create Clusters,and I have created my Federation by helm.When I try to join the host cluster in the Federation,there is something wrong.I know the user guide advise a list of Kubernetes environments that have been tested.Is it ok using kubeadm?

`kubectl config get-contexts`
`CURRENT   NAME       CLUSTER      AUTHINFO           NAMESPACE`
`*         cluster1   kubernetes   kubernetes-admin`
`         cluster2   cluster2     admin`
`kubefedctl join cluster1 --cluster-context cluster1 \`
`>     --host-cluster-context cluster1 --v=2`
`Error: Error retrieving FederationConfig "federation-system/federation-v2": no matches for kind` `"FederationConfig" in version "core.federation.k8s.io/v1alpha1"`

**Since when has it been failing**:
today
**Reason for failure**:
I don’t have any idea.
**Anything else we need to know**:
I am Chinese and sorry for my bad writing and the noises.By the way,Using the latest helm,there is something wrong deploying the federation v2.I need to use the  lower version to complete it.
K8s version:1.14.1

/kind failing-test

**Comment by marun** [comment]
@yongzhedamaoxian Helm is the only supported way to deploy.  Please document what helm version and what chart version you are using to install and the problems you are encountering.
