### ISSUE TITLE
Re-examine doc after kubefed rename

### ISSUE THREAD

**Issue by pmorie** [kubernetes-sigs/kubefed#891]
This issue is to re-examine the doc content after the merge of #865 to find any places where we may have missed renaming or where grammatical changes may be required.

@abrennan89 is going to take this one, but she's not in the kubernetes-sigs org yet.

**Comment by abrennan89** [comment]
Added PR #904 for initial changes - awaiting feedback

**Comment by abrennan89** [comment]
#939 - @marun is working on final changes to this afaik.
