### ISSUE TITLE
Deletion semantics for higher level resources

### ISSUE THREAD

**Issue by irfanurrehman** [kubernetes-sigs/kubefed#90]
Federation v2 follows a layered approach such that the higher level resources depend on the lower level federated types for propogation and rconciliation of k8s objects into federated clusters.
To create, for example an automated distribution of deployment replicas, an user can only create a `FederatedDeployment` and `ReplicaSchedulingPreference` (as defined in #46). The higher level RSP resource controller will observe this and create an override `(FederatedDeploymentOverride)` and a placement `(FederatedDeploymentPlacement)` to reconcile this user intent into clusters. The RSP controller can further update the corresponding override and template to reconcile cluster capacity and/or clusters leaving or joining this federation.

A peculiar case is when the higher level resource is deleted; should the controller also delete the corresponding override and placement resources or leave them behind? This becomes peculiar, because the lower level resources (override and placement) might have existed prior to creation of the higher level resource, in which case the higher level resource, adopted and updated them, if needed.

The answer probably is to use a cascading deleting mechanism and/or a parentRef (ObjectMeta.OwnerReferences) in such a scenario.
The user can specify --cascade=true/false (with some default) to control this behaviour.

**Comment by marun** [comment]
When would it ever be desirable for higher-level resource deletion to delete lower-level resources by default?  The dependency graph is arguably directional (from high-level to low-level).  It could be possible for a UI to support manual deletion of related resources, but I think it would be surprising for that to happen automatically.

I do think there is value in the controller for a higher-level type to add finalizers to lower-level types (e.g. scheduling controller add finalizers to template) to ensure cleanup if the lower level resource would be removed.  Such a scheme would be consistent with the directional relationship of the resources.

**Comment by irfanurrehman** [comment]
> When would it ever be desirable for higher-level resource deletion to delete lower-level resources by default?

I did not specify a necessary default behaviour :). IMHO, either (cascade or no cascade) could be default.  
The use case that we have in mind is: 
User creates a `FederatedDeploymenttemplate` and provides preferences using `ReplicaSchedulingPreferences` and thats all. In this case the override and placement actually are created by the system. When user doesn't want these anymore, he deletes `FederatedDeploymenttemplate` `ReplicaSchedulingPreferences`. Without an option to delete the lower level resources in the dependency graph, the override and placement will be left behind. Its arguable that without a template, override and/or placement both wont be of any use. To me it seems valuable to leave a switch with the user to have control on such behaviour.

Also one view of the layered system would be to visualise the higher level resources to be users of lower level resources, where its up to the higher level resource controller to define its usage behaviour, which includes crud of its target resource in a layered fashion (or the dependency tree, as you call it).
Perhaps this discussion can be widened to considering the template as the primary resource among template, override and placement. Does it make sense?

**Comment by marun** [comment]
I think the template is already on its way to being the primary resource.  At present explicit placement is required, but #75 is likely to make that optional for all namespaced resources.  The catch is that an override resource needs to exist before its associated template if member clusters are to receive those overrides on creation of target resources.  This is critical for Jobs, whose `Completions` field is immutable (#44).

Its not clear to me what deletion semantics should be given the dependencies between resources.  Near-term (certainly pre-alpha), I would not expect automated deletion to be a priority.  Hopefully users can participate in improving the UX once they have an alpha release to work with.

**Comment by marun** [comment]
@irfanurrehman Would it make sense for the RSP controller to add ownership references to rsp resources such that deletion of a template would ensure deletion an owned rsp resource?

**Comment by irfanurrehman** [comment]
> @irfanurrehman Would it make sense for the RSP controller to add ownership references to rsp resources such that deletion of a template would ensure deletion an owned rsp resource?

Yes it seems logical to me, because creation of the template would be what triggers the creation of placement and override in the first place.
