### ISSUE TITLE
Rename occurences of `Kubefed` to `KubeFed`

### ISSUE THREAD

**Issue by pmorie** [kubernetes-sigs/kubefed#907]
Per the Wednesday May 15 WG meeting consensus.

cc @abrennan89

**Comment by Jaanki** [comment]
@pmorie Is this to be changed in docs only or in the source code too like function names?

**Comment by abrennan89** [comment]
@Jaanki I have an open issue for this in docs; https://github.com/kubernetes-sigs/kubefed/issues/891

**Comment by Jaanki** [comment]
@abrennan89 I was thinking to take this up. I see #891 is not assigned to anyone. If you are not planning to work on it, I would be happy too :)

**Comment by marun** [comment]
@Jaanki This is already being worked on as part of #912

**Comment by marun** [comment]
The PR author is not in the ks org so assignment was not possible.

**Comment by marun** [comment]
Superceded by #936
