### ISSUE TITLE
E2e tests for higher level resources

### ISSUE THREAD

**Issue by irfanurrehman** [kubernetes-sigs/kubefed#91]
Some higher level resources need e2e tests for actual end to end functionality validation. Below is the list of current such resources which certainly need additional e2e tests:
- [ ] ReplicaSchedulingPreferences as in #46.
- [ ] MultiClusterDNS as in #59

The implementation of these tests is dependent on #89 (or some other strategy, for example self validation external to CI using managed clusters or BYOC).

**Comment by marun** [comment]
@irfanurrehman Can RSP testing be considered complete with the merging of #392?

@shashidharatd Is there additional testing needed to satisfy the e2e requirement listed above?

**Comment by irfanurrehman** [comment]
For RSP tests the answer is yes.
Will leave it to @shashidharatd to update for MultiClusterDNS tests.

**Comment by shashidharatd** [comment]
There were some test cases missing like `cluster fail-over` which required 2 clusters to test. Now we have support for deploying multiple clusters in CI, we should add such test cases.

**Comment by marun** [comment]
@shashidharatd Would you please add detail to this issue to aid in either implementation or review of that testing?

**Comment by irfanurrehman** [comment]
@shashidharatd can we consider the e2e testing complete for service dns now?
