### ISSUE TITLE
Validations for KubefedConfig API

### ISSUE THREAD

**Issue by font** [kubernetes-sigs/kubefed#916]
### Field Validations for [KubefedConfig](https://github.com/kubernetes-sigs/kubefed/blob/master/pkg/apis/core/v1alpha1/kubefedconfig_types.go):

- `scope` must be a valid enum value. It should be immutable.
- `ControllerDuration`
    - `availableDelay` is a valid `int64` > 0
    - `unavailableDelay` is a valid `int64` > 0
- `LeaderElectConfig`
    - `leaseDuration` is a valid `int64` > 0 and must be > `renewDeadline`
    - `renewDeadline` is a valid `int64` > 0 and must be > `retryPeriod * JitterFactor`
    - `retryPeriod` is a valid `int64` > 0
    - `resourceLock` should be a valid enum value
- `FeatureGatesConfig`
    - `name` should be a valid feature name
    - `configuration` should be a valid enum value
- `ClusterHealthCheckConfig`
    - All fields should be a valid `int64` > 0
- `SyncControllerConfig`
    - `AdoptResources` should be a valid enum value.

**Comment by xunpan** [comment]
- LeaderElectConfig
  - leaseDuration must be greater than renewDeadline
  - renewDeadline must be greater than retryPeriod*JitterFactor
