### ISSUE TITLE
fail to use the kubefedctl tool to join clusters vie GKE

### ISSUE THREAD

**Issue by yongzhedamaoxian** [kubernetes-sigs/kubefed#932]
**What happened**:
`kubefedctl join cluster3 --cluster-context cluster3  --host-cluster-context cluster3 --v=2`
```
I0528 12:33:03.979080   32537 join.go:161] Args and flags: name cluster3, host: cluster3, host-system-namespace: federation-system, kubeconfig: , cluster-context: cluster3, secret-name: , dry-run: false
F0528 12:33:04.056096   32537 join.go:128] Error: Error retrieving FederationConfig "federation-system/federation-v2": no matches for kind "FederationConfig" in version "core.federation.k8s.io/v1alpha1"
```
**What you expected to happen**:
Join sucessfully
**How to reproduce it (as minimally and precisely as possible)**:
1 Create a GKE cluster with version 1.12.7-gke.10
2 Follow the kubefed guide via gke

**Anything else we need to know?**:
**Environment**:
- Kubernetes version (use `kubectl version`)
K8s:
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b
08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:
"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.7-gke.10", GitCommit:"8d9b8641e72cf7c96efa61
421e87f96387242ba1", GitTreeState:"clean", BuildDate:"2019-04-12T22:59:24Z", GoVersion:"go1.10.8b4", Compiler:"gc",
 Platform:"linux/amd64"}
```
- helm version (use `helm version`)
helm:
```
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
```
- kubefed version
0.1.0-rc2   
- Install method (helm vs script)
helm

/kind bug

**Comment by marun** [comment]
@yongzhedamaoxian Previous pre-release versions of kubefed are not supportable.  Please reopen this bug if you can reproduce it against v0.1.0-rc2 or greater.

**Comment by yongzhedamaoxian** [comment]
> @yongzhedamaoxian Previous pre-release versions of kubefed are not supportable. Please reopen this bug if you can reproduce it against v0.1.0-rc2 or greater.

I have changed.Please reopen

**Comment by marun** [comment]
@yongzhedamaoxian Ah, now the error is clear to me. It appears that you are using an outdated version of `kubefedctl`.  Please use the version of `kubefectl` corresponding to the release you are targeting (i.e. `v0.1.0-rc2`).

**Comment by yongzhedamaoxian** [comment]
> @yongzhedamaoxian Ah, now the error is clear to me. It appears that you are using an outdated version of `kubefedctl`. Please use the version of `kubefectl` corresponding to the release you are targeting (i.e. `v0.1.0-rc2`).

ok.Let me try

**Comment by yongzhedamaoxian** [comment]
> > @yongzhedamaoxian Ah, now the error is clear to me. It appears that you are using an outdated version of `kubefedctl`. Please use the version of `kubefectl` corresponding to the release you are targeting (i.e. `v0.1.0-rc2`).
> 
> ok.Let me try

thank you.I have made it

**Comment by marun** [comment]
@yongzhedamaoxian Glad to hear!  Does that mean this issue can be closed?

**Comment by yongzhedamaoxian** [comment]
> @yongzhedamaoxian Glad to hear! Does that mean this issue can be closed?

Yes!!
