### ISSUE TITLE
Higher level HPA Preferences API and controller

### ISSUE THREAD

**Issue by irfanurrehman** [kubernetes-sigs/kubefed#95]
Its easy to federate a given k8s resource with the current federation v2 infrastructure. Federated HPA is also no exception. Default propagation of hpa with possible overrides per cluster (as with using template, overrides and placements) has some, but limited usage. A higher level HPA scheduling API and controller with extended logic makes for a feature set with more usage and value.

A suitable resource name for this could be `HPASchedulingPreferences` (similar to `ReplicaSchedulingPreferences`) under group `federatedscheduling`.
This also provides feature parity with federation V1.

**Comment by a0144** [comment]
what is the status of this feature?

**Comment by irfanurrehman** [comment]
@a0144 this was put out on the backlog to be explored if an user requirement comes up, or  interested user/users show up with a relevant use case. Do you have a use case which can substantiate the need of this feature?

**Comment by a0144** [comment]
@irfanurrehman yes, I have two on-prem kubeadm clusters, where under normal circumstances only one is used to run the workloads. The pods for each service are scaled up by HPA locally in cluster1 as long as there are enough resources to do so. If not, they should be scaled into the second cluster. If you have some ideas of other ways to make it work I'd be really glad to get some tips.

**Comment by irfanurrehman** [comment]
@a0144. I am not aware of any alternative behaviours to make this work as of now. I would recommend you join the kubefed work group sync tomorrow @ 7:30 PT at https://zoom.us/my/k8s.mc to talk about your use case. I can add an agenda item if you confirm your presence.

**Comment by a0144** [comment]
@irfanurrehman Thanks for the info. I'll join the meeting tomorrow

**Comment by sancyx** [comment]
Hi @irfanurrehman @a0144. Do you have any news on this, like design proposals?

**Comment by irfanurrehman** [comment]
@sancyx this issue is waiting for more evidence of the utility. If you have a reasonable use case then we can talk further about it. Talking about it at the community meeting as mentioned [here](https://github.com/kubernetes-sigs/kubefed/issues/95#issuecomment-516223911) is a good first step.
