### ISSUE TITLE
SchedulingManager test triggers race detector

### ISSUE THREAD

**Issue by marun** [kubernetes-sigs/kubefed#962]
**Which test(s) are failing**:
`Scheduling SchedulingManager when federatedtypeconfig resources are changed related scheduler and plugin controllers should be dynamically disabled/enabled`

**Reason for failure**:

https://gist.github.com/marun/4b4a78cced8d10d48b60fb1676e4e702

/kind failing-test

**Comment by irfanurrehman** [comment]
@marun Do you have any additional info about this. The info generated seemed to have some problem and missing the actual data point that might have resulted in the race.
```
Previous write at 0x00c00036a620 by goroutine 16:
  [failed to restore the stack]
```
We have the read data point listed 
```
  sigs.k8s.io/kubefed/pkg/apis/core/v1beta1.(*FederatedTypeConfig).GetFederatedType()
      /home/travis/gopath/src/sigs.k8s.io/kubefed/pkg/apis/core/v1beta1/federatedtypeconfig_types.go:243 +0x82
```
But am unable to decipher (with this info alone) as to which might be the actual variable that is missing protection.

Let me know if you happen to see it again.

**Comment by marun** [comment]
@irfanurrehman I think the implication is that FTCs used in testing will need to be copied so that tests running concurrently are not in danger of interfering with one another.

**Comment by xunpan** [comment]
I think @font fixed this in 
https://github.com/kubernetes-sigs/kubefed/pull/978/commits

The code duplicate `FederatedTypeConfig` for sync controller to avoid race condition. Though I did not see the exactly part of the lost stack, the fix should work for the case logically.
