### ISSUE TITLE
Update kind to 0.3.0

### ISSUE THREAD

**Issue by marun** [kubernetes-sigs/kubefed#964]
[kind 0.3.0](https://github.com/kubernetes-sigs/kind/releases/tag/v0.3.0) offers a number of improvements including a switch to containerd that should significantly improve startup times.  The switch to containerd will require updates to kubefed's `create-servers.sh` script to account for the difference in configuring an insecure registry.

**Comment by qinpingli** [comment]
Created a PR(#980) for this issue.

**Comment by marun** [comment]
Fixed by #980
