### ISSUE TITLE
Config mechanism for API instantiation

### ISSUE THREAD

**Issue by irfanurrehman** [kubernetes-sigs/kubefed#97]
At a given time frame, federation might have a set of k8s resources federated. Users can further federate their CRD resources into the same federation. Additionally, with the layered approach of a lower level federated types enabling simple federation and higher level types based on the lower level controllers, some users might want all or subset of APIs and controllers eventually in their federation deployment.
This calls for a configuration mechanism, which can make some APIs (and respective controllers) optional by default, and additionally provide a mechanism to enable/disable individual API resources in the federation control plane.
The mechanism should be easy to configure (for an end user) and the implementation can ideally target the infrasctructure setup post the move to CRD based resources (if that happens).

**Comment by marun** [comment]
Is this related to FederatedTypeConfig, which at present defines the placement/template/override/target resources that will configure propagation and also allows propagation to be enabled/disabled?

**Comment by irfanurrehman** [comment]
What I had in mind was more like one time config for example, gating APIs exposed in Apiserver based on some static config and or running necessary controllers based on the same or perhaps a different controller config. This probably is much simpler to achiev and I think the infrastructure for this config is already in place in the aggregated Apiserver that we are currently using.

This thought precluded the discussion we had in last federation sync, where a possible need of different binaries for different controllers was also expressed. We probably need to conclude the best choice, and if needed differentiate a short term and a long term solution.

**Comment by marun** [comment]
I'm not understanding your intent, and think a higher-bandwidth discussion at the next WG meeting might be useful.

**Comment by marun** [comment]
@irfanurrehman @shashidharatd  Revisiting this, what next steps are required to satisfy this issue?  sync controllers and rsp schedulers are both driven by the state of `FederatedTypeConfig`.  Should dns programming (both service- and ingress- based) be similarly driven by configuration?

**Comment by irfanurrehman** [comment]
I think TypeConfig provides a good enough configuration mechanism for controllers that work based on it. We can probably do similar stuff (`ServiceManager ?`) for network (`service, ingress`) types also.

**Comment by irfanurrehman** [comment]
@shashidharatd Please let us know if it makes sense to have a `ServiceManager` akin to `SchedulingManager`. If not I think we can close this issue.
/remove-lifecycle stale
