### ISSUE TITLE
Higher level Job Preferences API and controller

### ISSUE THREAD

**Issue by irfanurrehman** [kubernetes-sigs/kubefed#98]
k8s jobs has already been federated using the simple federation resources (template, placement and override) for jobs. This however does not provide higher level job scheduling logic, which can provide an automated distribution of parallelism and completions for the given job across federated clusters.
This particular use case seems quite valuable and calls for a higher level job scheduling API (aka `JobSchedulingPreferences`) and an associated controller logic.
This also provides feature parity with federation V1.

**Comment by sdminonne** [comment]
@irfanurrehman  I tried to have a look at federation V1 code but I couldn't find `JobSchedulingPreferences`. Instead, I found something concerning
`ReplicaAllocationPreferences` as an annotation with key `federation.kubernetes.io/job-preferences`.
May you give more details? Thanks

**Comment by irfanurrehman** [comment]
In V1 there is a single set of preference annotations. The definition was originally created for deployments and replicasets. The same was later reused for jobs controller, as the intent was first to create an alpha prototype, and most of the fields of existing preferences sort of did fit the usage pattern. The preferences however needed a key name specific to the resource, as you mentioned `federation.kubernetes.io/job-preferences` for jobs. In the case of jobs, many of the preferences fields were meanigless and unused.

In V2 our plan is to have a job specific definition of the API named `JobSchedulingPreferences`. 
@shashidharatd signed up to do this and very recently started work on the same. 
What is your intent digging this information. Are you interested in taking this up? If so, we can sync to fill you in with info, we did already brainstorm about the same.

**Comment by sdminonne** [comment]
@irfanurrehman thanks.
I was having a look at the list of issues and, having some interests in jobs, this one caught my eyes.
I could help on this but I'm not sure to estimate the effort. In mid-July, I'll be in PTO for a couple of weeks and if @shashidharatd already started I don't if and hand-over it's worth.
Eventually, if it's not too work for you guys we can imagine chatting a little before the end of this week.
Thanks
