### ISSUE TITLE
Some kube types exist in more than one group but should be enabled at most once

### ISSUE THREAD

**Issue by marun** [kubernetes-sigs/kubefed#988]
A number of core types exist in more than one group, e.g. (not intended to be an exhaustive list)

 - `deployments` is found in both `extensions/v1beta1` and `apps/v1`
 - `replicasets` is found in both `extensions/v1beta1` and `deployments.apps/v1`
 - `ingresses` is found in both `extensions/v1beta1` and `networking.k8s.io/v1beta1` (as of Kube 1.14)

Currently a FederatedTypeConfig (FTC) must have a name of the form `<target plural name>.<target group name>`, which allows for one of the above types to be enabled more than once (e.g. an FTC for `deployments.apps` and an FTC for `deployments.extensions`) by varying the group of the generated federated CRD (i.e. by passing `--federated-group` to `kubefedctl enable`). This would result in multiple sync controller targeting different endpoints but potentially fighting to modify the same resources.

Is there a way to mechanically determine that a resource in a given group is the same as in a different group?  Or will it be necessary to hard-code types that appear in multiple groups and only allow enabling federation of a type in a single specific group? e.g.

 - attempting to enable `deployment` would always enable `deployments.apps`
 - attempts to enable `ingress` would enable `ingresses.extensions` pre 1.14 and `ingresses.networking.k8s.io` for 1.14 and greater

/kind bug

**Comment by xunpan** [comment]
My understanding for this case is that a resource is federated more than once. In that case, there will be issues for sync-controller. But it seems not a use case to me. So, we can reject the case by  checking during federating a resource. If the resource is already in one FTC as target, it is rejected. We may also need to check in webhook when a FTC is created.
@marun

**Comment by marun** [comment]
@xunpan As per the questions at the end of the issue text, is it possible to detect potential duplication automatically or will special-case handling need to be hardcoded?
