### ISSUE TITLE
Support running in a cluster with restricted pod security policy

### ISSUE THREAD

**Issue by andrewmyhre** [kubernetes-sigs/kubefed#999]
**What would you like to be added**:
- In images/kubefed/Dockerfile when adding the hyperfed user, specify a UID (`RUN adduser -D -g '' -u 1001 hyperfed`)
- In the specs for the `kubefed-admission-webhook` and `kubefed-controller-manager` deployments specify the UID:
```
securityContext:
  runAsUser: 1001
```

This was addressed in #945 but it would appear the change wasn't tested in a restricted pod security policy context. The above changes are required.

Also, the helm chart for version 0.1.0-rc2 still specifies the commands for these deployments to use the `/root/` path rather than the `/hyperfed/` path which was updated in #945.

**Why is this needed**:
Without these changes although the container will not run as root, kubernetes is unable to determine if it is in fact running as a non-root user, so in a cluster with a restricted pod security policy kubernetes will prevent the containers from starting.

/kind feature

**Comment by marun** [comment]
Thank you for suggesting this. Would you like to contribute the fix? We're expecting to release rc3 on Monday June 24th and it would be good to include both #945 and your suggestions.

**Comment by andrewmyhre** [comment]
Sure, I've pushed #1007 to address this.
There are a couple of other tweaks I've made; in my testing I found the binaries were ending up owned by root and the hyperfed user was unable to execute them.

**Comment by marun** [comment]
Fixed by #1007
